/**
 * This file is part of Hercules.
 * http://herc.ws - http://github.com/HerculesWS/Hercules
 *
 * Copyright (C) 2018-2026 Hercules Dev Team
 * Copyright (C) 2018-2020 Andrei Karas (4144)
 *
 * Hercules is free software: you can redistribute it and/or modify
 * it under the terms of the GNU General Public License as published by
 * the Free Software Foundation, either version 3 of the License, or
 * (at your option) any later version.
 *
 * This program is distributed in the hope that it will be useful,
 * but WITHOUT ANY WARRANTY; without even the implied warranty of
 * MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
 * GNU General Public License for more details.
 *
 * You should have received a copy of the GNU General Public License
 * along with this program.  If not, see <http://www.gnu.org/licenses/>.
 */

#ifndef COMMON_PACKETS2003_LEN_SAK_H
#define COMMON_PACKETS2003_LEN_SAK_H

/* This file is autogenerated, please do not commit manual changes */

// Packet: 0x0064
packetLen(0x0064, 55)

// Packet: 0x0065
packetLen(0x0065, 17)

// Packet: 0x0066
packetLen(0x0066, 3)

// Packet: 0x0067
packetLen(0x0067, 37)

// Packet: 0x0068
packetLen(0x0068, 46)

// Packet: 0x0069
packetLen(0x0069, -1)

// Packet: 0x006a
packetLen(0x006A, 23)

// Packet: 0x006b
packetLen(0x006B, -1)

// Packet: 0x006c
packetLen(0x006C, 3)

// Packet: 0x006d
packetLen(0x006D, 108)

// Packet: 0x006e
packetLen(0x006E, 3)

// Packet: 0x006f
packetLen(0x006F, 2)

// Packet: 0x0070
packetLen(0x0070, 3)

// Packet: 0x0071
packetLen(0x0071, 28)

// Packet: 0x0072
packetLen(0x0072, 19)

// Packet: 0x0073
packetLen(0x0073, 11)

// Packet: 0x0074
packetLen(0x0074, 3)

// Packet: 0x0075
packetLen(0x0075, -1)

// Packet: 0x0076
packetLen(0x0076, 9)

// Packet: 0x0077
packetLen(0x0077, 5)

// Packet: 0x0078
packetLen(0x0078, 54)

// Packet: 0x0079
packetLen(0x0079, 53)

// Packet: 0x007a
packetLen(0x007A, 58)

// Packet: 0x007b
packetLen(0x007B, 60)

// Packet: 0x007c
packetLen(0x007C, 41)

// Packet: 0x007d
packetLen(0x007D, 2)

// Packet: 0x007e
packetLen(0x007E, 6)

// Packet: 0x007f
packetLen(0x007F, 6)

// Packet: 0x0080
packetLen(0x0080, 7)

// Packet: 0x0081
packetLen(0x0081, 3)

// Packet: 0x0082
packetLen(0x0082, 2)

// Packet: 0x0083
packetLen(0x0083, 2)

// Packet: 0x0084
packetLen(0x0084, 2)

// Packet: 0x0085
packetLen(0x0085, 5)

// Packet: 0x0086
packetLen(0x0086, 16)

// Packet: 0x0087
packetLen(0x0087, 12)

// Packet: 0x0088
packetLen(0x0088, 10)

// Packet: 0x0089
packetLen(0x0089, 7)

// Packet: 0x008a
packetLen(0x008A, 29)

// Packet: 0x008b
packetLen(0x008B, 23)

// Packet: 0x008c
packetLen(0x008C, -1)

// Packet: 0x008d
packetLen(0x008D, -1)

// Packet: 0x008e
packetLen(0x008E, -1)

// Packet: 0x0090
packetLen(0x0090, 7)

// Packet: 0x0091
packetLen(0x0091, 22)

// Packet: 0x0092
packetLen(0x0092, 28)

// Packet: 0x0093
packetLen(0x0093, 2)

// Packet: 0x0094
packetLen(0x0094, 6)

// Packet: 0x0095
packetLen(0x0095, 30)

// Packet: 0x0096
packetLen(0x0096, -1)

// Packet: 0x0097
packetLen(0x0097, -1)

// Packet: 0x0098
packetLen(0x0098, 3)

// Packet: 0x0099
packetLen(0x0099, -1)

// Packet: 0x009a
packetLen(0x009A, -1)

// Packet: 0x009b
packetLen(0x009B, 5)

// Packet: 0x009c
packetLen(0x009C, 9)

// Packet: 0x009d
packetLen(0x009D, 17)

// Packet: 0x009e
packetLen(0x009E, 17)

// Packet: 0x009f
packetLen(0x009F, 6)

// Packet: 0x00a0
packetLen(0x00A0, 23)

// Packet: 0x00a1
packetLen(0x00A1, 6)

// Packet: 0x00a2
packetLen(0x00A2, 6)

// Packet: 0x00a3
packetLen(0x00A3, -1)

// Packet: 0x00a4
packetLen(0x00A4, -1)

// Packet: 0x00a5
packetLen(0x00A5, -1)

// Packet: 0x00a6
packetLen(0x00A6, -1)

// Packet: 0x00a7
packetLen(0x00A7, 8)

// Packet: 0x00a8
packetLen(0x00A8, 7)

// Packet: 0x00a9
packetLen(0x00A9, 6)

// Packet: 0x00aa
packetLen(0x00AA, 7)

// Packet: 0x00ab
packetLen(0x00AB, 4)

// Packet: 0x00ac
packetLen(0x00AC, 7)

// Packet: 0x00ae
packetLen(0x00AE, -1)

// Packet: 0x00af
packetLen(0x00AF, 6)

// Packet: 0x00b0
packetLen(0x00B0, 8)

// Packet: 0x00b1
packetLen(0x00B1, 8)

// Packet: 0x00b2
packetLen(0x00B2, 3)

// Packet: 0x00b3
packetLen(0x00B3, 3)

// Packet: 0x00b4
packetLen(0x00B4, -1)

// Packet: 0x00b5
packetLen(0x00B5, 6)

// Packet: 0x00b6
packetLen(0x00B6, 6)

// Packet: 0x00b7
packetLen(0x00B7, -1)

// Packet: 0x00b8
packetLen(0x00B8, 7)

// Packet: 0x00b9
packetLen(0x00B9, 6)

// Packet: 0x00ba
packetLen(0x00BA, 2)

// Packet: 0x00bb
packetLen(0x00BB, 5)

// Packet: 0x00bc
packetLen(0x00BC, 6)

// Packet: 0x00bd
packetLen(0x00BD, 44)

// Packet: 0x00be
packetLen(0x00BE, 5)

// Packet: 0x00bf
packetLen(0x00BF, 3)

// Packet: 0x00c0
packetLen(0x00C0, 7)

// Packet: 0x00c1
packetLen(0x00C1, 2)

// Packet: 0x00c2
packetLen(0x00C2, 6)

// Packet: 0x00c3
packetLen(0x00C3, 8)

// Packet: 0x00c4
packetLen(0x00C4, 6)

// Packet: 0x00c5
packetLen(0x00C5, 7)

// Packet: 0x00c6
packetLen(0x00C6, -1)

// Packet: 0x00c7
packetLen(0x00C7, -1)

// Packet: 0x00c8
packetLen(0x00C8, -1)

// Packet: 0x00c9
packetLen(0x00C9, -1)

// Packet: 0x00ca
packetLen(0x00CA, 3)

// Packet: 0x00cb
packetLen(0x00CB, 3)

// Packet: 0x00cc
packetLen(0x00CC, 6)

// Packet: 0x00cd
packetLen(0x00CD, 3)

// Packet: 0x00ce
packetLen(0x00CE, 2)

// Packet: 0x00cf
packetLen(0x00CF, 27)

// Packet: 0x00d0
packetLen(0x00D0, 3)

// Packet: 0x00d1
packetLen(0x00D1, 4)

// Packet: 0x00d2
packetLen(0x00D2, 4)

// Packet: 0x00d3
packetLen(0x00D3, 2)

// Packet: 0x00d4
packetLen(0x00D4, -1)

// Packet: 0x00d5
packetLen(0x00D5, -1)

// Packet: 0x00d6
packetLen(0x00D6, 3)

// Packet: 0x00d7
packetLen(0x00D7, -1)

// Packet: 0x00d8
packetLen(0x00D8, 6)

// Packet: 0x00d9
packetLen(0x00D9, 14)

// Packet: 0x00da
packetLen(0x00DA, 3)

// Packet: 0x00db
packetLen(0x00DB, -1)

// Packet: 0x00dc
packetLen(0x00DC, 28)

// Packet: 0x00dd
packetLen(0x00DD, 29)

// Packet: 0x00de
packetLen(0x00DE, -1)

// Packet: 0x00df
packetLen(0x00DF, -1)

// Packet: 0x00e0
packetLen(0x00E0, 30)

// Packet: 0x00e1
packetLen(0x00E1, 30)

// Packet: 0x00e2
packetLen(0x00E2, 26)

// Packet: 0x00e3
packetLen(0x00E3, 2)

// Packet: 0x00e4
packetLen(0x00E4, 6)

// Packet: 0x00e5
packetLen(0x00E5, 26)

// Packet: 0x00e6
packetLen(0x00E6, 3)

// Packet: 0x00e7
packetLen(0x00E7, 3)

// Packet: 0x00e8
packetLen(0x00E8, 8)

// Packet: 0x00e9
packetLen(0x00E9, 19)

// Packet: 0x00ea
packetLen(0x00EA, 5)

// Packet: 0x00eb
packetLen(0x00EB, 2)

// Packet: 0x00ec
packetLen(0x00EC, 3)

// Packet: 0x00ed
packetLen(0x00ED, 2)

// Packet: 0x00ee
packetLen(0x00EE, 2)

// Packet: 0x00ef
packetLen(0x00EF, 2)

// Packet: 0x00f0
packetLen(0x00F0, 3)

// Packet: 0x00f1
packetLen(0x00F1, 2)

// Packet: 0x00f2
packetLen(0x00F2, 6)

// Packet: 0x00f3
packetLen(0x00F3, 8)

// Packet: 0x00f4
packetLen(0x00F4, 21)

// Packet: 0x00f5
packetLen(0x00F5, 8)

// Packet: 0x00f6
packetLen(0x00F6, 8)

// Packet: 0x00f7
packetLen(0x00F7, 2)

// Packet: 0x00f8
packetLen(0x00F8, 2)

// Packet: 0x00f9
#if PACKETVER >= 20031117
packetLen(0x00F9, 26)
#elif PACKETVER >= 20031110
packetLen(0x00F9, 28)
#elif PACKETVER >= 20031029
packetLen(0x00F9, 26)
#endif

// Packet: 0x00fa
packetLen(0x00FA, 3)

// Packet: 0x00fb
packetLen(0x00FB, -1)

// Packet: 0x00fc
packetLen(0x00FC, 6)

// Packet: 0x00fd
packetLen(0x00FD, 27)

// Packet: 0x00fe
packetLen(0x00FE, 30)

// Packet: 0x00ff
packetLen(0x00FF, 10)

// Packet: 0x0100
packetLen(0x0100, 2)

// Packet: 0x0101
packetLen(0x0101, 6)

// Packet: 0x0102
packetLen(0x0102, 6)

// Packet: 0x0103
packetLen(0x0103, 30)

// Packet: 0x0104
#if PACKETVER >= 20031117
packetLen(0x0104, 79)
#elif PACKETVER >= 20031110
packetLen(0x0104, 81)
#elif PACKETVER >= 20031029
packetLen(0x0104, 79)
#endif

// Packet: 0x0105
packetLen(0x0105, 31)

// Packet: 0x0106
packetLen(0x0106, 10)

// Packet: 0x0107
packetLen(0x0107, 10)

// Packet: 0x0108
packetLen(0x0108, -1)

// Packet: 0x0109
packetLen(0x0109, -1)

// Packet: 0x010a
packetLen(0x010A, 4)

// Packet: 0x010b
packetLen(0x010B, 6)

// Packet: 0x010c
packetLen(0x010C, 6)

// Packet: 0x010d
packetLen(0x010D, 2)

// Packet: 0x010e
packetLen(0x010E, 11)

// Packet: 0x010f
packetLen(0x010F, -1)

// Packet: 0x0110
packetLen(0x0110, 10)

// Packet: 0x0111
packetLen(0x0111, 39)

// Packet: 0x0112
packetLen(0x0112, 4)

// Packet: 0x0113
packetLen(0x0113, 10)

// Packet: 0x0114
packetLen(0x0114, 31)

// Packet: 0x0115
packetLen(0x0115, 35)

// Packet: 0x0116
packetLen(0x0116, 10)

// Packet: 0x0117
packetLen(0x0117, 18)

// Packet: 0x0118
packetLen(0x0118, 2)

// Packet: 0x0119
packetLen(0x0119, 13)

// Packet: 0x011a
packetLen(0x011A, 15)

// Packet: 0x011b
packetLen(0x011B, 20)

// Packet: 0x011c
packetLen(0x011C, 68)

// Packet: 0x011d
packetLen(0x011D, 2)

// Packet: 0x011e
packetLen(0x011E, 3)

// Packet: 0x011f
packetLen(0x011F, 16)

// Packet: 0x0120
packetLen(0x0120, 6)

// Packet: 0x0121
packetLen(0x0121, 14)

// Packet: 0x0122
packetLen(0x0122, -1)

// Packet: 0x0123
packetLen(0x0123, -1)

// Packet: 0x0124
packetLen(0x0124, 21)

// Packet: 0x0125
packetLen(0x0125, 8)

// Packet: 0x0126
packetLen(0x0126, 8)

// Packet: 0x0127
packetLen(0x0127, 8)

// Packet: 0x0128
packetLen(0x0128, 8)

// Packet: 0x0129
packetLen(0x0129, 8)

// Packet: 0x012a
packetLen(0x012A, 2)

// Packet: 0x012b
packetLen(0x012B, 2)

// Packet: 0x012c
packetLen(0x012C, 3)

// Packet: 0x012d
packetLen(0x012D, 4)

// Packet: 0x012e
packetLen(0x012E, 2)

// Packet: 0x012f
packetLen(0x012F, -1)

// Packet: 0x0130
packetLen(0x0130, 6)

// Packet: 0x0131
packetLen(0x0131, 86)

// Packet: 0x0132
packetLen(0x0132, 6)

// Packet: 0x0133
packetLen(0x0133, -1)

// Packet: 0x0134
packetLen(0x0134, -1)

// Packet: 0x0135
packetLen(0x0135, 7)

// Packet: 0x0136
packetLen(0x0136, -1)

// Packet: 0x0137
packetLen(0x0137, 6)

// Packet: 0x0138
packetLen(0x0138, 3)

// Packet: 0x0139
packetLen(0x0139, 16)

// Packet: 0x013a
packetLen(0x013A, 4)

// Packet: 0x013b
packetLen(0x013B, 4)

// Packet: 0x013c
packetLen(0x013C, 4)

// Packet: 0x013d
packetLen(0x013D, 6)

// Packet: 0x013e
packetLen(0x013E, 24)

// Packet: 0x013f
packetLen(0x013F, 26)

// Packet: 0x0140
packetLen(0x0140, 22)

// Packet: 0x0141
packetLen(0x0141, 14)

// Packet: 0x0142
packetLen(0x0142, 6)

// Packet: 0x0143
packetLen(0x0143, 10)

// Packet: 0x0144
packetLen(0x0144, 23)

// Packet: 0x0145
packetLen(0x0145, 19)

// Packet: 0x0146
packetLen(0x0146, 6)

// Packet: 0x0147
packetLen(0x0147, 39)

// Packet: 0x0148
packetLen(0x0148, 8)

// Packet: 0x0149
packetLen(0x0149, 9)

// Packet: 0x014a
packetLen(0x014A, 6)

// Packet: 0x014b
packetLen(0x014B, 27)

// Packet: 0x014c
packetLen(0x014C, -1)

// Packet: 0x014d
packetLen(0x014D, 2)

// Packet: 0x014e
packetLen(0x014E, 6)

// Packet: 0x014f
packetLen(0x014F, 6)

// Packet: 0x0150
packetLen(0x0150, 110)

// Packet: 0x0151
packetLen(0x0151, 6)

// Packet: 0x0152
packetLen(0x0152, -1)

// Packet: 0x0153
packetLen(0x0153, -1)

// Packet: 0x0154
packetLen(0x0154, -1)

// Packet: 0x0155
packetLen(0x0155, -1)

// Packet: 0x0156
packetLen(0x0156, -1)

// Packet: 0x0157
packetLen(0x0157, 6)

// Packet: 0x0158
packetLen(0x0158, -1)

// Packet: 0x0159
packetLen(0x0159, 54)

// Packet: 0x015a
packetLen(0x015A, 66)

// Packet: 0x015b
packetLen(0x015B, 54)

// Packet: 0x015c
packetLen(0x015C, 90)

// Packet: 0x015d
packetLen(0x015D, 42)

// Packet: 0x015e
packetLen(0x015E, 6)

// Packet: 0x015f
packetLen(0x015F, 42)

// Packet: 0x0160
packetLen(0x0160, -1)

// Packet: 0x0161
packetLen(0x0161, -1)

// Packet: 0x0162
packetLen(0x0162, -1)

// Packet: 0x0163
packetLen(0x0163, -1)

// Packet: 0x0164
packetLen(0x0164, -1)

// Packet: 0x0165
packetLen(0x0165, 30)

// Packet: 0x0166
packetLen(0x0166, -1)

// Packet: 0x0167
packetLen(0x0167, 3)

// Packet: 0x0168
packetLen(0x0168, 14)

// Packet: 0x0169
packetLen(0x0169, 3)

// Packet: 0x016a
packetLen(0x016A, 30)

// Packet: 0x016b
packetLen(0x016B, 10)

// Packet: 0x016c
packetLen(0x016C, 43)

// Packet: 0x016d
packetLen(0x016D, 14)

// Packet: 0x016e
packetLen(0x016E, 186)

// Packet: 0x016f
packetLen(0x016F, 182)

// Packet: 0x0170
packetLen(0x0170, 14)

// Packet: 0x0171
packetLen(0x0171, 30)

// Packet: 0x0172
packetLen(0x0172, 10)

// Packet: 0x0173
packetLen(0x0173, 3)

// Packet: 0x0174
packetLen(0x0174, -1)

// Packet: 0x0175
packetLen(0x0175, 6)

// Packet: 0x0176
packetLen(0x0176, 106)

// Packet: 0x0177
packetLen(0x0177, -1)

// Packet: 0x0178
packetLen(0x0178, 4)

// Packet: 0x0179
packetLen(0x0179, 5)

// Packet: 0x017a
packetLen(0x017A, 4)

// Packet: 0x017b
packetLen(0x017B, -1)

// Packet: 0x017c
packetLen(0x017C, 6)

// Packet: 0x017d
packetLen(0x017D, 7)

// Packet: 0x017e
packetLen(0x017E, -1)

// Packet: 0x017f
packetLen(0x017F, -1)

// Packet: 0x0180
packetLen(0x0180, 6)

// Packet: 0x0181
packetLen(0x0181, 3)

// Packet: 0x0182
packetLen(0x0182, 106)

// Packet: 0x0183
packetLen(0x0183, 10)

// Packet: 0x0184
packetLen(0x0184, 10)

// Packet: 0x0185
packetLen(0x0185, 34)

// Packet: 0x0187
packetLen(0x0187, 6)

// Packet: 0x0188
packetLen(0x0188, 8)

// Packet: 0x0189
packetLen(0x0189, 4)

// Packet: 0x018a
packetLen(0x018A, 4)

// Packet: 0x018b
packetLen(0x018B, 4)

// Packet: 0x018c
packetLen(0x018C, 29)

// Packet: 0x018d
packetLen(0x018D, -1)

// Packet: 0x018e
packetLen(0x018E, 10)

// Packet: 0x018f
packetLen(0x018F, 6)

// Packet: 0x0190
packetLen(0x0190, 90)

// Packet: 0x0191
packetLen(0x0191, 86)

// Packet: 0x0192
packetLen(0x0192, 24)

// Packet: 0x0193
packetLen(0x0193, 6)

// Packet: 0x0194
packetLen(0x0194, 30)

// Packet: 0x0195
packetLen(0x0195, 102)

// Packet: 0x0196
packetLen(0x0196, 9)

// Packet: 0x0197
packetLen(0x0197, 4)

// Packet: 0x0198
packetLen(0x0198, 8)

// Packet: 0x0199
packetLen(0x0199, 4)

// Packet: 0x019a
packetLen(0x019A, 14)

// Packet: 0x019b
packetLen(0x019B, 10)

// Packet: 0x019c
packetLen(0x019C, 4)

// Packet: 0x019d
packetLen(0x019D, 6)

// Packet: 0x019e
packetLen(0x019E, 2)

// Packet: 0x019f
packetLen(0x019F, 6)

// Packet: 0x01a0
packetLen(0x01A0, 3)

// Packet: 0x01a1
packetLen(0x01A1, 3)

// Packet: 0x01a2
packetLen(0x01A2, 35)

// Packet: 0x01a3
packetLen(0x01A3, 5)

// Packet: 0x01a4
packetLen(0x01A4, 11)

// Packet: 0x01a5
packetLen(0x01A5, 26)

// Packet: 0x01a6
packetLen(0x01A6, -1)

// Packet: 0x01a7
packetLen(0x01A7, 4)

// Packet: 0x01a8
packetLen(0x01A8, 4)

// Packet: 0x01a9
packetLen(0x01A9, 6)

// Packet: 0x01aa
packetLen(0x01AA, 10)

// Packet: 0x01ab
packetLen(0x01AB, 12)

// Packet: 0x01ac
packetLen(0x01AC, 6)

// Packet: 0x01ad
packetLen(0x01AD, -1)

// Packet: 0x01ae
packetLen(0x01AE, 4)

// Packet: 0x01af
packetLen(0x01AF, 4)

// Packet: 0x01b0
packetLen(0x01B0, 11)

// Packet: 0x01b1
packetLen(0x01B1, 7)

// Packet: 0x01b2
packetLen(0x01B2, -1)

// Packet: 0x01b3
packetLen(0x01B3, 67)

// Packet: 0x01b4
packetLen(0x01B4, 12)

// Packet: 0x01b5
packetLen(0x01B5, 18)

// Packet: 0x01b6
packetLen(0x01B6, 114)

// Packet: 0x01b7
packetLen(0x01B7, 6)

// Packet: 0x01b8
packetLen(0x01B8, 3)

// Packet: 0x01b9
packetLen(0x01B9, 6)

// Packet: 0x01ba
packetLen(0x01BA, 26)

// Packet: 0x01bb
packetLen(0x01BB, 26)

// Packet: 0x01bc
packetLen(0x01BC, 26)

// Packet: 0x01bd
packetLen(0x01BD, 26)

// Packet: 0x01be
packetLen(0x01BE, 2)

// Packet: 0x01bf
packetLen(0x01BF, 3)

// Packet: 0x01c0
packetLen(0x01C0, 2)

// Packet: 0x01c1
packetLen(0x01C1, 14)

// Packet: 0x01c2
packetLen(0x01C2, 10)

// Packet: 0x01c3
packetLen(0x01C3, -1)

// Packet: 0x01c4
packetLen(0x01C4, 22)

// Packet: 0x01c5
packetLen(0x01C5, 22)

// Packet: 0x01c6
packetLen(0x01C6, 4)

// Packet: 0x01c7
packetLen(0x01C7, 2)

// Packet: 0x01c8
packetLen(0x01C8, 13)

// Packet: 0x01c9
packetLen(0x01C9, 97)

// Packet: 0x01cb
packetLen(0x01CB, 9)

// Packet: 0x01cc
packetLen(0x01CC, 9)

// Packet: 0x01cd
packetLen(0x01CD, 30)

// Packet: 0x01ce
packetLen(0x01CE, 6)

// Packet: 0x01cf
packetLen(0x01CF, 28)

// Packet: 0x01d0
packetLen(0x01D0, 8)

// Packet: 0x01d1
packetLen(0x01D1, 14)

// Packet: 0x01d2
packetLen(0x01D2, 10)

// Packet: 0x01d3
packetLen(0x01D3, 35)

// Packet: 0x01d4
packetLen(0x01D4, 6)

// Packet: 0x01d5
packetLen(0x01D5, 8)

// Packet: 0x01d6
packetLen(0x01D6, 4)

// Packet: 0x01d7
packetLen(0x01D7, 11)

// Packet: 0x01d8
packetLen(0x01D8, 54)

// Packet: 0x01d9
packetLen(0x01D9, 53)

// Packet: 0x01da
packetLen(0x01DA, 60)

// Packet: 0x01db
packetLen(0x01DB, 2)

// Packet: 0x01dc
packetLen(0x01DC, -1)

// Packet: 0x01dd
packetLen(0x01DD, 47)

// Packet: 0x01de
packetLen(0x01DE, 33)

// Packet: 0x01df
packetLen(0x01DF, 6)

// Packet: 0x01e0
packetLen(0x01E0, 30)

// Packet: 0x01e1
packetLen(0x01E1, 8)

// Packet: 0x01e2
packetLen(0x01E2, 34)

// Packet: 0x01e3
packetLen(0x01E3, 14)

// Packet: 0x01e4
packetLen(0x01E4, 2)

// Packet: 0x01e5
packetLen(0x01E5, 6)

// Packet: 0x01e6
#if PACKETVER >= 20031110
packetLen(0x01E6, 26)
#elif PACKETVER >= 20031029
packetLen(0x01E6, 28)
#endif

// Packet: 0x01e7
#if PACKETVER >= 20031110
packetLen(0x01E7, 2)
#elif PACKETVER >= 20031029
packetLen(0x01E7, 81)
#endif

// Packet: 0x01e8
#if PACKETVER >= 20031117
packetLen(0x01E8, 28)
#elif PACKETVER >= 20031110
// removed
#elif PACKETVER >= 20031029
packetLen(0x01E8, 26)
#endif

// Packet: 0x01e9
#if PACKETVER >= 20031117
packetLen(0x01E9, 81)
#elif PACKETVER >= 20031110
// removed
#elif PACKETVER >= 20031103
packetLen(0x01E9, 2)
#endif

// Packet: 0x01ea
#if PACKETVER >= 20031117
packetLen(0x01EA, 6)
#endif

// Packet: 0x01eb
#if PACKETVER >= 20031124
packetLen(0x01EB, 10)
#endif

// Packet: 0x01ec
#if PACKETVER >= 20031124
packetLen(0x01EC, 26)
#endif

// Packet: 0x01ed
#if PACKETVER >= 20031124
packetLen(0x01ED, 2)
#endif

// Packet: 0x01ee
#if PACKETVER >= 20031208
packetLen(0x01EE, -1)
#endif

// Packet: 0x01ef
#if PACKETVER >= 20031218
packetLen(0x01EF, -1)
#endif

// Packet: 0x01f0
#if PACKETVER >= 20031218
packetLen(0x01F0, -1)
#endif

// Packet: 0x01f1
#if PACKETVER >= 20031223
packetLen(0x01F1, -1)
#endif

#endif /* COMMON_PACKETS2003_LEN_SAK_H */
