/**
 * This file is part of Hercules.
 * http://herc.ws - http://github.com/HerculesWS/Hercules
 *
 * Copyright (C) 2018-2022 Hercules Dev Team
 * Copyright (C) 2018-2021 Andrei Karas (4144)
 *
 * Hercules is free software: you can redistribute it and/or modify
 * it under the terms of the GNU General Public License as published by
 * the Free Software Foundation, either version 3 of the License, or
 * (at your option) any later version.
 *
 * This program is distributed in the hope that it will be useful,
 * but WITHOUT ANY WARRANTY; without even the implied warranty of
 * MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
 * GNU General Public License for more details.
 *
 * You should have received a copy of the GNU General Public License
 * along with this program.  If not, see <http://www.gnu.org/licenses/>.
 */

#ifndef COMMON_PACKETS2018_LEN_ZERO_H
#define COMMON_PACKETS2018_LEN_ZERO_H

/* This file is autogenerated, please do not commit manual changes */

// Packet: 0x0064
packetLen(0x0064, 55)

// Packet: 0x0065
packetLen(0x0065, 17)

// Packet: 0x0066
packetLen(0x0066, 3)

// Packet: 0x0067
packetLen(0x0067, 37)

// Packet: 0x0068
packetLen(0x0068, 46)

// Packet: 0x0069
packetLen(0x0069, -1)

// Packet: 0x006a
packetLen(0x006a, 23)

// Packet: 0x006b
packetLen(0x006b, -1)

// Packet: 0x006c
packetLen(0x006c, 3)

// Packet: 0x006d
packetLen(0x006d, 157)

// Packet: 0x006e
packetLen(0x006e, 3)

// Packet: 0x006f
packetLen(0x006f, 2)

// Packet: 0x0070
packetLen(0x0070, 3)

// Packet: 0x0071
packetLen(0x0071, 28)

// Packet: 0x0072
packetLen(0x0072, 22)

// Packet: 0x0073
packetLen(0x0073, 11)

// Packet: 0x0074
packetLen(0x0074, 3)

// Packet: 0x0075
packetLen(0x0075, -1)

// Packet: 0x0076
packetLen(0x0076, 9)

// Packet: 0x0077
packetLen(0x0077, 5)

// Packet: 0x0078
packetLen(0x0078, 55)

// Packet: 0x0079
packetLen(0x0079, 53)

// Packet: 0x007a
packetLen(0x007a, 58)

// Packet: 0x007b
packetLen(0x007b, 60)

// Packet: 0x007c
packetLen(0x007c, 44)

// Packet: 0x007d
packetLen(0x007d, 2)

// Packet: 0x007e
packetLen(0x007e, 105)

// Packet: 0x007f
packetLen(0x007f, 6)

// Packet: 0x0080
packetLen(0x0080, 7)

// Packet: 0x0081
packetLen(0x0081, 3)

// Packet: 0x0082
packetLen(0x0082, 2)

// Packet: 0x0083
packetLen(0x0083, 2)

// Packet: 0x0084
packetLen(0x0084, 2)

// Packet: 0x0085
packetLen(0x0085, 10)

// Packet: 0x0086
packetLen(0x0086, 16)

// Packet: 0x0087
packetLen(0x0087, 12)

// Packet: 0x0088
packetLen(0x0088, 10)

// Packet: 0x0089
packetLen(0x0089, 11)

// Packet: 0x008a
packetLen(0x008a, 29)

// Packet: 0x008b
packetLen(0x008b, 23)

// Packet: 0x008c
packetLen(0x008c, 14)

// Packet: 0x008d
packetLen(0x008d, -1)

// Packet: 0x008e
packetLen(0x008e, -1)

// Packet: 0x0090
packetLen(0x0090, 7)

// Packet: 0x0091
packetLen(0x0091, 22)

// Packet: 0x0092
packetLen(0x0092, 28)

// Packet: 0x0093
packetLen(0x0093, 2)

// Packet: 0x0094
packetLen(0x0094, 19)

// Packet: 0x0095
packetLen(0x0095, 30)

// Packet: 0x0096
packetLen(0x0096, -1)

// Packet: 0x0097
packetLen(0x0097, -1)

// Packet: 0x0098
packetLen(0x0098, 3)

// Packet: 0x0099
packetLen(0x0099, -1)

// Packet: 0x009a
packetLen(0x009a, -1)

// Packet: 0x009b
packetLen(0x009b, 34)

// Packet: 0x009c
packetLen(0x009c, 9)

// Packet: 0x009d
#if PACKETVER >= 20181114
packetLen(0x009d, 19)
#elif PACKETVER >= 20180103
packetLen(0x009d, 17)
#endif

// Packet: 0x009e
#if PACKETVER >= 20181114
packetLen(0x009e, 19)
#elif PACKETVER >= 20180103
packetLen(0x009e, 17)
#endif

// Packet: 0x009f
packetLen(0x009f, 20)

// Packet: 0x00a0
#if PACKETVER >= 20181114
packetLen(0x00a0, 33)
#elif PACKETVER >= 20180103
packetLen(0x00a0, 23)
#endif

// Packet: 0x00a1
packetLen(0x00a1, 6)

// Packet: 0x00a2
packetLen(0x00a2, 14)

// Packet: 0x00a3
packetLen(0x00a3, -1)

// Packet: 0x00a4
packetLen(0x00a4, -1)

// Packet: 0x00a5
packetLen(0x00a5, -1)

// Packet: 0x00a6
packetLen(0x00a6, -1)

// Packet: 0x00a7
packetLen(0x00a7, 9)

// Packet: 0x00a8
packetLen(0x00a8, 7)

// Packet: 0x00a9
packetLen(0x00a9, 6)

// Packet: 0x00aa
packetLen(0x00aa, 9)

// Packet: 0x00ab
packetLen(0x00ab, 4)

// Packet: 0x00ac
packetLen(0x00ac, 7)

// Packet: 0x00ae
packetLen(0x00ae, -1)

// Packet: 0x00af
packetLen(0x00af, 6)

// Packet: 0x00b0
packetLen(0x00b0, 8)

// Packet: 0x00b1
packetLen(0x00b1, 8)

// Packet: 0x00b2
packetLen(0x00b2, 3)

// Packet: 0x00b3
packetLen(0x00b3, 3)

// Packet: 0x00b4
packetLen(0x00b4, -1)

// Packet: 0x00b5
packetLen(0x00b5, 6)

// Packet: 0x00b6
packetLen(0x00b6, 6)

// Packet: 0x00b7
packetLen(0x00b7, -1)

// Packet: 0x00b8
packetLen(0x00b8, 7)

// Packet: 0x00b9
packetLen(0x00b9, 6)

// Packet: 0x00ba
packetLen(0x00ba, 2)

// Packet: 0x00bb
packetLen(0x00bb, 5)

// Packet: 0x00bc
packetLen(0x00bc, 6)

// Packet: 0x00bd
packetLen(0x00bd, 44)

// Packet: 0x00be
packetLen(0x00be, 5)

// Packet: 0x00bf
packetLen(0x00bf, 3)

// Packet: 0x00c0
packetLen(0x00c0, 7)

// Packet: 0x00c1
packetLen(0x00c1, 2)

// Packet: 0x00c2
packetLen(0x00c2, 6)

// Packet: 0x00c3
packetLen(0x00c3, 8)

// Packet: 0x00c4
packetLen(0x00c4, 6)

// Packet: 0x00c5
packetLen(0x00c5, 7)

// Packet: 0x00c6
packetLen(0x00c6, -1)

// Packet: 0x00c7
packetLen(0x00c7, -1)

// Packet: 0x00c8
packetLen(0x00c8, -1)

// Packet: 0x00c9
packetLen(0x00c9, -1)

// Packet: 0x00ca
packetLen(0x00ca, 3)

// Packet: 0x00cb
packetLen(0x00cb, 3)

// Packet: 0x00cc
packetLen(0x00cc, 6)

// Packet: 0x00cd
packetLen(0x00cd, 3)

// Packet: 0x00ce
packetLen(0x00ce, 2)

// Packet: 0x00cf
packetLen(0x00cf, 27)

// Packet: 0x00d0
packetLen(0x00d0, 3)

// Packet: 0x00d1
packetLen(0x00d1, 4)

// Packet: 0x00d2
packetLen(0x00d2, 4)

// Packet: 0x00d3
packetLen(0x00d3, 2)

// Packet: 0x00d4
packetLen(0x00d4, -1)

// Packet: 0x00d5
packetLen(0x00d5, -1)

// Packet: 0x00d6
packetLen(0x00d6, 3)

// Packet: 0x00d7
packetLen(0x00d7, -1)

// Packet: 0x00d8
packetLen(0x00d8, 6)

// Packet: 0x00d9
packetLen(0x00d9, 14)

// Packet: 0x00da
packetLen(0x00da, 3)

// Packet: 0x00db
packetLen(0x00db, -1)

// Packet: 0x00dc
packetLen(0x00dc, 28)

// Packet: 0x00dd
packetLen(0x00dd, 29)

// Packet: 0x00de
packetLen(0x00de, -1)

// Packet: 0x00df
packetLen(0x00df, -1)

// Packet: 0x00e0
packetLen(0x00e0, 30)

// Packet: 0x00e1
packetLen(0x00e1, 30)

// Packet: 0x00e2
packetLen(0x00e2, 26)

// Packet: 0x00e3
packetLen(0x00e3, 2)

// Packet: 0x00e4
packetLen(0x00e4, 6)

// Packet: 0x00e5
packetLen(0x00e5, 26)

// Packet: 0x00e6
packetLen(0x00e6, 3)

// Packet: 0x00e7
packetLen(0x00e7, 3)

// Packet: 0x00e8
packetLen(0x00e8, 8)

// Packet: 0x00e9
#if PACKETVER >= 20181114
packetLen(0x00e9, 29)
#elif PACKETVER >= 20180103
packetLen(0x00e9, 19)
#endif

// Packet: 0x00ea
packetLen(0x00ea, 5)

// Packet: 0x00eb
packetLen(0x00eb, 2)

// Packet: 0x00ec
packetLen(0x00ec, 3)

// Packet: 0x00ed
packetLen(0x00ed, 2)

// Packet: 0x00ee
packetLen(0x00ee, 2)

// Packet: 0x00ef
packetLen(0x00ef, 2)

// Packet: 0x00f0
packetLen(0x00f0, 3)

// Packet: 0x00f1
packetLen(0x00f1, 2)

// Packet: 0x00f2
packetLen(0x00f2, 6)

// Packet: 0x00f3
packetLen(0x00f3, -1)

// Packet: 0x00f4
#if PACKETVER >= 20181114
packetLen(0x00f4, 31)
#elif PACKETVER >= 20180103
packetLen(0x00f4, 21)
#endif

// Packet: 0x00f5
packetLen(0x00f5, 11)

// Packet: 0x00f6
packetLen(0x00f6, 8)

// Packet: 0x00f7
packetLen(0x00f7, 17)

// Packet: 0x00f8
packetLen(0x00f8, 2)

// Packet: 0x00f9
packetLen(0x00f9, 26)

// Packet: 0x00fa
packetLen(0x00fa, 3)

// Packet: 0x00fb
packetLen(0x00fb, -1)

// Packet: 0x00fc
packetLen(0x00fc, 6)

// Packet: 0x00fd
packetLen(0x00fd, 27)

// Packet: 0x00fe
packetLen(0x00fe, 30)

// Packet: 0x00ff
packetLen(0x00ff, 10)

// Packet: 0x0100
packetLen(0x0100, 2)

// Packet: 0x0101
packetLen(0x0101, 6)

// Packet: 0x0102
packetLen(0x0102, 6)

// Packet: 0x0103
packetLen(0x0103, 30)

// Packet: 0x0104
packetLen(0x0104, 79)

// Packet: 0x0105
packetLen(0x0105, 31)

// Packet: 0x0106
packetLen(0x0106, 10)

// Packet: 0x0107
packetLen(0x0107, 10)

// Packet: 0x0108
packetLen(0x0108, -1)

// Packet: 0x0109
packetLen(0x0109, -1)

// Packet: 0x010a
#if PACKETVER >= 20181114
packetLen(0x010a, 6)
#elif PACKETVER >= 20180103
packetLen(0x010a, 4)
#endif

// Packet: 0x010b
packetLen(0x010b, 6)

// Packet: 0x010c
packetLen(0x010c, 6)

// Packet: 0x010d
packetLen(0x010d, 2)

// Packet: 0x010e
packetLen(0x010e, 11)

// Packet: 0x010f
packetLen(0x010f, -1)

// Packet: 0x0110
#if PACKETVER >= 20181114
packetLen(0x0110, 14)
#elif PACKETVER >= 20180103
packetLen(0x0110, 10)
#endif

// Packet: 0x0111
packetLen(0x0111, 39)

// Packet: 0x0112
packetLen(0x0112, 4)

// Packet: 0x0113
packetLen(0x0113, 25)

// Packet: 0x0114
packetLen(0x0114, 31)

// Packet: 0x0115
packetLen(0x0115, 35)

// Packet: 0x0116
packetLen(0x0116, 17)

// Packet: 0x0117
packetLen(0x0117, 18)

// Packet: 0x0118
packetLen(0x0118, 2)

// Packet: 0x0119
packetLen(0x0119, 13)

// Packet: 0x011a
packetLen(0x011a, 15)

// Packet: 0x011b
packetLen(0x011b, 20)

// Packet: 0x011c
packetLen(0x011c, 68)

// Packet: 0x011d
packetLen(0x011d, 2)

// Packet: 0x011e
packetLen(0x011e, 3)

// Packet: 0x011f
packetLen(0x011f, 16)

// Packet: 0x0120
packetLen(0x0120, 6)

// Packet: 0x0121
packetLen(0x0121, 14)

// Packet: 0x0122
packetLen(0x0122, -1)

// Packet: 0x0123
packetLen(0x0123, -1)

// Packet: 0x0124
#if PACKETVER >= 20181114
packetLen(0x0124, 31)
#elif PACKETVER >= 20180103
packetLen(0x0124, 21)
#endif

// Packet: 0x0125
packetLen(0x0125, 8)

// Packet: 0x0126
packetLen(0x0126, 8)

// Packet: 0x0127
packetLen(0x0127, 8)

// Packet: 0x0128
packetLen(0x0128, 8)

// Packet: 0x0129
packetLen(0x0129, 8)

// Packet: 0x012a
packetLen(0x012a, 2)

// Packet: 0x012b
packetLen(0x012b, 2)

// Packet: 0x012c
packetLen(0x012c, 3)

// Packet: 0x012d
packetLen(0x012d, 4)

// Packet: 0x012e
packetLen(0x012e, 2)

// Packet: 0x012f
packetLen(0x012f, -1)

// Packet: 0x0130
packetLen(0x0130, 6)

// Packet: 0x0131
packetLen(0x0131, 86)

// Packet: 0x0132
packetLen(0x0132, 6)

// Packet: 0x0133
packetLen(0x0133, -1)

// Packet: 0x0134
packetLen(0x0134, -1)

// Packet: 0x0135
packetLen(0x0135, 7)

// Packet: 0x0136
packetLen(0x0136, -1)

// Packet: 0x0137
packetLen(0x0137, 6)

// Packet: 0x0138
packetLen(0x0138, 3)

// Packet: 0x0139
packetLen(0x0139, 16)

// Packet: 0x013a
packetLen(0x013a, 4)

// Packet: 0x013b
packetLen(0x013b, 4)

// Packet: 0x013c
packetLen(0x013c, 4)

// Packet: 0x013d
packetLen(0x013d, 6)

// Packet: 0x013e
packetLen(0x013e, 24)

// Packet: 0x013f
packetLen(0x013f, 26)

// Packet: 0x0140
packetLen(0x0140, 22)

// Packet: 0x0141
packetLen(0x0141, 14)

// Packet: 0x0142
packetLen(0x0142, 6)

// Packet: 0x0143
packetLen(0x0143, 10)

// Packet: 0x0144
packetLen(0x0144, 23)

// Packet: 0x0145
packetLen(0x0145, 19)

// Packet: 0x0146
packetLen(0x0146, 6)

// Packet: 0x0147
packetLen(0x0147, 39)

// Packet: 0x0148
packetLen(0x0148, 8)

// Packet: 0x0149
packetLen(0x0149, 9)

// Packet: 0x014a
packetLen(0x014a, 6)

// Packet: 0x014b
packetLen(0x014b, 27)

// Packet: 0x014c
packetLen(0x014c, -1)

// Packet: 0x014d
packetLen(0x014d, 2)

// Packet: 0x014e
packetLen(0x014e, 6)

// Packet: 0x014f
packetLen(0x014f, 6)

// Packet: 0x0150
packetLen(0x0150, 110)

// Packet: 0x0151
packetLen(0x0151, 6)

// Packet: 0x0152
packetLen(0x0152, -1)

// Packet: 0x0153
packetLen(0x0153, -1)

// Packet: 0x0154
packetLen(0x0154, -1)

// Packet: 0x0155
packetLen(0x0155, -1)

// Packet: 0x0156
packetLen(0x0156, -1)

// Packet: 0x0157
packetLen(0x0157, 6)

// Packet: 0x0159
packetLen(0x0159, 54)

// Packet: 0x015a
packetLen(0x015a, 66)

// Packet: 0x015b
packetLen(0x015b, 54)

// Packet: 0x015c
packetLen(0x015c, 90)

// Packet: 0x015d
packetLen(0x015d, 42)

// Packet: 0x015e
packetLen(0x015e, 6)

// Packet: 0x015f
packetLen(0x015f, 42)

// Packet: 0x0160
packetLen(0x0160, -1)

// Packet: 0x0161
packetLen(0x0161, -1)

// Packet: 0x0162
packetLen(0x0162, -1)

// Packet: 0x0163
packetLen(0x0163, -1)

// Packet: 0x0164
packetLen(0x0164, -1)

// Packet: 0x0165
packetLen(0x0165, 30)

// Packet: 0x0166
packetLen(0x0166, -1)

// Packet: 0x0167
packetLen(0x0167, 3)

// Packet: 0x0168
packetLen(0x0168, 14)

// Packet: 0x0169
packetLen(0x0169, 3)

// Packet: 0x016a
packetLen(0x016a, 30)

// Packet: 0x016b
packetLen(0x016b, 10)

// Packet: 0x016c
packetLen(0x016c, 43)

// Packet: 0x016d
packetLen(0x016d, 14)

// Packet: 0x016e
packetLen(0x016e, 186)

// Packet: 0x016f
packetLen(0x016f, 182)

// Packet: 0x0170
packetLen(0x0170, 14)

// Packet: 0x0171
packetLen(0x0171, 30)

// Packet: 0x0172
packetLen(0x0172, 10)

// Packet: 0x0173
packetLen(0x0173, 3)

// Packet: 0x0174
packetLen(0x0174, -1)

// Packet: 0x0175
packetLen(0x0175, 6)

// Packet: 0x0176
packetLen(0x0176, 106)

// Packet: 0x0177
packetLen(0x0177, -1)

// Packet: 0x0178
packetLen(0x0178, 4)

// Packet: 0x0179
packetLen(0x0179, 5)

// Packet: 0x017a
packetLen(0x017a, 4)

// Packet: 0x017b
packetLen(0x017b, -1)

// Packet: 0x017c
packetLen(0x017c, 6)

// Packet: 0x017d
packetLen(0x017d, 7)

// Packet: 0x017e
packetLen(0x017e, -1)

// Packet: 0x017f
packetLen(0x017f, -1)

// Packet: 0x0180
packetLen(0x0180, 6)

// Packet: 0x0181
packetLen(0x0181, 3)

// Packet: 0x0182
packetLen(0x0182, 106)

// Packet: 0x0183
packetLen(0x0183, 10)

// Packet: 0x0184
packetLen(0x0184, 10)

// Packet: 0x0185
packetLen(0x0185, 34)

// Packet: 0x0187
packetLen(0x0187, 6)

// Packet: 0x0188
packetLen(0x0188, 8)

// Packet: 0x0189
packetLen(0x0189, 4)

// Packet: 0x018a
packetLen(0x018a, 4)

// Packet: 0x018b
packetLen(0x018b, 4)

// Packet: 0x018c
packetLen(0x018c, 29)

// Packet: 0x018d
packetLen(0x018d, -1)

// Packet: 0x018e
#if PACKETVER >= 20181114
packetLen(0x018e, 18)
#elif PACKETVER >= 20180103
packetLen(0x018e, 10)
#endif

// Packet: 0x018f
#if PACKETVER >= 20181114
packetLen(0x018f, 8)
#elif PACKETVER >= 20180103
packetLen(0x018f, 6)
#endif

// Packet: 0x0190
packetLen(0x0190, 23)

// Packet: 0x0191
packetLen(0x0191, 86)

// Packet: 0x0192
packetLen(0x0192, 24)

// Packet: 0x0193
packetLen(0x0193, 2)

// Packet: 0x0194
packetLen(0x0194, 30)

// Packet: 0x0195
packetLen(0x0195, 102)

// Packet: 0x0196
packetLen(0x0196, 9)

// Packet: 0x0197
packetLen(0x0197, 4)

// Packet: 0x0198
packetLen(0x0198, 8)

// Packet: 0x0199
packetLen(0x0199, 4)

// Packet: 0x019a
packetLen(0x019a, 14)

// Packet: 0x019b
packetLen(0x019b, 10)

// Packet: 0x019c
packetLen(0x019c, -1)

// Packet: 0x019d
packetLen(0x019d, 6)

// Packet: 0x019e
packetLen(0x019e, 2)

// Packet: 0x019f
packetLen(0x019f, 6)

// Packet: 0x01a0
packetLen(0x01a0, 3)

// Packet: 0x01a1
packetLen(0x01a1, 3)

// Packet: 0x01a2
packetLen(0x01a2, 37)

// Packet: 0x01a3
#if PACKETVER >= 20181114
packetLen(0x01a3, 7)
#elif PACKETVER >= 20180103
packetLen(0x01a3, 5)
#endif

// Packet: 0x01a4
packetLen(0x01a4, 11)

// Packet: 0x01a5
packetLen(0x01a5, 26)

// Packet: 0x01a6
packetLen(0x01a6, -1)

// Packet: 0x01a7
packetLen(0x01a7, 4)

// Packet: 0x01a8
packetLen(0x01a8, 4)

// Packet: 0x01a9
packetLen(0x01a9, 6)

// Packet: 0x01aa
packetLen(0x01aa, 10)

// Packet: 0x01ab
packetLen(0x01ab, 12)

// Packet: 0x01ac
packetLen(0x01ac, 6)

// Packet: 0x01ad
packetLen(0x01ad, -1)

// Packet: 0x01ae
#if PACKETVER >= 20181114
packetLen(0x01ae, 6)
#elif PACKETVER >= 20180103
packetLen(0x01ae, 4)
#endif

// Packet: 0x01af
packetLen(0x01af, 4)

// Packet: 0x01b0
packetLen(0x01b0, 11)

// Packet: 0x01b1
packetLen(0x01b1, 7)

// Packet: 0x01b2
packetLen(0x01b2, -1)

// Packet: 0x01b3
packetLen(0x01b3, 67)

// Packet: 0x01b4
packetLen(0x01b4, 12)

// Packet: 0x01b5
packetLen(0x01b5, 18)

// Packet: 0x01b6
packetLen(0x01b6, 114)

// Packet: 0x01b7
packetLen(0x01b7, 6)

// Packet: 0x01b8
packetLen(0x01b8, 3)

// Packet: 0x01b9
packetLen(0x01b9, 6)

// Packet: 0x01ba
packetLen(0x01ba, 26)

// Packet: 0x01bb
packetLen(0x01bb, 26)

// Packet: 0x01bc
packetLen(0x01bc, 26)

// Packet: 0x01bd
packetLen(0x01bd, 26)

// Packet: 0x01be
packetLen(0x01be, 2)

// Packet: 0x01bf
packetLen(0x01bf, 3)

// Packet: 0x01c0
packetLen(0x01c0, 2)

// Packet: 0x01c1
packetLen(0x01c1, 14)

// Packet: 0x01c2
packetLen(0x01c2, 10)

// Packet: 0x01c3
packetLen(0x01c3, -1)

// Packet: 0x01c4
#if PACKETVER >= 20181114
packetLen(0x01c4, 32)
#elif PACKETVER >= 20180103
packetLen(0x01c4, 22)
#endif

// Packet: 0x01c5
#if PACKETVER >= 20181114
packetLen(0x01c5, 32)
#elif PACKETVER >= 20180103
packetLen(0x01c5, 22)
#endif

// Packet: 0x01c6
packetLen(0x01c6, 4)

// Packet: 0x01c7
packetLen(0x01c7, 2)

// Packet: 0x01c8
#if PACKETVER >= 20181114
packetLen(0x01c8, 15)
#elif PACKETVER >= 20180103
packetLen(0x01c8, 13)
#endif

// Packet: 0x01c9
packetLen(0x01c9, 97)

// Packet: 0x01ca
packetLen(0x01ca, 3)

// Packet: 0x01cb
packetLen(0x01cb, 9)

// Packet: 0x01cc
packetLen(0x01cc, 9)

// Packet: 0x01cd
packetLen(0x01cd, 30)

// Packet: 0x01ce
packetLen(0x01ce, 6)

// Packet: 0x01cf
packetLen(0x01cf, 28)

// Packet: 0x01d0
packetLen(0x01d0, 8)

// Packet: 0x01d1
packetLen(0x01d1, 14)

// Packet: 0x01d2
packetLen(0x01d2, 10)

// Packet: 0x01d3
packetLen(0x01d3, 35)

// Packet: 0x01d4
packetLen(0x01d4, 6)

// Packet: 0x01d5
packetLen(0x01d5, -1)

// Packet: 0x01d6
packetLen(0x01d6, 4)

// Packet: 0x01d7
#if PACKETVER >= 20181114
packetLen(0x01d7, 15)
#elif PACKETVER >= 20180103
packetLen(0x01d7, 11)
#endif

// Packet: 0x01d8
#if PACKETVER >= 20181114
packetLen(0x01d8, 58)
#elif PACKETVER >= 20180103
packetLen(0x01d8, 54)
#endif

// Packet: 0x01d9
#if PACKETVER >= 20181114
packetLen(0x01d9, 57)
#elif PACKETVER >= 20180103
packetLen(0x01d9, 53)
#endif

// Packet: 0x01da
#if PACKETVER >= 20181114
packetLen(0x01da, 64)
#elif PACKETVER >= 20180103
packetLen(0x01da, 60)
#endif

// Packet: 0x01db
packetLen(0x01db, 2)

// Packet: 0x01dc
packetLen(0x01dc, -1)

// Packet: 0x01dd
packetLen(0x01dd, 47)

// Packet: 0x01de
packetLen(0x01de, 33)

// Packet: 0x01df
packetLen(0x01df, 6)

// Packet: 0x01e0
packetLen(0x01e0, 30)

// Packet: 0x01e1
packetLen(0x01e1, 8)

// Packet: 0x01e2
packetLen(0x01e2, 34)

// Packet: 0x01e3
packetLen(0x01e3, 14)

// Packet: 0x01e4
packetLen(0x01e4, 2)

// Packet: 0x01e5
packetLen(0x01e5, 6)

// Packet: 0x01e6
packetLen(0x01e6, 26)

// Packet: 0x01e7
packetLen(0x01e7, 2)

// Packet: 0x01e8
packetLen(0x01e8, 28)

// Packet: 0x01e9
packetLen(0x01e9, 81)

// Packet: 0x01ea
packetLen(0x01ea, 6)

// Packet: 0x01eb
packetLen(0x01eb, 10)

// Packet: 0x01ec
packetLen(0x01ec, 26)

// Packet: 0x01ed
packetLen(0x01ed, 2)

// Packet: 0x01ee
packetLen(0x01ee, -1)

// Packet: 0x01ef
packetLen(0x01ef, -1)

// Packet: 0x01f0
packetLen(0x01f0, -1)

// Packet: 0x01f1
packetLen(0x01f1, -1)

// Packet: 0x01f2
packetLen(0x01f2, 20)

// Packet: 0x01f3
packetLen(0x01f3, 10)

// Packet: 0x01f4
packetLen(0x01f4, 32)

// Packet: 0x01f5
packetLen(0x01f5, 9)

// Packet: 0x01f6
packetLen(0x01f6, 34)

// Packet: 0x01f7
packetLen(0x01f7, 14)

// Packet: 0x01f8
packetLen(0x01f8, 2)

// Packet: 0x01f9
packetLen(0x01f9, 6)

// Packet: 0x01fa
packetLen(0x01fa, 48)

// Packet: 0x01fb
packetLen(0x01fb, 56)

// Packet: 0x01fc
packetLen(0x01fc, -1)

// Packet: 0x01fd
#if PACKETVER >= 20181114
packetLen(0x01fd, 25)
#elif PACKETVER >= 20180103
packetLen(0x01fd, 15)
#endif

// Packet: 0x01fe
packetLen(0x01fe, 5)

// Packet: 0x01ff
packetLen(0x01ff, 10)

// Packet: 0x0200
packetLen(0x0200, 26)

// Packet: 0x0201
packetLen(0x0201, -1)

// Packet: 0x0202
#if PACKETVER >= 20180523
packetLen(0x0202, 26)
#elif PACKETVER >= 20180511
packetLen(0x0202, 2)
#elif PACKETVER >= 20180315
packetLen(0x0202, 26)
#elif PACKETVER >= 20180314
packetLen(0x0202, 2)
#elif PACKETVER >= 20180228
packetLen(0x0202, 5)
#elif PACKETVER >= 20180213
packetLen(0x0202, 2)
#elif PACKETVER >= 20180131
packetLen(0x0202, 5)
#elif PACKETVER >= 20180103
packetLen(0x0202, 2)
#endif

// Packet: 0x0203
packetLen(0x0203, 10)

// Packet: 0x0204
packetLen(0x0204, 18)

// Packet: 0x0205
packetLen(0x0205, 26)

// Packet: 0x0206
#if PACKETVER >= 20180328
packetLen(0x0206, 35)
#elif PACKETVER >= 20180103
packetLen(0x0206, 11)
#endif

// Packet: 0x0207
packetLen(0x0207, 34)

// Packet: 0x0208
packetLen(0x0208, 14)

// Packet: 0x0209
packetLen(0x0209, 36)

// Packet: 0x020a
packetLen(0x020a, 10)

// Packet: 0x020d
packetLen(0x020d, -1)

// Packet: 0x020e
packetLen(0x020e, 32)

// Packet: 0x0212
packetLen(0x0212, 26)

// Packet: 0x0213
packetLen(0x0213, 26)

// Packet: 0x0214
packetLen(0x0214, 42)

// Packet: 0x0215
packetLen(0x0215, 6)

// Packet: 0x0216
packetLen(0x0216, 6)

// Packet: 0x0217
packetLen(0x0217, 2)

// Packet: 0x0218
packetLen(0x0218, 2)

// Packet: 0x0219
packetLen(0x0219, 282)

// Packet: 0x021a
packetLen(0x021a, 282)

// Packet: 0x021b
packetLen(0x021b, 10)

// Packet: 0x021c
packetLen(0x021c, 10)

// Packet: 0x021d
packetLen(0x021d, 6)

// Packet: 0x021e
packetLen(0x021e, 6)

// Packet: 0x021f
packetLen(0x021f, 66)

// Packet: 0x0220
packetLen(0x0220, 10)

// Packet: 0x0221
packetLen(0x0221, -1)

// Packet: 0x0222
packetLen(0x0222, 6)

// Packet: 0x0223
#if PACKETVER >= 20181114
packetLen(0x0223, 10)
#elif PACKETVER >= 20180103
packetLen(0x0223, 8)
#endif

// Packet: 0x0224
packetLen(0x0224, 10)

// Packet: 0x0225
packetLen(0x0225, 2)

// Packet: 0x0226
packetLen(0x0226, 282)

// Packet: 0x0227
packetLen(0x0227, 18)

// Packet: 0x0228
packetLen(0x0228, 18)

// Packet: 0x0229
packetLen(0x0229, 15)

// Packet: 0x022a
#if PACKETVER >= 20181114
packetLen(0x022a, 62)
#elif PACKETVER >= 20180103
packetLen(0x022a, 58)
#endif

// Packet: 0x022b
#if PACKETVER >= 20181114
packetLen(0x022b, 61)
#elif PACKETVER >= 20180103
packetLen(0x022b, 57)
#endif

// Packet: 0x022c
#if PACKETVER >= 20181114
packetLen(0x022c, 69)
#elif PACKETVER >= 20180103
packetLen(0x022c, 65)
#endif

// Packet: 0x022d
#if PACKETVER >= 20180523
packetLen(0x022d, 5)
#elif PACKETVER >= 20180511
packetLen(0x022d, 2)
#elif PACKETVER >= 20180315
packetLen(0x022d, 5)
#elif PACKETVER >= 20180314
packetLen(0x022d, 2)
#elif PACKETVER >= 20180228
packetLen(0x022d, 19)
#elif PACKETVER >= 20180221
packetLen(0x022d, 2)
#elif PACKETVER >= 20180213
packetLen(0x022d, 5)
#elif PACKETVER >= 20180131
packetLen(0x022d, 19)
#elif PACKETVER >= 20180103
packetLen(0x022d, 2)
#endif

// Packet: 0x022e
#if PACKETVER >= 20181114
packetLen(0x022e, 73)
#elif PACKETVER >= 20180103
packetLen(0x022e, 71)
#endif

// Packet: 0x022f
#if PACKETVER >= 20181114
packetLen(0x022f, 7)
#elif PACKETVER >= 20180103
packetLen(0x022f, 5)
#endif

// Packet: 0x0230
packetLen(0x0230, 12)

// Packet: 0x0231
packetLen(0x0231, 26)

// Packet: 0x0232
packetLen(0x0232, 9)

// Packet: 0x0233
packetLen(0x0233, 11)

// Packet: 0x0234
packetLen(0x0234, 6)

// Packet: 0x0235
packetLen(0x0235, -1)

// Packet: 0x0236
packetLen(0x0236, 10)

// Packet: 0x0237
packetLen(0x0237, 2)

// Packet: 0x0238
packetLen(0x0238, 282)

// Packet: 0x0239
packetLen(0x0239, 11)

// Packet: 0x023a
packetLen(0x023a, 4)

// Packet: 0x023b
#if PACKETVER >= 20180523
packetLen(0x023b, 36)
#elif PACKETVER >= 20180511
packetLen(0x023b, 2)
#elif PACKETVER >= 20180315
packetLen(0x023b, 36)
#elif PACKETVER >= 20180228
packetLen(0x023b, 26)
#elif PACKETVER >= 20180213
packetLen(0x023b, 2)
#elif PACKETVER >= 20180131
packetLen(0x023b, 26)
#elif PACKETVER >= 20180103
packetLen(0x023b, 2)
#endif

// Packet: 0x023c
packetLen(0x023c, 6)

// Packet: 0x023d
packetLen(0x023d, 6)

// Packet: 0x023e
packetLen(0x023e, 8)

// Packet: 0x023f
packetLen(0x023f, 2)

// Packet: 0x0240
packetLen(0x0240, -1)

// Packet: 0x0241
packetLen(0x0241, 6)

// Packet: 0x0242
packetLen(0x0242, -1)

// Packet: 0x0243
packetLen(0x0243, 6)

// Packet: 0x0244
packetLen(0x0244, 6)

// Packet: 0x0245
packetLen(0x0245, 3)

// Packet: 0x0246
packetLen(0x0246, 4)

// Packet: 0x0247
packetLen(0x0247, 8)

// Packet: 0x0248
packetLen(0x0248, -1)

// Packet: 0x0249
packetLen(0x0249, 3)

// Packet: 0x024a
packetLen(0x024a, 70)

// Packet: 0x024b
packetLen(0x024b, 4)

// Packet: 0x024c
packetLen(0x024c, 8)

// Packet: 0x024d
packetLen(0x024d, 12)

// Packet: 0x024e
packetLen(0x024e, 6)

// Packet: 0x024f
packetLen(0x024f, 10)

// Packet: 0x0250
packetLen(0x0250, 3)

// Packet: 0x0251
packetLen(0x0251, 34)

// Packet: 0x0252
packetLen(0x0252, -1)

// Packet: 0x0253
packetLen(0x0253, 3)

// Packet: 0x0254
packetLen(0x0254, 3)

// Packet: 0x0255
packetLen(0x0255, 5)

// Packet: 0x0256
packetLen(0x0256, 5)

// Packet: 0x0257
packetLen(0x0257, 8)

// Packet: 0x0258
packetLen(0x0258, 2)

// Packet: 0x0259
packetLen(0x0259, 3)

// Packet: 0x025a
packetLen(0x025a, -1)

// Packet: 0x025b
#if PACKETVER >= 20181114
packetLen(0x025b, 8)
#elif PACKETVER >= 20180103
packetLen(0x025b, 6)
#endif

// Packet: 0x025c
packetLen(0x025c, 4)

// Packet: 0x025d
packetLen(0x025d, 6)

// Packet: 0x025e
packetLen(0x025e, 4)

// Packet: 0x025f
packetLen(0x025f, 6)

// Packet: 0x0260
packetLen(0x0260, 6)

// Packet: 0x0261
packetLen(0x0261, 11)

// Packet: 0x0262
packetLen(0x0262, 11)

// Packet: 0x0263
packetLen(0x0263, 11)

// Packet: 0x0264
packetLen(0x0264, 20)

// Packet: 0x0265
packetLen(0x0265, 20)

// Packet: 0x0266
packetLen(0x0266, 30)

// Packet: 0x0267
packetLen(0x0267, 4)

// Packet: 0x0268
packetLen(0x0268, 4)

// Packet: 0x0269
packetLen(0x0269, 4)

// Packet: 0x026a
packetLen(0x026a, 4)

// Packet: 0x026b
packetLen(0x026b, 4)

// Packet: 0x026c
packetLen(0x026c, 4)

// Packet: 0x026d
packetLen(0x026d, 4)

// Packet: 0x026f
packetLen(0x026f, 2)

// Packet: 0x0270
packetLen(0x0270, 2)

// Packet: 0x0271
packetLen(0x0271, 40)

// Packet: 0x0272
packetLen(0x0272, 44)

// Packet: 0x0273
packetLen(0x0273, 30)

// Packet: 0x0274
packetLen(0x0274, 8)

// Packet: 0x0275
packetLen(0x0275, 37)

// Packet: 0x0276
packetLen(0x0276, -1)

// Packet: 0x0277
packetLen(0x0277, 84)

// Packet: 0x0278
packetLen(0x0278, 2)

// Packet: 0x0279
packetLen(0x0279, 2)

// Packet: 0x027a
packetLen(0x027a, -1)

// Packet: 0x027b
packetLen(0x027b, 14)

// Packet: 0x027c
packetLen(0x027c, 60)

// Packet: 0x027d
packetLen(0x027d, 62)

// Packet: 0x027e
packetLen(0x027e, -1)

// Packet: 0x027f
packetLen(0x027f, 8)

// Packet: 0x0280
packetLen(0x0280, 12)

// Packet: 0x0281
#if PACKETVER >= 20180523
packetLen(0x0281, 4)
#elif PACKETVER >= 20180511
packetLen(0x0281, 2)
#elif PACKETVER >= 20180315
packetLen(0x0281, 4)
#elif PACKETVER >= 20180314
packetLen(0x0281, 2)
#elif PACKETVER >= 20180228
packetLen(0x0281, -1)
#elif PACKETVER >= 20180213
packetLen(0x0281, 2)
#elif PACKETVER >= 20180131
packetLen(0x0281, -1)
#elif PACKETVER >= 20180103
packetLen(0x0281, 2)
#endif

// Packet: 0x0282
packetLen(0x0282, 284)

// Packet: 0x0283
packetLen(0x0283, 6)

// Packet: 0x0284
packetLen(0x0284, 14)

// Packet: 0x0285
packetLen(0x0285, 6)

// Packet: 0x0286
packetLen(0x0286, 4)

// Packet: 0x0287
packetLen(0x0287, -1)

// Packet: 0x0288
packetLen(0x0288, -1)

// Packet: 0x0289
packetLen(0x0289, 12)

// Packet: 0x028a
packetLen(0x028a, 18)

// Packet: 0x028b
packetLen(0x028b, -1)

// Packet: 0x028c
packetLen(0x028c, 46)

// Packet: 0x028d
packetLen(0x028d, 34)

// Packet: 0x028e
packetLen(0x028e, 4)

// Packet: 0x028f
packetLen(0x028f, 6)

// Packet: 0x0290
packetLen(0x0290, 4)

// Packet: 0x0291
packetLen(0x0291, 4)

// Packet: 0x0292
packetLen(0x0292, 2)

// Packet: 0x0293
packetLen(0x0293, 70)

// Packet: 0x0294
packetLen(0x0294, 10)

// Packet: 0x0295
packetLen(0x0295, -1)

// Packet: 0x0296
packetLen(0x0296, -1)

// Packet: 0x0297
packetLen(0x0297, -1)

// Packet: 0x0298
#if PACKETVER >= 20181114
packetLen(0x0298, 10)
#elif PACKETVER >= 20180103
packetLen(0x0298, 8)
#endif

// Packet: 0x0299
#if PACKETVER >= 20181114
packetLen(0x0299, 8)
#elif PACKETVER >= 20180103
packetLen(0x0299, 6)
#endif

// Packet: 0x029a
#if PACKETVER >= 20181114
packetLen(0x029a, 37)
#elif PACKETVER >= 20180103
packetLen(0x029a, 27)
#endif

// Packet: 0x029b
packetLen(0x029b, 80)

// Packet: 0x029c
packetLen(0x029c, 66)

// Packet: 0x029d
packetLen(0x029d, -1)

// Packet: 0x029e
packetLen(0x029e, 11)

// Packet: 0x029f
packetLen(0x029f, 3)

// Packet: 0x02a2
packetLen(0x02a2, 8)

// Packet: 0x02a5
packetLen(0x02a5, 8)

// Packet: 0x02a6
packetLen(0x02a6, -1)

// Packet: 0x02a7
packetLen(0x02a7, -1)

// Packet: 0x02aa
packetLen(0x02aa, 4)

// Packet: 0x02ab
packetLen(0x02ab, 36)

// Packet: 0x02ac
packetLen(0x02ac, 6)

// Packet: 0x02ad
packetLen(0x02ad, 8)

// Packet: 0x02b0
packetLen(0x02b0, 85)

// Packet: 0x02b1
packetLen(0x02b1, -1)

// Packet: 0x02b2
packetLen(0x02b2, -1)

// Packet: 0x02b3
packetLen(0x02b3, 107)

// Packet: 0x02b4
packetLen(0x02b4, 6)

// Packet: 0x02b5
packetLen(0x02b5, -1)

// Packet: 0x02b6
packetLen(0x02b6, 7)

// Packet: 0x02b7
packetLen(0x02b7, 7)

// Packet: 0x02b8
#if PACKETVER >= 20181114
packetLen(0x02b8, 32)
#elif PACKETVER >= 20180103
packetLen(0x02b8, 22)
#endif

// Packet: 0x02b9
packetLen(0x02b9, 191)

// Packet: 0x02ba
packetLen(0x02ba, 11)

// Packet: 0x02bb
packetLen(0x02bb, 8)

// Packet: 0x02bc
packetLen(0x02bc, 6)

// Packet: 0x02c1
packetLen(0x02c1, -1)

// Packet: 0x02c2
packetLen(0x02c2, -1)

// Packet: 0x02c4
#if PACKETVER >= 20180523
packetLen(0x02c4, 26)
#elif PACKETVER >= 20180511
packetLen(0x02c4, 2)
#elif PACKETVER >= 20180315
packetLen(0x02c4, 26)
#elif PACKETVER >= 20180228
packetLen(0x02c4, 2)
#elif PACKETVER >= 20180221
packetLen(0x02c4, 6)
#elif PACKETVER >= 20180213
packetLen(0x02c4, 8)
#elif PACKETVER >= 20180103
packetLen(0x02c4, 2)
#endif

// Packet: 0x02c5
packetLen(0x02c5, 30)

// Packet: 0x02c6
packetLen(0x02c6, 30)

// Packet: 0x02c7
packetLen(0x02c7, 7)

// Packet: 0x02c8
packetLen(0x02c8, 3)

// Packet: 0x02c9
packetLen(0x02c9, 3)

// Packet: 0x02ca
packetLen(0x02ca, 3)

// Packet: 0x02cb
packetLen(0x02cb, 65)

// Packet: 0x02cc
packetLen(0x02cc, 4)

// Packet: 0x02cd
packetLen(0x02cd, 71)

// Packet: 0x02ce
packetLen(0x02ce, 10)

// Packet: 0x02cf
packetLen(0x02cf, 6)

// Packet: 0x02d0
packetLen(0x02d0, -1)

// Packet: 0x02d1
packetLen(0x02d1, -1)

// Packet: 0x02d2
packetLen(0x02d2, -1)

// Packet: 0x02d3
packetLen(0x02d3, 4)

// Packet: 0x02d4
#if PACKETVER >= 20181114
packetLen(0x02d4, 39)
#elif PACKETVER >= 20180103
packetLen(0x02d4, 29)
#endif

// Packet: 0x02d5
packetLen(0x02d5, 2)

// Packet: 0x02d6
packetLen(0x02d6, 6)

// Packet: 0x02d7
packetLen(0x02d7, -1)

// Packet: 0x02d8
packetLen(0x02d8, 10)

// Packet: 0x02d9
packetLen(0x02d9, 10)

// Packet: 0x02da
packetLen(0x02da, 3)

// Packet: 0x02db
packetLen(0x02db, -1)

// Packet: 0x02dc
packetLen(0x02dc, -1)

// Packet: 0x02dd
packetLen(0x02dd, 32)

// Packet: 0x02de
packetLen(0x02de, 6)

// Packet: 0x02df
packetLen(0x02df, 36)

// Packet: 0x02e0
packetLen(0x02e0, 34)

// Packet: 0x02e1
packetLen(0x02e1, 33)

// Packet: 0x02e2
packetLen(0x02e2, 20)

// Packet: 0x02e3
packetLen(0x02e3, 22)

// Packet: 0x02e4
packetLen(0x02e4, 11)

// Packet: 0x02e5
packetLen(0x02e5, 9)

// Packet: 0x02e6
packetLen(0x02e6, 6)

// Packet: 0x02e7
packetLen(0x02e7, -1)

// Packet: 0x02e8
packetLen(0x02e8, -1)

// Packet: 0x02e9
packetLen(0x02e9, -1)

// Packet: 0x02ea
packetLen(0x02ea, -1)

// Packet: 0x02eb
packetLen(0x02eb, 13)

// Packet: 0x02ec
#if PACKETVER >= 20181114
packetLen(0x02ec, 71)
#elif PACKETVER >= 20180103
packetLen(0x02ec, 67)
#endif

// Packet: 0x02ed
#if PACKETVER >= 20181114
packetLen(0x02ed, 63)
#elif PACKETVER >= 20180103
packetLen(0x02ed, 59)
#endif

// Packet: 0x02ee
#if PACKETVER >= 20181114
packetLen(0x02ee, 64)
#elif PACKETVER >= 20180103
packetLen(0x02ee, 60)
#endif

// Packet: 0x02ef
packetLen(0x02ef, 8)

// Packet: 0x02f0
packetLen(0x02f0, 10)

// Packet: 0x02f1
packetLen(0x02f1, 2)

// Packet: 0x02f2
packetLen(0x02f2, 2)

// Packet: 0x02f3
packetLen(0x02f3, -1)

// Packet: 0x02f4
packetLen(0x02f4, 3)

// Packet: 0x02f5
packetLen(0x02f5, 7)

// Packet: 0x02f6
packetLen(0x02f6, 7)

// Packet: 0x035c
packetLen(0x035c, 2)

// Packet: 0x035d
packetLen(0x035d, -1)

// Packet: 0x035e
packetLen(0x035e, 2)

// Packet: 0x035f
#if PACKETVER >= 20180523
packetLen(0x035f, 5)
#elif PACKETVER >= 20180511
packetLen(0x035f, 2)
#elif PACKETVER >= 20180315
packetLen(0x035f, 5)
#elif PACKETVER >= 20180314
packetLen(0x035f, 2)
#elif PACKETVER >= 20180228
packetLen(0x035f, 6)
#elif PACKETVER >= 20180221
packetLen(0x035f, 2)
#elif PACKETVER >= 20180131
packetLen(0x035f, 6)
#elif PACKETVER >= 20180117
packetLen(0x035f, 2)
#elif PACKETVER >= 20180103
packetLen(0x035f, 5)
#endif

// Packet: 0x0360
#if PACKETVER >= 20180523
packetLen(0x0360, 6)
#elif PACKETVER >= 20180511
packetLen(0x0360, 2)
#elif PACKETVER >= 20180315
packetLen(0x0360, 6)
#elif PACKETVER >= 20180314
packetLen(0x0360, 2)
#elif PACKETVER >= 20180228
packetLen(0x0360, 6)
#elif PACKETVER >= 20180213
packetLen(0x0360, 2)
#elif PACKETVER >= 20180131
packetLen(0x0360, 6)
#elif PACKETVER >= 20180117
packetLen(0x0360, 2)
#elif PACKETVER >= 20180103
packetLen(0x0360, 18)
#endif

// Packet: 0x0361
#if PACKETVER >= 20180523
packetLen(0x0361, 5)
#elif PACKETVER >= 20180511
packetLen(0x0361, 2)
#elif PACKETVER >= 20180315
packetLen(0x0361, 5)
#elif PACKETVER >= 20180314
packetLen(0x0361, 2)
#elif PACKETVER >= 20180228
packetLen(0x0361, 5)
#elif PACKETVER >= 20180221
packetLen(0x0361, 2)
#elif PACKETVER >= 20180213
packetLen(0x0361, 90)
#elif PACKETVER >= 20180131
packetLen(0x0361, 5)
#elif PACKETVER >= 20180117
packetLen(0x0361, 26)
#elif PACKETVER >= 20180103
packetLen(0x0361, 2)
#endif

// Packet: 0x0362
#if PACKETVER >= 20180523
packetLen(0x0362, 6)
#elif PACKETVER >= 20180511
packetLen(0x0362, 2)
#elif PACKETVER >= 20180315
packetLen(0x0362, 6)
#elif PACKETVER >= 20180314
packetLen(0x0362, 2)
#elif PACKETVER >= 20180221
packetLen(0x0362, 6)
#elif PACKETVER >= 20180213
packetLen(0x0362, 2)
#elif PACKETVER >= 20180131
packetLen(0x0362, 6)
#elif PACKETVER >= 20180103
packetLen(0x0362, 2)
#endif

// Packet: 0x0363
#if PACKETVER >= 20180523
packetLen(0x0363, 6)
#elif PACKETVER >= 20180511
packetLen(0x0363, 2)
#elif PACKETVER >= 20180315
packetLen(0x0363, 6)
#elif PACKETVER >= 20180314
packetLen(0x0363, 2)
#elif PACKETVER >= 20180228
packetLen(0x0363, 8)
#elif PACKETVER >= 20180213
packetLen(0x0363, 2)
#elif PACKETVER >= 20180131
packetLen(0x0363, 8)
#elif PACKETVER >= 20180103
packetLen(0x0363, 2)
#endif

// Packet: 0x0364
#if PACKETVER >= 20180523
packetLen(0x0364, 8)
#elif PACKETVER >= 20180511
packetLen(0x0364, 2)
#elif PACKETVER >= 20180315
packetLen(0x0364, 8)
#elif PACKETVER >= 20180314
packetLen(0x0364, 2)
#elif PACKETVER >= 20180228
packetLen(0x0364, 8)
#elif PACKETVER >= 20180221
packetLen(0x0364, 5)
#elif PACKETVER >= 20180213
packetLen(0x0364, 2)
#elif PACKETVER >= 20180131
packetLen(0x0364, 8)
#elif PACKETVER >= 20180117
packetLen(0x0364, 6)
#elif PACKETVER >= 20180103
packetLen(0x0364, 2)
#endif

// Packet: 0x0365
#if PACKETVER >= 20180523
packetLen(0x0365, 8)
#elif PACKETVER >= 20180511
packetLen(0x0365, 2)
#elif PACKETVER >= 20180315
packetLen(0x0365, 8)
#elif PACKETVER >= 20180314
packetLen(0x0365, 2)
#elif PACKETVER >= 20180228
packetLen(0x0365, 18)
#elif PACKETVER >= 20180213
packetLen(0x0365, 2)
#elif PACKETVER >= 20180131
packetLen(0x0365, 18)
#elif PACKETVER >= 20180103
packetLen(0x0365, 2)
#endif

// Packet: 0x0366
#if PACKETVER >= 20180523
packetLen(0x0366, 10)
#elif PACKETVER >= 20180511
packetLen(0x0366, 2)
#elif PACKETVER >= 20180315
packetLen(0x0366, 10)
#elif PACKETVER >= 20180314
packetLen(0x0366, 2)
#elif PACKETVER >= 20180228
packetLen(0x0366, 90)
#elif PACKETVER >= 20180213
packetLen(0x0366, 2)
#elif PACKETVER >= 20180207
packetLen(0x0366, 90)
#elif PACKETVER >= 20180117
packetLen(0x0366, 2)
#elif PACKETVER >= 20180103
packetLen(0x0366, -1)
#endif

// Packet: 0x0367
#if PACKETVER >= 20180523
packetLen(0x0367, 90)
#elif PACKETVER >= 20180511
packetLen(0x0367, 2)
#elif PACKETVER >= 20180315
packetLen(0x0367, 90)
#elif PACKETVER >= 20180207
packetLen(0x0367, 2)
#elif PACKETVER >= 20180131
packetLen(0x0367, 36)
#elif PACKETVER >= 20180103
packetLen(0x0367, 2)
#endif

// Packet: 0x0368
#if PACKETVER >= 20180523
packetLen(0x0368, 6)
#elif PACKETVER >= 20180511
packetLen(0x0368, 2)
#elif PACKETVER >= 20180315
packetLen(0x0368, 6)
#elif PACKETVER >= 20180314
packetLen(0x0368, 2)
#elif PACKETVER >= 20180228
packetLen(0x0368, 6)
#elif PACKETVER >= 20180213
packetLen(0x0368, 2)
#elif PACKETVER >= 20180131
packetLen(0x0368, 6)
#elif PACKETVER >= 20180103
packetLen(0x0368, 2)
#endif

// Packet: 0x0369
#if PACKETVER >= 20180523
packetLen(0x0369, 6)
#elif PACKETVER >= 20180511
packetLen(0x0369, 2)
#elif PACKETVER >= 20180315
packetLen(0x0369, 6)
#elif PACKETVER >= 20180314
packetLen(0x0369, 2)
#elif PACKETVER >= 20180228
packetLen(0x0369, 7)
#elif PACKETVER >= 20180213
packetLen(0x0369, 2)
#elif PACKETVER >= 20180131
packetLen(0x0369, 7)
#elif PACKETVER >= 20180103
packetLen(0x0369, 2)
#endif

// Packet: 0x03dd
packetLen(0x03dd, 18)

// Packet: 0x03de
packetLen(0x03de, 18)

// Packet: 0x0436
#if PACKETVER >= 20180523
packetLen(0x0436, 19)
#elif PACKETVER >= 20180511
packetLen(0x0436, 2)
#elif PACKETVER >= 20180315
packetLen(0x0436, 19)
#elif PACKETVER >= 20180314
packetLen(0x0436, 2)
#elif PACKETVER >= 20180228
packetLen(0x0436, 4)
#elif PACKETVER >= 20180213
packetLen(0x0436, 2)
#elif PACKETVER >= 20180131
packetLen(0x0436, 4)
#elif PACKETVER >= 20180103
packetLen(0x0436, 2)
#endif

// Packet: 0x0437
#if PACKETVER >= 20180523
packetLen(0x0437, 7)
#elif PACKETVER >= 20180511
packetLen(0x0437, 2)
#elif PACKETVER >= 20180315
packetLen(0x0437, 7)
#elif PACKETVER >= 20180314
packetLen(0x0437, 2)
#elif PACKETVER >= 20180228
packetLen(0x0437, 5)
#elif PACKETVER >= 20180213
packetLen(0x0437, 2)
#elif PACKETVER >= 20180131
packetLen(0x0437, 5)
#elif PACKETVER >= 20180103
packetLen(0x0437, 2)
#endif

// Packet: 0x0438
#if PACKETVER >= 20180523
packetLen(0x0438, 10)
#elif PACKETVER >= 20180511
packetLen(0x0438, 2)
#elif PACKETVER >= 20180315
packetLen(0x0438, 10)
#elif PACKETVER >= 20180314
packetLen(0x0438, 2)
#elif PACKETVER >= 20180228
packetLen(0x0438, 10)
#elif PACKETVER >= 20180221
packetLen(0x0438, -1)
#elif PACKETVER >= 20180213
packetLen(0x0438, 2)
#elif PACKETVER >= 20180131
packetLen(0x0438, 10)
#elif PACKETVER >= 20180117
packetLen(0x0438, 8)
#elif PACKETVER >= 20180103
packetLen(0x0438, 2)
#endif

// Packet: 0x0439
packetLen(0x0439, 8)

// Packet: 0x043d
packetLen(0x043d, 8)

// Packet: 0x043e
packetLen(0x043e, -1)

// Packet: 0x043f
packetLen(0x043f, 25)

// Packet: 0x0440
packetLen(0x0440, 10)

// Packet: 0x0441
packetLen(0x0441, 4)

// Packet: 0x0442
packetLen(0x0442, -1)

// Packet: 0x0443
packetLen(0x0443, 8)

// Packet: 0x0444
packetLen(0x0444, -1)

// Packet: 0x0445
#if PACKETVER >= 20181114
packetLen(0x0445, 12)
#elif PACKETVER >= 20180103
packetLen(0x0445, 10)
#endif

// Packet: 0x0446
packetLen(0x0446, 14)

// Packet: 0x0447
packetLen(0x0447, 2)

// Packet: 0x0448
packetLen(0x0448, -1)

// Packet: 0x0449
packetLen(0x0449, 4)

// Packet: 0x044a
packetLen(0x044a, 6)

// Packet: 0x044b
packetLen(0x044b, 2)

// Packet: 0x07d7
packetLen(0x07d7, 8)

// Packet: 0x07d8
packetLen(0x07d8, 8)

// Packet: 0x07d9
packetLen(0x07d9, 268)

// Packet: 0x07da
packetLen(0x07da, 6)

// Packet: 0x07db
packetLen(0x07db, 8)

// Packet: 0x07dc
packetLen(0x07dc, 6)

// Packet: 0x07dd
packetLen(0x07dd, 54)

// Packet: 0x07de
packetLen(0x07de, 30)

// Packet: 0x07df
packetLen(0x07df, 54)

// Packet: 0x07e0
packetLen(0x07e0, 58)

// Packet: 0x07e1
packetLen(0x07e1, 15)

// Packet: 0x07e2
packetLen(0x07e2, 8)

// Packet: 0x07e3
packetLen(0x07e3, 6)

// Packet: 0x07e4
#if PACKETVER >= 20180523
packetLen(0x07e4, -1)
#elif PACKETVER >= 20180511
packetLen(0x07e4, 2)
#elif PACKETVER >= 20180315
packetLen(0x07e4, -1)
#elif PACKETVER >= 20180314
packetLen(0x07e4, 2)
#elif PACKETVER >= 20180228
packetLen(0x07e4, 6)
#elif PACKETVER >= 20180213
packetLen(0x07e4, 2)
#elif PACKETVER >= 20180131
packetLen(0x07e4, 6)
#elif PACKETVER >= 20180117
packetLen(0x07e4, 36)
#elif PACKETVER >= 20180103
packetLen(0x07e4, 5)
#endif

// Packet: 0x07e5
packetLen(0x07e5, 4)

// Packet: 0x07e6
packetLen(0x07e6, 8)

// Packet: 0x07e7
packetLen(0x07e7, 32)

// Packet: 0x07e8
packetLen(0x07e8, -1)

// Packet: 0x07e9
packetLen(0x07e9, 5)

// Packet: 0x07ea
packetLen(0x07ea, 2)

// Packet: 0x07eb
packetLen(0x07eb, -1)

// Packet: 0x07ec
#if PACKETVER >= 20180523
packetLen(0x07ec, 8)
#elif PACKETVER >= 20180511
packetLen(0x07ec, 2)
#elif PACKETVER >= 20180315
packetLen(0x07ec, 8)
#elif PACKETVER >= 20180314
packetLen(0x07ec, 19)
#elif PACKETVER >= 20180228
packetLen(0x07ec, 8)
#elif PACKETVER >= 20180213
packetLen(0x07ec, 2)
#elif PACKETVER >= 20180131
packetLen(0x07ec, 8)
#elif PACKETVER >= 20180103
packetLen(0x07ec, 2)
#endif

// Packet: 0x07ed
packetLen(0x07ed, 10)

// Packet: 0x07ee
packetLen(0x07ee, 6)

// Packet: 0x07ef
packetLen(0x07ef, 8)

// Packet: 0x07f0
packetLen(0x07f0, 6)

// Packet: 0x07f1
packetLen(0x07f1, 18)

// Packet: 0x07f2
packetLen(0x07f2, 8)

// Packet: 0x07f3
packetLen(0x07f3, 6)

// Packet: 0x07f4
packetLen(0x07f4, 3)

// Packet: 0x07f5
packetLen(0x07f5, 6)

// Packet: 0x07f6
packetLen(0x07f6, 14)

// Packet: 0x07f7
packetLen(0x07f7, -1)

// Packet: 0x07f8
packetLen(0x07f8, -1)

// Packet: 0x07f9
packetLen(0x07f9, -1)

// Packet: 0x07fa
packetLen(0x07fa, 8)

// Packet: 0x07fb
packetLen(0x07fb, 25)

// Packet: 0x07fc
packetLen(0x07fc, 10)

// Packet: 0x07fd
packetLen(0x07fd, -1)

// Packet: 0x07fe
packetLen(0x07fe, 26)

// Packet: 0x0800
packetLen(0x0800, -1)

// Packet: 0x0801
packetLen(0x0801, -1)

// Packet: 0x0802
#if PACKETVER >= 20180523
packetLen(0x0802, 18)
#elif PACKETVER >= 20180511
packetLen(0x0802, 2)
#elif PACKETVER >= 20180315
packetLen(0x0802, 18)
#elif PACKETVER >= 20180314
packetLen(0x0802, 2)
#elif PACKETVER >= 20180228
packetLen(0x0802, 26)
#elif PACKETVER >= 20180221
packetLen(0x0802, 2)
#elif PACKETVER >= 20180213
packetLen(0x0802, 6)
#elif PACKETVER >= 20180131
packetLen(0x0802, 26)
#elif PACKETVER >= 20180103
packetLen(0x0802, 2)
#endif

// Packet: 0x0803
packetLen(0x0803, 4)

// Packet: 0x0804
packetLen(0x0804, 14)

// Packet: 0x0805
packetLen(0x0805, -1)

// Packet: 0x0806
packetLen(0x0806, 2)

// Packet: 0x0807
packetLen(0x0807, 4)

// Packet: 0x0808
packetLen(0x0808, 14)

// Packet: 0x0809
packetLen(0x0809, 50)

// Packet: 0x080a
packetLen(0x080a, 18)

// Packet: 0x080b
packetLen(0x080b, 6)

// Packet: 0x080c
packetLen(0x080c, 2)

// Packet: 0x080d
packetLen(0x080d, 3)

// Packet: 0x080e
packetLen(0x080e, 14)

// Packet: 0x080f
#if PACKETVER >= 20181114
packetLen(0x080f, 30)
#elif PACKETVER >= 20180103
packetLen(0x080f, 20)
#endif

// Packet: 0x0810
packetLen(0x0810, 3)

// Packet: 0x0811
#if PACKETVER >= 20180523
packetLen(0x0811, -1)
#elif PACKETVER >= 20180511
packetLen(0x0811, 2)
#elif PACKETVER >= 20180315
packetLen(0x0811, -1)
#elif PACKETVER >= 20180314
packetLen(0x0811, 2)
#elif PACKETVER >= 20180228
packetLen(0x0811, -1)
#elif PACKETVER >= 20180213
packetLen(0x0811, 2)
#elif PACKETVER >= 20180131
packetLen(0x0811, -1)
#elif PACKETVER >= 20180103
packetLen(0x0811, 2)
#endif

// Packet: 0x0812
packetLen(0x0812, 8)

// Packet: 0x0813
packetLen(0x0813, -1)

// Packet: 0x0814
packetLen(0x0814, 86)

// Packet: 0x0815
#if PACKETVER >= 20180314
packetLen(0x0815, 2)
#elif PACKETVER >= 20180228
packetLen(0x0815, -1)
#elif PACKETVER >= 20180221
packetLen(0x0815, 2)
#elif PACKETVER >= 20180213
packetLen(0x0815, 10)
#elif PACKETVER >= 20180131
packetLen(0x0815, -1)
#elif PACKETVER >= 20180103
packetLen(0x0815, 2)
#endif

// Packet: 0x0816
packetLen(0x0816, 6)

// Packet: 0x0817
#if PACKETVER >= 20180315
packetLen(0x0817, 6)
#elif PACKETVER >= 20180228
packetLen(0x0817, 2)
#elif PACKETVER >= 20180221
packetLen(0x0817, -1)
#elif PACKETVER >= 20180103
packetLen(0x0817, 2)
#endif

// Packet: 0x0818
packetLen(0x0818, -1)

// Packet: 0x0819
#if PACKETVER >= 20180523
packetLen(0x0819, -1)
#elif PACKETVER >= 20180511
packetLen(0x0819, 2)
#elif PACKETVER >= 20180315
packetLen(0x0819, -1)
#elif PACKETVER >= 20180314
packetLen(0x0819, 2)
#elif PACKETVER >= 20180228
packetLen(0x0819, -1)
#elif PACKETVER >= 20180213
packetLen(0x0819, 2)
#elif PACKETVER >= 20180131
packetLen(0x0819, -1)
#elif PACKETVER >= 20180103
packetLen(0x0819, 2)
#endif

// Packet: 0x081a
packetLen(0x081a, 4)

// Packet: 0x081b
#if PACKETVER >= 20181114
packetLen(0x081b, 12)
#elif PACKETVER >= 20180103
packetLen(0x081b, 10)
#endif

// Packet: 0x081c
packetLen(0x081c, 10)

// Packet: 0x081d
packetLen(0x081d, 22)

// Packet: 0x081e
packetLen(0x081e, 8)

// Packet: 0x081f
packetLen(0x081f, -1)

// Packet: 0x0820
packetLen(0x0820, 11)

// Packet: 0x0821
packetLen(0x0821, 2)

// Packet: 0x0822
packetLen(0x0822, 9)

// Packet: 0x0823
packetLen(0x0823, -1)

// Packet: 0x0824
#if PACKETVER >= 20181114
packetLen(0x0824, 8)
#elif PACKETVER >= 20180103
packetLen(0x0824, 6)
#endif

// Packet: 0x0825
packetLen(0x0825, -1)

// Packet: 0x0827
packetLen(0x0827, 6)

// Packet: 0x0828
packetLen(0x0828, 14)

// Packet: 0x0829
packetLen(0x0829, 12)

// Packet: 0x082a
packetLen(0x082a, 10)

// Packet: 0x082b
packetLen(0x082b, 6)

// Packet: 0x082c
packetLen(0x082c, 10)

// Packet: 0x082d
packetLen(0x082d, -1)

// Packet: 0x0835
#if PACKETVER >= 20180523
packetLen(0x0835, -1)
#elif PACKETVER >= 20180511
packetLen(0x0835, 2)
#elif PACKETVER >= 20180315
packetLen(0x0835, -1)
#elif PACKETVER >= 20180103
packetLen(0x0835, 2)
#endif

// Packet: 0x0836
packetLen(0x0836, -1)

// Packet: 0x0837
packetLen(0x0837, 3)

// Packet: 0x0838
#if PACKETVER >= 20180314
packetLen(0x0838, 2)
#elif PACKETVER >= 20180228
packetLen(0x0838, 12)
#elif PACKETVER >= 20180213
packetLen(0x0838, 2)
#elif PACKETVER >= 20180131
packetLen(0x0838, 12)
#elif PACKETVER >= 20180103
packetLen(0x0838, 2)
#endif

// Packet: 0x0839
packetLen(0x0839, 66)

// Packet: 0x083a
packetLen(0x083a, 5)

// Packet: 0x083b
packetLen(0x083b, 2)

// Packet: 0x083c
#if PACKETVER >= 20181114
packetLen(0x083c, 14)
#elif PACKETVER >= 20180523
packetLen(0x083c, 12)
#elif PACKETVER >= 20180511
packetLen(0x083c, 2)
#elif PACKETVER >= 20180315
packetLen(0x083c, 12)
#elif PACKETVER >= 20180314
packetLen(0x083c, 5)
#elif PACKETVER >= 20180228
packetLen(0x083c, 10)
#elif PACKETVER >= 20180213
packetLen(0x083c, 2)
#elif PACKETVER >= 20180131
packetLen(0x083c, 10)
#elif PACKETVER >= 20180117
packetLen(0x083c, 6)
#elif PACKETVER >= 20180103
packetLen(0x083c, 10)
#endif

// Packet: 0x083d
packetLen(0x083d, 6)

// Packet: 0x083e
packetLen(0x083e, 26)

// Packet: 0x0840
packetLen(0x0840, -1)

// Packet: 0x0841
packetLen(0x0841, 4)

// Packet: 0x0842
packetLen(0x0842, 6)

// Packet: 0x0843
packetLen(0x0843, 6)

// Packet: 0x0844
packetLen(0x0844, 2)

// Packet: 0x0845
packetLen(0x0845, 10)

// Packet: 0x0846
packetLen(0x0846, 4)

// Packet: 0x0847
packetLen(0x0847, -1)

// Packet: 0x0848
packetLen(0x0848, -1)

// Packet: 0x0849
packetLen(0x0849, 16)

// Packet: 0x084a
packetLen(0x084a, 2)

// Packet: 0x084b
#if PACKETVER >= 20181114
packetLen(0x084b, 21)
#elif PACKETVER >= 20180103
packetLen(0x084b, 19)
#endif

// Packet: 0x084c
packetLen(0x084c, 10)

// Packet: 0x084d
packetLen(0x084d, 10)

// Packet: 0x084e
packetLen(0x084e, 5)

// Packet: 0x084f
packetLen(0x084f, 6)

// Packet: 0x0850
packetLen(0x0850, 7)

// Packet: 0x0851
packetLen(0x0851, -1)

// Packet: 0x0852
packetLen(0x0852, 2)

// Packet: 0x0853
packetLen(0x0853, -1)

// Packet: 0x0854
packetLen(0x0854, -1)

// Packet: 0x0855
packetLen(0x0855, 6)

// Packet: 0x0856
packetLen(0x0856, -1)

// Packet: 0x0857
packetLen(0x0857, -1)

// Packet: 0x0858
packetLen(0x0858, -1)

// Packet: 0x0859
packetLen(0x0859, -1)

// Packet: 0x085a
#if PACKETVER >= 20180221
packetLen(0x085a, 2)
#elif PACKETVER >= 20180213
packetLen(0x085a, -1)
#elif PACKETVER >= 20180103
packetLen(0x085a, 2)
#endif

// Packet: 0x085b
#if PACKETVER >= 20180228
packetLen(0x085b, 2)
#elif PACKETVER >= 20180221
packetLen(0x085b, 10)
#elif PACKETVER >= 20180103
packetLen(0x085b, 2)
#endif

// Packet: 0x085c
packetLen(0x085c, 2)

// Packet: 0x085d
#if PACKETVER >= 20180315
packetLen(0x085d, 2)
#elif PACKETVER >= 20180314
packetLen(0x085d, 26)
#elif PACKETVER >= 20180221
packetLen(0x085d, 2)
#elif PACKETVER >= 20180213
packetLen(0x085d, 5)
#elif PACKETVER >= 20180103
packetLen(0x085d, 2)
#endif

// Packet: 0x085e
packetLen(0x085e, 2)

// Packet: 0x085f
#if PACKETVER >= 20180523
packetLen(0x085f, 2)
#elif PACKETVER >= 20180511
packetLen(0x085f, 6)
#elif PACKETVER >= 20180315
packetLen(0x085f, 2)
#elif PACKETVER >= 20180314
packetLen(0x085f, -1)
#elif PACKETVER >= 20180103
packetLen(0x085f, 2)
#endif

// Packet: 0x0860
#if PACKETVER >= 20180117
packetLen(0x0860, 2)
#elif PACKETVER >= 20180103
packetLen(0x0860, 5)
#endif

// Packet: 0x0861
packetLen(0x0861, 2)

// Packet: 0x0862
packetLen(0x0862, 2)

// Packet: 0x0863
#if PACKETVER >= 20180523
packetLen(0x0863, 2)
#elif PACKETVER >= 20180511
packetLen(0x0863, 6)
#elif PACKETVER >= 20180103
packetLen(0x0863, 2)
#endif

// Packet: 0x0864
packetLen(0x0864, 2)

// Packet: 0x0865
packetLen(0x0865, 2)

// Packet: 0x0866
#if PACKETVER >= 20180315
packetLen(0x0866, 2)
#elif PACKETVER >= 20180314
packetLen(0x0866, 5)
#elif PACKETVER >= 20180131
packetLen(0x0866, 2)
#elif PACKETVER >= 20180103
packetLen(0x0866, -1)
#endif

// Packet: 0x0867
packetLen(0x0867, 2)

// Packet: 0x0868
#if PACKETVER >= 20180221
packetLen(0x0868, 2)
#elif PACKETVER >= 20180213
packetLen(0x0868, 18)
#elif PACKETVER >= 20180103
packetLen(0x0868, 2)
#endif

// Packet: 0x0869
packetLen(0x0869, 2)

// Packet: 0x086a
#if PACKETVER >= 20180228
packetLen(0x086a, 2)
#elif PACKETVER >= 20180221
packetLen(0x086a, 8)
#elif PACKETVER >= 20180103
packetLen(0x086a, 2)
#endif

// Packet: 0x086b
packetLen(0x086b, 2)

// Packet: 0x086c
#if PACKETVER >= 20180523
packetLen(0x086c, 2)
#elif PACKETVER >= 20180511
packetLen(0x086c, 7)
#elif PACKETVER >= 20180103
packetLen(0x086c, 2)
#endif

// Packet: 0x086d
#if PACKETVER >= 20180117
packetLen(0x086d, 2)
#elif PACKETVER >= 20180103
packetLen(0x086d, 26)
#endif

// Packet: 0x086e
#if PACKETVER >= 20180131
packetLen(0x086e, 2)
#elif PACKETVER >= 20180117
packetLen(0x086e, 10)
#elif PACKETVER >= 20180103
packetLen(0x086e, 2)
#endif

// Packet: 0x086f
#if PACKETVER >= 20180131
packetLen(0x086f, 2)
#elif PACKETVER >= 20180117
packetLen(0x086f, 6)
#elif PACKETVER >= 20180103
packetLen(0x086f, 2)
#endif

// Packet: 0x0870
packetLen(0x0870, 2)

// Packet: 0x0871
#if PACKETVER >= 20180117
packetLen(0x0871, 2)
#elif PACKETVER >= 20180103
packetLen(0x0871, 6)
#endif

// Packet: 0x0872
#if PACKETVER >= 20180117
packetLen(0x0872, 2)
#elif PACKETVER >= 20180103
packetLen(0x0872, -1)
#endif

// Packet: 0x0873
packetLen(0x0873, 2)

// Packet: 0x0874
packetLen(0x0874, 2)

// Packet: 0x0875
packetLen(0x0875, 2)

// Packet: 0x0876
packetLen(0x0876, 2)

// Packet: 0x0877
#if PACKETVER >= 20180523
packetLen(0x0877, 2)
#elif PACKETVER >= 20180511
packetLen(0x0877, 8)
#elif PACKETVER >= 20180103
packetLen(0x0877, 2)
#endif

// Packet: 0x0878
#if PACKETVER >= 20180315
packetLen(0x0878, 2)
#elif PACKETVER >= 20180314
packetLen(0x0878, 8)
#elif PACKETVER >= 20180103
packetLen(0x0878, 2)
#endif

// Packet: 0x0879
packetLen(0x0879, 2)

// Packet: 0x087a
packetLen(0x087a, 2)

// Packet: 0x087b
#if PACKETVER >= 20180221
packetLen(0x087b, 2)
#elif PACKETVER >= 20180213
packetLen(0x087b, 6)
#elif PACKETVER >= 20180117
packetLen(0x087b, 2)
#elif PACKETVER >= 20180103
packetLen(0x087b, 8)
#endif

// Packet: 0x087c
packetLen(0x087c, 2)

// Packet: 0x087d
#if PACKETVER >= 20180131
packetLen(0x087d, 2)
#elif PACKETVER >= 20180117
packetLen(0x087d, 19)
#elif PACKETVER >= 20180103
packetLen(0x087d, 2)
#endif

// Packet: 0x087e
#if PACKETVER >= 20180523
packetLen(0x087e, 2)
#elif PACKETVER >= 20180511
packetLen(0x087e, -1)
#elif PACKETVER >= 20180103
packetLen(0x087e, 2)
#endif

// Packet: 0x087f
packetLen(0x087f, 2)

// Packet: 0x0880
#if PACKETVER >= 20180523
packetLen(0x0880, 2)
#elif PACKETVER >= 20180511
packetLen(0x0880, 6)
#elif PACKETVER >= 20180228
packetLen(0x0880, 2)
#elif PACKETVER >= 20180221
packetLen(0x0880, 19)
#elif PACKETVER >= 20180103
packetLen(0x0880, 2)
#endif

// Packet: 0x0881
#if PACKETVER >= 20180131
packetLen(0x0881, 2)
#elif PACKETVER >= 20180117
packetLen(0x0881, 10)
#elif PACKETVER >= 20180103
packetLen(0x0881, 2)
#endif

// Packet: 0x0882
#if PACKETVER >= 20180221
packetLen(0x0882, 2)
#elif PACKETVER >= 20180213
packetLen(0x0882, 12)
#elif PACKETVER >= 20180103
packetLen(0x0882, 2)
#endif

// Packet: 0x0883
packetLen(0x0883, 2)

// Packet: 0x0884
packetLen(0x0884, 2)

// Packet: 0x0885
packetLen(0x0885, 2)

// Packet: 0x0886
#if PACKETVER >= 20180131
packetLen(0x0886, 2)
#elif PACKETVER >= 20180117
packetLen(0x0886, 6)
#elif PACKETVER >= 20180103
packetLen(0x0886, 2)
#endif

// Packet: 0x0887
#if PACKETVER >= 20180221
packetLen(0x0887, 2)
#elif PACKETVER >= 20180213
packetLen(0x0887, -1)
#elif PACKETVER >= 20180103
packetLen(0x0887, 2)
#endif

// Packet: 0x0888
#if PACKETVER >= 20180221
packetLen(0x0888, 2)
#elif PACKETVER >= 20180213
packetLen(0x0888, 6)
#elif PACKETVER >= 20180117
packetLen(0x0888, 2)
#elif PACKETVER >= 20180103
packetLen(0x0888, 7)
#endif

// Packet: 0x0889
#if PACKETVER >= 20180523
packetLen(0x0889, 2)
#elif PACKETVER >= 20180511
packetLen(0x0889, 8)
#elif PACKETVER >= 20180103
packetLen(0x0889, 2)
#endif

// Packet: 0x088a
#if PACKETVER >= 20180221
packetLen(0x088a, 2)
#elif PACKETVER >= 20180213
packetLen(0x088a, 4)
#elif PACKETVER >= 20180103
packetLen(0x088a, 2)
#endif

// Packet: 0x088b
packetLen(0x088b, 2)

// Packet: 0x088c
packetLen(0x088c, 2)

// Packet: 0x088d
#if PACKETVER >= 20180315
packetLen(0x088d, 2)
#elif PACKETVER >= 20180314
packetLen(0x088d, 36)
#elif PACKETVER >= 20180228
packetLen(0x088d, 2)
#elif PACKETVER >= 20180221
packetLen(0x088d, 6)
#elif PACKETVER >= 20180103
packetLen(0x088d, 2)
#endif

// Packet: 0x088e
#if PACKETVER >= 20180221
packetLen(0x088e, 2)
#elif PACKETVER >= 20180213
packetLen(0x088e, 6)
#elif PACKETVER >= 20180103
packetLen(0x088e, 2)
#endif

// Packet: 0x088f
packetLen(0x088f, 2)

// Packet: 0x0890
#if PACKETVER >= 20180131
packetLen(0x0890, 2)
#elif PACKETVER >= 20180117
packetLen(0x0890, 8)
#elif PACKETVER >= 20180103
packetLen(0x0890, 6)
#endif

// Packet: 0x0891
#if PACKETVER >= 20180315
packetLen(0x0891, 2)
#elif PACKETVER >= 20180314
packetLen(0x0891, 8)
#elif PACKETVER >= 20180131
packetLen(0x0891, 2)
#elif PACKETVER >= 20180117
packetLen(0x0891, 6)
#elif PACKETVER >= 20180103
packetLen(0x0891, 2)
#endif

// Packet: 0x0892
#if PACKETVER >= 20180228
packetLen(0x0892, 2)
#elif PACKETVER >= 20180221
packetLen(0x0892, 6)
#elif PACKETVER >= 20180103
packetLen(0x0892, 2)
#endif

// Packet: 0x0893
#if PACKETVER >= 20180523
packetLen(0x0893, 2)
#elif PACKETVER >= 20180511
packetLen(0x0893, 18)
#elif PACKETVER >= 20180131
packetLen(0x0893, 2)
#elif PACKETVER >= 20180117
packetLen(0x0893, 7)
#elif PACKETVER >= 20180103
packetLen(0x0893, 2)
#endif

// Packet: 0x0894
packetLen(0x0894, 2)

// Packet: 0x0895
#if PACKETVER >= 20180228
packetLen(0x0895, 2)
#elif PACKETVER >= 20180221
packetLen(0x0895, 6)
#elif PACKETVER >= 20180103
packetLen(0x0895, 2)
#endif

// Packet: 0x0896
#if PACKETVER >= 20180523
packetLen(0x0896, 2)
#elif PACKETVER >= 20180511
packetLen(0x0896, 19)
#elif PACKETVER >= 20180117
packetLen(0x0896, 2)
#elif PACKETVER >= 20180103
packetLen(0x0896, 10)
#endif

// Packet: 0x0897
#if PACKETVER >= 20180315
packetLen(0x0897, 2)
#elif PACKETVER >= 20180314
packetLen(0x0897, 6)
#elif PACKETVER >= 20180103
packetLen(0x0897, 2)
#endif

// Packet: 0x0898
packetLen(0x0898, 2)

// Packet: 0x0899
#if PACKETVER >= 20180523
packetLen(0x0899, 2)
#elif PACKETVER >= 20180511
packetLen(0x0899, 12)
#elif PACKETVER >= 20180315
packetLen(0x0899, 2)
#elif PACKETVER >= 20180314
packetLen(0x0899, 8)
#elif PACKETVER >= 20180221
packetLen(0x0899, 2)
#elif PACKETVER >= 20180213
packetLen(0x0899, 26)
#elif PACKETVER >= 20180131
packetLen(0x0899, 2)
#elif PACKETVER >= 20180117
packetLen(0x0899, -1)
#elif PACKETVER >= 20180103
packetLen(0x0899, 2)
#endif

// Packet: 0x089a
packetLen(0x089a, 2)

// Packet: 0x089b
packetLen(0x089b, 2)

// Packet: 0x089c
packetLen(0x089c, 2)

// Packet: 0x089d
#if PACKETVER >= 20180131
packetLen(0x089d, 2)
#elif PACKETVER >= 20180117
packetLen(0x089d, -1)
#elif PACKETVER >= 20180103
packetLen(0x089d, 8)
#endif

// Packet: 0x089e
#if PACKETVER >= 20180315
packetLen(0x089e, 2)
#elif PACKETVER >= 20180314
packetLen(0x089e, -1)
#elif PACKETVER >= 20180131
packetLen(0x089e, 2)
#elif PACKETVER >= 20180117
packetLen(0x089e, 5)
#elif PACKETVER >= 20180103
packetLen(0x089e, 2)
#endif

// Packet: 0x089f
packetLen(0x089f, 2)

// Packet: 0x08a0
packetLen(0x08a0, 2)

// Packet: 0x08a1
#if PACKETVER >= 20180315
packetLen(0x08a1, 2)
#elif PACKETVER >= 20180314
packetLen(0x08a1, 4)
#elif PACKETVER >= 20180228
packetLen(0x08a1, 2)
#elif PACKETVER >= 20180221
packetLen(0x08a1, 5)
#elif PACKETVER >= 20180103
packetLen(0x08a1, 2)
#endif

// Packet: 0x08a2
#if PACKETVER >= 20180523
packetLen(0x08a2, 2)
#elif PACKETVER >= 20180511
packetLen(0x08a2, 6)
#elif PACKETVER >= 20180103
packetLen(0x08a2, 2)
#endif

// Packet: 0x08a3
#if PACKETVER >= 20180228
packetLen(0x08a3, 2)
#elif PACKETVER >= 20180221
packetLen(0x08a3, 10)
#elif PACKETVER >= 20180103
packetLen(0x08a3, 2)
#endif

// Packet: 0x08a4
packetLen(0x08a4, 2)

// Packet: 0x08a5
#if PACKETVER >= 20180523
packetLen(0x08a5, 2)
#elif PACKETVER >= 20180511
packetLen(0x08a5, 6)
#elif PACKETVER >= 20180103
packetLen(0x08a5, 2)
#endif

// Packet: 0x08a6
#if PACKETVER >= 20180117
packetLen(0x08a6, 2)
#elif PACKETVER >= 20180103
packetLen(0x08a6, 6)
#endif

// Packet: 0x08a7
packetLen(0x08a7, 2)

// Packet: 0x08a8
packetLen(0x08a8, 2)

// Packet: 0x08a9
packetLen(0x08a9, 2)

// Packet: 0x08aa
packetLen(0x08aa, 2)

// Packet: 0x08ab
packetLen(0x08ab, 2)

// Packet: 0x08ac
packetLen(0x08ac, 2)

// Packet: 0x08ad
packetLen(0x08ad, 2)

// Packet: 0x08af
packetLen(0x08af, 10)

// Packet: 0x08b0
packetLen(0x08b0, 17)

// Packet: 0x08b1
packetLen(0x08b1, -1)

// Packet: 0x08b2
packetLen(0x08b2, -1)

// Packet: 0x08b3
packetLen(0x08b3, -1)

// Packet: 0x08b4
packetLen(0x08b4, 2)

// Packet: 0x08b5
packetLen(0x08b5, 6)

// Packet: 0x08b6
packetLen(0x08b6, 3)

// Packet: 0x08b8
packetLen(0x08b8, 10)

// Packet: 0x08b9
packetLen(0x08b9, 12)

// Packet: 0x08ba
packetLen(0x08ba, 10)

// Packet: 0x08bb
packetLen(0x08bb, 8)

// Packet: 0x08bc
packetLen(0x08bc, 10)

// Packet: 0x08bd
packetLen(0x08bd, 8)

// Packet: 0x08be
packetLen(0x08be, 14)

// Packet: 0x08bf
packetLen(0x08bf, 8)

// Packet: 0x08c0
packetLen(0x08c0, -1)

// Packet: 0x08c1
packetLen(0x08c1, 2)

// Packet: 0x08c2
packetLen(0x08c2, 2)

// Packet: 0x08c3
packetLen(0x08c3, 10)

// Packet: 0x08c4
packetLen(0x08c4, 8)

// Packet: 0x08c5
packetLen(0x08c5, 6)

// Packet: 0x08c6
packetLen(0x08c6, 4)

// Packet: 0x08c7
packetLen(0x08c7, -1)

// Packet: 0x08c8
packetLen(0x08c8, 34)

// Packet: 0x08c9
packetLen(0x08c9, 2)

// Packet: 0x08ca
packetLen(0x08ca, -1)

// Packet: 0x08cb
packetLen(0x08cb, -1)

// Packet: 0x08cc
packetLen(0x08cc, 109)

// Packet: 0x08cd
packetLen(0x08cd, 10)

// Packet: 0x08ce
packetLen(0x08ce, 2)

// Packet: 0x08cf
packetLen(0x08cf, 10)

// Packet: 0x08d0
packetLen(0x08d0, 9)

// Packet: 0x08d1
packetLen(0x08d1, 7)

// Packet: 0x08d2
packetLen(0x08d2, 10)

// Packet: 0x08d3
packetLen(0x08d3, 10)

// Packet: 0x08d4
packetLen(0x08d4, 8)

// Packet: 0x08d5
packetLen(0x08d5, -1)

// Packet: 0x08d6
packetLen(0x08d6, 6)

// Packet: 0x08d7
packetLen(0x08d7, 28)

// Packet: 0x08d8
packetLen(0x08d8, 27)

// Packet: 0x08d9
packetLen(0x08d9, 30)

// Packet: 0x08da
packetLen(0x08da, 26)

// Packet: 0x08db
packetLen(0x08db, 27)

// Packet: 0x08dc
packetLen(0x08dc, 26)

// Packet: 0x08dd
packetLen(0x08dd, 27)

// Packet: 0x08de
packetLen(0x08de, 27)

// Packet: 0x08df
packetLen(0x08df, 50)

// Packet: 0x08e0
packetLen(0x08e0, 51)

// Packet: 0x08e1
packetLen(0x08e1, 51)

// Packet: 0x08e2
packetLen(0x08e2, 27)

// Packet: 0x08e3
packetLen(0x08e3, 157)

// Packet: 0x08e4
packetLen(0x08e4, 6)

// Packet: 0x08fc
packetLen(0x08fc, 30)

// Packet: 0x08fd
packetLen(0x08fd, 6)

// Packet: 0x08fe
packetLen(0x08fe, -1)

// Packet: 0x08ff
packetLen(0x08ff, 24)

// Packet: 0x0900
packetLen(0x0900, -1)

// Packet: 0x0901
packetLen(0x0901, -1)

// Packet: 0x0902
packetLen(0x0902, -1)

// Packet: 0x0903
packetLen(0x0903, -1)

// Packet: 0x0904
packetLen(0x0904, -1)

// Packet: 0x0905
packetLen(0x0905, -1)

// Packet: 0x0906
packetLen(0x0906, -1)

// Packet: 0x0907
packetLen(0x0907, 5)

// Packet: 0x0908
packetLen(0x0908, 5)

// Packet: 0x090a
packetLen(0x090a, 26)

// Packet: 0x090d
packetLen(0x090d, -1)

// Packet: 0x090e
packetLen(0x090e, 2)

// Packet: 0x090f
packetLen(0x090f, -1)

// Packet: 0x0910
packetLen(0x0910, 10)

// Packet: 0x0911
packetLen(0x0911, 30)

// Packet: 0x0912
packetLen(0x0912, 10)

// Packet: 0x0913
packetLen(0x0913, 30)

// Packet: 0x0914
packetLen(0x0914, -1)

// Packet: 0x0915
packetLen(0x0915, -1)

// Packet: 0x0916
packetLen(0x0916, 26)

// Packet: 0x0917
#if PACKETVER >= 20180315
packetLen(0x0917, 2)
#elif PACKETVER >= 20180314
packetLen(0x0917, -1)
#elif PACKETVER >= 20180221
packetLen(0x0917, 2)
#elif PACKETVER >= 20180213
packetLen(0x0917, 7)
#elif PACKETVER >= 20180103
packetLen(0x0917, 2)
#endif

// Packet: 0x0918
#if PACKETVER >= 20180315
packetLen(0x0918, 2)
#elif PACKETVER >= 20180314
packetLen(0x0918, 7)
#elif PACKETVER >= 20180103
packetLen(0x0918, 2)
#endif

// Packet: 0x0919
#if PACKETVER >= 20180523
packetLen(0x0919, 2)
#elif PACKETVER >= 20180511
packetLen(0x0919, 5)
#elif PACKETVER >= 20180131
packetLen(0x0919, 2)
#elif PACKETVER >= 20180117
packetLen(0x0919, 6)
#elif PACKETVER >= 20180103
packetLen(0x0919, 2)
#endif

// Packet: 0x091a
#if PACKETVER >= 20180523
packetLen(0x091a, 2)
#elif PACKETVER >= 20180511
packetLen(0x091a, -1)
#elif PACKETVER >= 20180103
packetLen(0x091a, 2)
#endif

// Packet: 0x091b
#if PACKETVER >= 20180228
packetLen(0x091b, 2)
#elif PACKETVER >= 20180221
packetLen(0x091b, 90)
#elif PACKETVER >= 20180103
packetLen(0x091b, 2)
#endif

// Packet: 0x091c
#if PACKETVER >= 20180131
packetLen(0x091c, 2)
#elif PACKETVER >= 20180117
packetLen(0x091c, 8)
#elif PACKETVER >= 20180103
packetLen(0x091c, 2)
#endif

// Packet: 0x091d
#if PACKETVER >= 20180523
packetLen(0x091d, 2)
#elif PACKETVER >= 20180511
packetLen(0x091d, -1)
#elif PACKETVER >= 20180221
packetLen(0x091d, 2)
#elif PACKETVER >= 20180213
packetLen(0x091d, 5)
#elif PACKETVER >= 20180103
packetLen(0x091d, 2)
#endif

// Packet: 0x091e
#if PACKETVER >= 20180117
packetLen(0x091e, 2)
#elif PACKETVER >= 20180103
packetLen(0x091e, 6)
#endif

// Packet: 0x091f
#if PACKETVER >= 20180315
packetLen(0x091f, 2)
#elif PACKETVER >= 20180314
packetLen(0x091f, 10)
#elif PACKETVER >= 20180131
packetLen(0x091f, 2)
#elif PACKETVER >= 20180117
packetLen(0x091f, 90)
#elif PACKETVER >= 20180103
packetLen(0x091f, 2)
#endif

// Packet: 0x0920
#if PACKETVER >= 20180523
packetLen(0x0920, 2)
#elif PACKETVER >= 20180511
packetLen(0x0920, 4)
#elif PACKETVER >= 20180315
packetLen(0x0920, 2)
#elif PACKETVER >= 20180314
packetLen(0x0920, 6)
#elif PACKETVER >= 20180103
packetLen(0x0920, 2)
#endif

// Packet: 0x0921
#if PACKETVER >= 20180228
packetLen(0x0921, 2)
#elif PACKETVER >= 20180221
packetLen(0x0921, -1)
#elif PACKETVER >= 20180131
packetLen(0x0921, 2)
#elif PACKETVER >= 20180117
packetLen(0x0921, 5)
#elif PACKETVER >= 20180103
packetLen(0x0921, 2)
#endif

// Packet: 0x0922
#if PACKETVER >= 20180221
packetLen(0x0922, 2)
#elif PACKETVER >= 20180213
packetLen(0x0922, -1)
#elif PACKETVER >= 20180103
packetLen(0x0922, 2)
#endif

// Packet: 0x0923
#if PACKETVER >= 20180315
packetLen(0x0923, 2)
#elif PACKETVER >= 20180314
packetLen(0x0923, 12)
#elif PACKETVER >= 20180228
packetLen(0x0923, 2)
#elif PACKETVER >= 20180221
packetLen(0x0923, 5)
#elif PACKETVER >= 20180103
packetLen(0x0923, 2)
#endif

// Packet: 0x0924
#if PACKETVER >= 20180117
packetLen(0x0924, 2)
#elif PACKETVER >= 20180103
packetLen(0x0924, 4)
#endif

// Packet: 0x0925
packetLen(0x0925, 2)

// Packet: 0x0926
packetLen(0x0926, 2)

// Packet: 0x0927
packetLen(0x0927, 2)

// Packet: 0x0928
packetLen(0x0928, 2)

// Packet: 0x0929
#if PACKETVER >= 20180131
packetLen(0x0929, 2)
#elif PACKETVER >= 20180117
packetLen(0x0929, 18)
#elif PACKETVER >= 20180103
packetLen(0x0929, 2)
#endif

// Packet: 0x092a
packetLen(0x092a, 2)

// Packet: 0x092b
packetLen(0x092b, 2)

// Packet: 0x092c
#if PACKETVER >= 20180523
packetLen(0x092c, 2)
#elif PACKETVER >= 20180511
packetLen(0x092c, 10)
#elif PACKETVER >= 20180103
packetLen(0x092c, 2)
#endif

// Packet: 0x092d
#if PACKETVER >= 20180523
packetLen(0x092d, 2)
#elif PACKETVER >= 20180511
packetLen(0x092d, 26)
#elif PACKETVER >= 20180228
packetLen(0x092d, 2)
#elif PACKETVER >= 20180221
packetLen(0x092d, 26)
#elif PACKETVER >= 20180131
packetLen(0x092d, 2)
#elif PACKETVER >= 20180117
packetLen(0x092d, 4)
#elif PACKETVER >= 20180103
packetLen(0x092d, 2)
#endif

// Packet: 0x092e
#if PACKETVER >= 20180523
packetLen(0x092e, 2)
#elif PACKETVER >= 20180511
packetLen(0x092e, -1)
#elif PACKETVER >= 20180103
packetLen(0x092e, 2)
#endif

// Packet: 0x092f
packetLen(0x092f, 2)

// Packet: 0x0930
#if PACKETVER >= 20180315
packetLen(0x0930, 2)
#elif PACKETVER >= 20180314
packetLen(0x0930, 6)
#elif PACKETVER >= 20180228
packetLen(0x0930, 36)
#elif PACKETVER >= 20180221
packetLen(0x0930, 2)
#elif PACKETVER >= 20180213
packetLen(0x0930, 8)
#elif PACKETVER >= 20180103
packetLen(0x0930, 2)
#endif

// Packet: 0x0931
#if PACKETVER >= 20180315
packetLen(0x0931, 2)
#elif PACKETVER >= 20180314
packetLen(0x0931, 6)
#elif PACKETVER >= 20180103
packetLen(0x0931, 2)
#endif

// Packet: 0x0932
#if PACKETVER >= 20180228
packetLen(0x0932, 2)
#elif PACKETVER >= 20180221
packetLen(0x0932, -1)
#elif PACKETVER >= 20180103
packetLen(0x0932, 2)
#endif

// Packet: 0x0933
#if PACKETVER >= 20180131
packetLen(0x0933, 2)
#elif PACKETVER >= 20180117
packetLen(0x0933, 12)
#elif PACKETVER >= 20180103
packetLen(0x0933, 2)
#endif

// Packet: 0x0934
packetLen(0x0934, 2)

// Packet: 0x0935
packetLen(0x0935, 2)

// Packet: 0x0936
packetLen(0x0936, 2)

// Packet: 0x0937
packetLen(0x0937, 2)

// Packet: 0x0938
#if PACKETVER >= 20180117
packetLen(0x0938, 2)
#elif PACKETVER >= 20180103
packetLen(0x0938, 90)
#endif

// Packet: 0x0939
packetLen(0x0939, 2)

// Packet: 0x093a
packetLen(0x093a, 2)

// Packet: 0x093b
#if PACKETVER >= 20180228
packetLen(0x093b, 2)
#elif PACKETVER >= 20180221
packetLen(0x093b, 12)
#elif PACKETVER >= 20180117
packetLen(0x093b, 2)
#elif PACKETVER >= 20180103
packetLen(0x093b, 26)
#endif

// Packet: 0x093c
packetLen(0x093c, 2)

// Packet: 0x093d
#if PACKETVER >= 20180228
packetLen(0x093d, 2)
#elif PACKETVER >= 20180221
packetLen(0x093d, 26)
#elif PACKETVER >= 20180103
packetLen(0x093d, 2)
#endif

// Packet: 0x093e
#if PACKETVER >= 20180228
packetLen(0x093e, 2)
#elif PACKETVER >= 20180221
packetLen(0x093e, 8)
#elif PACKETVER >= 20180103
packetLen(0x093e, 2)
#endif

// Packet: 0x093f
#if PACKETVER >= 20180315
packetLen(0x093f, 2)
#elif PACKETVER >= 20180314
packetLen(0x093f, 6)
#elif PACKETVER >= 20180103
packetLen(0x093f, 2)
#endif

// Packet: 0x0940
#if PACKETVER >= 20180207
packetLen(0x0940, 2)
#elif PACKETVER >= 20180131
packetLen(0x0940, 90)
#elif PACKETVER >= 20180103
packetLen(0x0940, 2)
#endif

// Packet: 0x0941
#if PACKETVER >= 20180221
packetLen(0x0941, 2)
#elif PACKETVER >= 20180213
packetLen(0x0941, 19)
#elif PACKETVER >= 20180103
packetLen(0x0941, 2)
#endif

// Packet: 0x0942
#if PACKETVER >= 20180523
packetLen(0x0942, 2)
#elif PACKETVER >= 20180511
packetLen(0x0942, 5)
#elif PACKETVER >= 20180228
packetLen(0x0942, 2)
#elif PACKETVER >= 20180221
packetLen(0x0942, 36)
#elif PACKETVER >= 20180213
packetLen(0x0942, 8)
#elif PACKETVER >= 20180103
packetLen(0x0942, 2)
#endif

// Packet: 0x0943
packetLen(0x0943, 2)

// Packet: 0x0944
packetLen(0x0944, 2)

// Packet: 0x0945
packetLen(0x0945, 2)

// Packet: 0x0946
#if PACKETVER >= 20180315
packetLen(0x0946, 2)
#elif PACKETVER >= 20180314
packetLen(0x0946, 90)
#elif PACKETVER >= 20180131
packetLen(0x0946, 2)
#elif PACKETVER >= 20180117
packetLen(0x0946, 26)
#elif PACKETVER >= 20180103
packetLen(0x0946, 2)
#endif

// Packet: 0x0947
#if PACKETVER >= 20180221
packetLen(0x0947, 2)
#elif PACKETVER >= 20180213
packetLen(0x0947, 6)
#elif PACKETVER >= 20180103
packetLen(0x0947, 2)
#endif

// Packet: 0x0948
packetLen(0x0948, 2)

// Packet: 0x0949
packetLen(0x0949, 2)

// Packet: 0x094a
#if PACKETVER >= 20180523
packetLen(0x094a, 2)
#elif PACKETVER >= 20180511
packetLen(0x094a, 90)
#elif PACKETVER >= 20180315
packetLen(0x094a, 2)
#elif PACKETVER >= 20180314
packetLen(0x094a, 10)
#elif PACKETVER >= 20180103
packetLen(0x094a, 2)
#endif

// Packet: 0x094b
packetLen(0x094b, 2)

// Packet: 0x094c
packetLen(0x094c, 2)

// Packet: 0x094d
#if PACKETVER >= 20180221
packetLen(0x094d, 2)
#elif PACKETVER >= 20180213
packetLen(0x094d, 10)
#elif PACKETVER >= 20180103
packetLen(0x094d, 2)
#endif

// Packet: 0x094e
#if PACKETVER >= 20180315
packetLen(0x094e, 2)
#elif PACKETVER >= 20180314
packetLen(0x094e, 5)
#elif PACKETVER >= 20180103
packetLen(0x094e, 2)
#endif

// Packet: 0x094f
packetLen(0x094f, 2)

// Packet: 0x0950
packetLen(0x0950, 2)

// Packet: 0x0951
#if PACKETVER >= 20180228
packetLen(0x0951, 2)
#elif PACKETVER >= 20180221
packetLen(0x0951, 18)
#elif PACKETVER >= 20180103
packetLen(0x0951, 2)
#endif

// Packet: 0x0952
#if PACKETVER >= 20180228
packetLen(0x0952, 2)
#elif PACKETVER >= 20180221
packetLen(0x0952, 4)
#elif PACKETVER >= 20180103
packetLen(0x0952, 2)
#endif

// Packet: 0x0953
packetLen(0x0953, 2)

// Packet: 0x0954
#if PACKETVER >= 20180315
packetLen(0x0954, 2)
#elif PACKETVER >= 20180314
packetLen(0x0954, 18)
#elif PACKETVER >= 20180103
packetLen(0x0954, 2)
#endif

// Packet: 0x0955
#if PACKETVER >= 20180523
packetLen(0x0955, 2)
#elif PACKETVER >= 20180511
packetLen(0x0955, 26)
#elif PACKETVER >= 20180103
packetLen(0x0955, 2)
#endif

// Packet: 0x0956
#if PACKETVER >= 20180523
packetLen(0x0956, 2)
#elif PACKETVER >= 20180511
packetLen(0x0956, 8)
#elif PACKETVER >= 20180315
packetLen(0x0956, 2)
#elif PACKETVER >= 20180314
packetLen(0x0956, 6)
#elif PACKETVER >= 20180117
packetLen(0x0956, 2)
#elif PACKETVER >= 20180103
packetLen(0x0956, -1)
#endif

// Packet: 0x0957
packetLen(0x0957, 2)

// Packet: 0x0958
#if PACKETVER >= 20180315
packetLen(0x0958, 2)
#elif PACKETVER >= 20180314
packetLen(0x0958, -1)
#elif PACKETVER >= 20180228
packetLen(0x0958, 2)
#elif PACKETVER >= 20180221
packetLen(0x0958, 7)
#elif PACKETVER >= 20180213
packetLen(0x0958, 26)
#elif PACKETVER >= 20180117
packetLen(0x0958, 2)
#elif PACKETVER >= 20180103
packetLen(0x0958, 19)
#endif

// Packet: 0x0959
#if PACKETVER >= 20180228
packetLen(0x0959, 2)
#elif PACKETVER >= 20180221
packetLen(0x0959, 8)
#elif PACKETVER >= 20180103
packetLen(0x0959, 2)
#endif

// Packet: 0x095a
packetLen(0x095a, 2)

// Packet: 0x095b
#if PACKETVER >= 20180117
packetLen(0x095b, 2)
#elif PACKETVER >= 20180103
packetLen(0x095b, 36)
#endif

// Packet: 0x095c
#if PACKETVER >= 20180523
packetLen(0x095c, 2)
#elif PACKETVER >= 20180511
packetLen(0x095c, 10)
#elif PACKETVER >= 20180221
packetLen(0x095c, 2)
#elif PACKETVER >= 20180213
packetLen(0x095c, -1)
#elif PACKETVER >= 20180103
packetLen(0x095c, 2)
#endif

// Packet: 0x095d
#if PACKETVER >= 20180228
packetLen(0x095d, 2)
#elif PACKETVER >= 20180221
packetLen(0x095d, 6)
#elif PACKETVER >= 20180117
packetLen(0x095d, 2)
#elif PACKETVER >= 20180103
packetLen(0x095d, 6)
#endif

// Packet: 0x095e
#if PACKETVER >= 20180131
packetLen(0x095e, 2)
#elif PACKETVER >= 20180117
packetLen(0x095e, -1)
#elif PACKETVER >= 20180103
packetLen(0x095e, 2)
#endif

// Packet: 0x095f
packetLen(0x095f, 2)

// Packet: 0x0960
packetLen(0x0960, 2)

// Packet: 0x0961
#if PACKETVER >= 20180523
packetLen(0x0961, 2)
#elif PACKETVER >= 20180511
packetLen(0x0961, 5)
#elif PACKETVER >= 20180103
packetLen(0x0961, 2)
#endif

// Packet: 0x0962
packetLen(0x0962, 2)

// Packet: 0x0963
#if PACKETVER >= 20180131
packetLen(0x0963, 2)
#elif PACKETVER >= 20180117
packetLen(0x0963, 5)
#elif PACKETVER >= 20180103
packetLen(0x0963, 2)
#endif

// Packet: 0x0964
#if PACKETVER >= 20180117
packetLen(0x0964, 2)
#elif PACKETVER >= 20180103
packetLen(0x0964, 6)
#endif

// Packet: 0x0965
packetLen(0x0965, 2)

// Packet: 0x0966
#if PACKETVER >= 20180117
packetLen(0x0966, 2)
#elif PACKETVER >= 20180103
packetLen(0x0966, 8)
#endif

// Packet: 0x0967
#if PACKETVER >= 20180221
packetLen(0x0967, 2)
#elif PACKETVER >= 20180207
packetLen(0x0967, 36)
#elif PACKETVER >= 20180103
packetLen(0x0967, 2)
#endif

// Packet: 0x0968
#if PACKETVER >= 20180523
packetLen(0x0968, 2)
#elif PACKETVER >= 20180511
packetLen(0x0968, 36)
#elif PACKETVER >= 20180103
packetLen(0x0968, 2)
#endif

// Packet: 0x0969
packetLen(0x0969, 2)

// Packet: 0x096a
#if PACKETVER >= 20180314
packetLen(0x096a, 2)
#elif PACKETVER >= 20180228
packetLen(0x096a, 6)
#elif PACKETVER >= 20180213
packetLen(0x096a, 2)
#elif PACKETVER >= 20180131
packetLen(0x096a, 6)
#elif PACKETVER >= 20180117
packetLen(0x096a, 2)
#elif PACKETVER >= 20180103
packetLen(0x096a, 12)
#endif

// Packet: 0x096b
packetLen(0x096b, 4)

// Packet: 0x096c
packetLen(0x096c, 6)

// Packet: 0x096d
packetLen(0x096d, -1)

// Packet: 0x096e
packetLen(0x096e, -1)

// Packet: 0x096f
packetLen(0x096f, 7)

// Packet: 0x0970
packetLen(0x0970, 31)

// Packet: 0x0971
packetLen(0x0971, 6)

// Packet: 0x0972
packetLen(0x0972, -1)

// Packet: 0x0973
packetLen(0x0973, 7)

// Packet: 0x0974
packetLen(0x0974, 2)

// Packet: 0x0975
packetLen(0x0975, -1)

// Packet: 0x0976
packetLen(0x0976, -1)

// Packet: 0x0977
packetLen(0x0977, 14)

// Packet: 0x0978
packetLen(0x0978, 6)

// Packet: 0x0979
packetLen(0x0979, 50)

// Packet: 0x097a
packetLen(0x097a, -1)

// Packet: 0x097b
packetLen(0x097b, -1)

// Packet: 0x097c
packetLen(0x097c, 4)

// Packet: 0x097d
packetLen(0x097d, 288)

// Packet: 0x097e
packetLen(0x097e, 12)

// Packet: 0x097f
packetLen(0x097f, -1)

// Packet: 0x0980
packetLen(0x0980, 7)

// Packet: 0x0981
packetLen(0x0981, -1)

// Packet: 0x0982
packetLen(0x0982, 7)

// Packet: 0x0983
packetLen(0x0983, 29)

// Packet: 0x0984
packetLen(0x0984, 28)

// Packet: 0x0985
packetLen(0x0985, -1)

// Packet: 0x0986
packetLen(0x0986, 10)

// Packet: 0x0987
packetLen(0x0987, -1)

// Packet: 0x0988
packetLen(0x0988, 6)

// Packet: 0x0989
packetLen(0x0989, 2)

// Packet: 0x098a
packetLen(0x098a, -1)

// Packet: 0x098b
packetLen(0x098b, 2)

// Packet: 0x098c
packetLen(0x098c, 4)

// Packet: 0x098d
packetLen(0x098d, -1)

// Packet: 0x098e
packetLen(0x098e, -1)

// Packet: 0x098f
packetLen(0x098f, -1)

// Packet: 0x0990
#if PACKETVER >= 20181114
packetLen(0x0990, 41)
#elif PACKETVER >= 20180103
packetLen(0x0990, 31)
#endif

// Packet: 0x0991
packetLen(0x0991, -1)

// Packet: 0x0992
packetLen(0x0992, -1)

// Packet: 0x0993
packetLen(0x0993, -1)

// Packet: 0x0994
packetLen(0x0994, -1)

// Packet: 0x0995
packetLen(0x0995, -1)

// Packet: 0x0996
packetLen(0x0996, -1)

// Packet: 0x0997
packetLen(0x0997, -1)

// Packet: 0x0998
packetLen(0x0998, 8)

// Packet: 0x0999
packetLen(0x0999, 11)

// Packet: 0x099a
packetLen(0x099a, 9)

// Packet: 0x099b
packetLen(0x099b, 8)

// Packet: 0x099c
packetLen(0x099c, 6)

// Packet: 0x099d
packetLen(0x099d, -1)

// Packet: 0x099e
packetLen(0x099e, 12)

// Packet: 0x099f
packetLen(0x099f, -1)

// Packet: 0x09a0
packetLen(0x09a0, 6)

// Packet: 0x09a1
packetLen(0x09a1, 2)

// Packet: 0x09a2
packetLen(0x09a2, 6)

// Packet: 0x09a3
packetLen(0x09a3, -1)

// Packet: 0x09a4
packetLen(0x09a4, 18)

// Packet: 0x09a5
packetLen(0x09a5, 7)

// Packet: 0x09a6
packetLen(0x09a6, 12)

// Packet: 0x09a7
packetLen(0x09a7, 10)

// Packet: 0x09a8
packetLen(0x09a8, 16)

// Packet: 0x09a9
packetLen(0x09a9, 10)

// Packet: 0x09aa
packetLen(0x09aa, 16)

// Packet: 0x09ab
packetLen(0x09ab, 6)

// Packet: 0x09ac
packetLen(0x09ac, -1)

// Packet: 0x09ad
#if PACKETVER >= 20181114
packetLen(0x09ad, 12)
#elif PACKETVER >= 20180103
packetLen(0x09ad, 10)
#endif

// Packet: 0x09ae
#if PACKETVER >= 20181114
packetLen(0x09ae, 19)
#elif PACKETVER >= 20180103
packetLen(0x09ae, 17)
#endif

// Packet: 0x09af
packetLen(0x09af, 4)

// Packet: 0x09b0
#if PACKETVER >= 20181114
packetLen(0x09b0, 10)
#elif PACKETVER >= 20180103
packetLen(0x09b0, 8)
#endif

// Packet: 0x09b1
packetLen(0x09b1, 4)

// Packet: 0x09b2
#if PACKETVER >= 20181114
packetLen(0x09b2, 10)
#elif PACKETVER >= 20180103
packetLen(0x09b2, 8)
#endif

// Packet: 0x09b3
#if PACKETVER >= 20181114
packetLen(0x09b3, 6)
#elif PACKETVER >= 20180103
packetLen(0x09b3, 4)
#endif

// Packet: 0x09b4
packetLen(0x09b4, 6)

// Packet: 0x09b5
packetLen(0x09b5, 2)

// Packet: 0x09b6
packetLen(0x09b6, 6)

// Packet: 0x09b7
packetLen(0x09b7, 4)

// Packet: 0x09b8
packetLen(0x09b8, 6)

// Packet: 0x09b9
packetLen(0x09b9, 4)

// Packet: 0x09ba
packetLen(0x09ba, 2)

// Packet: 0x09bb
packetLen(0x09bb, 6)

// Packet: 0x09bc
packetLen(0x09bc, 6)

// Packet: 0x09bd
packetLen(0x09bd, 2)

// Packet: 0x09be
packetLen(0x09be, 2)

// Packet: 0x09bf
packetLen(0x09bf, 4)

// Packet: 0x09c1
packetLen(0x09c1, 10)

// Packet: 0x09c2
packetLen(0x09c2, -1)

// Packet: 0x09c3
#if PACKETVER >= 20181114
packetLen(0x09c3, 10)
#elif PACKETVER >= 20180103
packetLen(0x09c3, 8)
#endif

// Packet: 0x09c4
#if PACKETVER >= 20181114
packetLen(0x09c4, 10)
#elif PACKETVER >= 20180103
packetLen(0x09c4, 8)
#endif

// Packet: 0x09c5
packetLen(0x09c5, 1042)

// Packet: 0x09c6
packetLen(0x09c6, -1)

// Packet: 0x09c7
packetLen(0x09c7, 18)

// Packet: 0x09c8
packetLen(0x09c8, -1)

// Packet: 0x09c9
packetLen(0x09c9, -1)

// Packet: 0x09ca
packetLen(0x09ca, -1)

// Packet: 0x09cb
packetLen(0x09cb, 17)

// Packet: 0x09cc
packetLen(0x09cc, -1)

// Packet: 0x09cd
packetLen(0x09cd, 8)

// Packet: 0x09ce
packetLen(0x09ce, 102)

// Packet: 0x09cf
packetLen(0x09cf, -1)

// Packet: 0x09d0
packetLen(0x09d0, -1)

// Packet: 0x09d1
packetLen(0x09d1, 14)

// Packet: 0x09d2
packetLen(0x09d2, -1)

// Packet: 0x09d3
packetLen(0x09d3, -1)

// Packet: 0x09d4
packetLen(0x09d4, 2)

// Packet: 0x09d5
packetLen(0x09d5, -1)

// Packet: 0x09d6
packetLen(0x09d6, -1)

// Packet: 0x09d7
packetLen(0x09d7, -1)

// Packet: 0x09d8
packetLen(0x09d8, 2)

// Packet: 0x09d9
packetLen(0x09d9, 4)

// Packet: 0x09da
packetLen(0x09da, -1)

// Packet: 0x09db
packetLen(0x09db, -1)

// Packet: 0x09dc
packetLen(0x09dc, -1)

// Packet: 0x09dd
packetLen(0x09dd, -1)

// Packet: 0x09de
packetLen(0x09de, -1)

// Packet: 0x09df
packetLen(0x09df, 7)

// Packet: 0x09e0
packetLen(0x09e0, -1)

// Packet: 0x09e1
packetLen(0x09e1, 8)

// Packet: 0x09e2
packetLen(0x09e2, 8)

// Packet: 0x09e3
packetLen(0x09e3, 8)

// Packet: 0x09e4
packetLen(0x09e4, 8)

// Packet: 0x09e5
packetLen(0x09e5, 18)

// Packet: 0x09e6
#if PACKETVER >= 20181114
packetLen(0x09e6, 24)
#elif PACKETVER >= 20180103
packetLen(0x09e6, 22)
#endif

// Packet: 0x09e7
packetLen(0x09e7, 3)

// Packet: 0x09e8
packetLen(0x09e8, 11)

// Packet: 0x09e9
packetLen(0x09e9, 2)

// Packet: 0x09ea
packetLen(0x09ea, 11)

// Packet: 0x09eb
packetLen(0x09eb, -1)

// Packet: 0x09ec
packetLen(0x09ec, -1)

// Packet: 0x09ed
packetLen(0x09ed, 3)

// Packet: 0x09ee
packetLen(0x09ee, 11)

// Packet: 0x09ef
packetLen(0x09ef, 11)

// Packet: 0x09f0
packetLen(0x09f0, -1)

// Packet: 0x09f1
packetLen(0x09f1, 11)

// Packet: 0x09f2
packetLen(0x09f2, 12)

// Packet: 0x09f3
packetLen(0x09f3, 11)

// Packet: 0x09f4
packetLen(0x09f4, 12)

// Packet: 0x09f5
packetLen(0x09f5, 11)

// Packet: 0x09f6
packetLen(0x09f6, 11)

// Packet: 0x09f7
#if PACKETVER >= 20181114
packetLen(0x09f7, 77)
#elif PACKETVER >= 20180103
packetLen(0x09f7, 75)
#endif

// Packet: 0x09f8
packetLen(0x09f8, -1)

// Packet: 0x09f9
packetLen(0x09f9, 143)

// Packet: 0x09fa
packetLen(0x09fa, -1)

// Packet: 0x09fb
packetLen(0x09fb, -1)

// Packet: 0x09fc
packetLen(0x09fc, 6)

// Packet: 0x09fd
packetLen(0x09fd, -1)

// Packet: 0x09fe
packetLen(0x09fe, -1)

// Packet: 0x09ff
packetLen(0x09ff, -1)

// Packet: 0x0a00
packetLen(0x0a00, 269)

// Packet: 0x0a01
packetLen(0x0a01, 3)

// Packet: 0x0a02
packetLen(0x0a02, 4)

// Packet: 0x0a03
packetLen(0x0a03, 2)

// Packet: 0x0a04
packetLen(0x0a04, 6)

// Packet: 0x0a05
#if PACKETVER >= 20181114
packetLen(0x0a05, 63)
#elif PACKETVER >= 20180103
packetLen(0x0a05, 53)
#endif

// Packet: 0x0a06
packetLen(0x0a06, 6)

// Packet: 0x0a07
packetLen(0x0a07, 9)

// Packet: 0x0a08
packetLen(0x0a08, 26)

// Packet: 0x0a09
#if PACKETVER >= 20181114
packetLen(0x0a09, 55)
#elif PACKETVER >= 20180103
packetLen(0x0a09, 45)
#endif

// Packet: 0x0a0a
#if PACKETVER >= 20181114
packetLen(0x0a0a, 57)
#elif PACKETVER >= 20180103
packetLen(0x0a0a, 47)
#endif

// Packet: 0x0a0b
#if PACKETVER >= 20181114
packetLen(0x0a0b, 57)
#elif PACKETVER >= 20180103
packetLen(0x0a0b, 47)
#endif

// Packet: 0x0a0c
#if PACKETVER >= 20181114
packetLen(0x0a0c, 66)
#elif PACKETVER >= 20180103
packetLen(0x0a0c, 56)
#endif

// Packet: 0x0a0d
packetLen(0x0a0d, -1)

// Packet: 0x0a0e
packetLen(0x0a0e, 14)

// Packet: 0x0a0f
packetLen(0x0a0f, -1)

// Packet: 0x0a10
packetLen(0x0a10, -1)

// Packet: 0x0a11
packetLen(0x0a11, -1)

// Packet: 0x0a12
packetLen(0x0a12, 27)

// Packet: 0x0a13
packetLen(0x0a13, 26)

// Packet: 0x0a14
packetLen(0x0a14, 10)

// Packet: 0x0a15
packetLen(0x0a15, 12)

// Packet: 0x0a16
packetLen(0x0a16, 26)

// Packet: 0x0a17
packetLen(0x0a17, 6)

// Packet: 0x0a18
packetLen(0x0a18, 14)

// Packet: 0x0a19
packetLen(0x0a19, 2)

// Packet: 0x0a1a
#if PACKETVER >= 20181114
packetLen(0x0a1a, 25)
#elif PACKETVER >= 20180103
packetLen(0x0a1a, 23)
#endif

// Packet: 0x0a1b
packetLen(0x0a1b, 2)

// Packet: 0x0a1c
packetLen(0x0a1c, -1)

// Packet: 0x0a1d
packetLen(0x0a1d, 2)

// Packet: 0x0a1e
packetLen(0x0a1e, 3)

// Packet: 0x0a1f
packetLen(0x0a1f, 2)

// Packet: 0x0a20
#if PACKETVER >= 20181114
packetLen(0x0a20, 23)
#elif PACKETVER >= 20180103
packetLen(0x0a20, 21)
#endif

// Packet: 0x0a21
packetLen(0x0a21, 3)

// Packet: 0x0a22
#if PACKETVER >= 20181114
packetLen(0x0a22, 7)
#elif PACKETVER >= 20180103
packetLen(0x0a22, 5)
#endif

// Packet: 0x0a23
packetLen(0x0a23, -1)

// Packet: 0x0a24
packetLen(0x0a24, 66)

// Packet: 0x0a25
packetLen(0x0a25, 6)

// Packet: 0x0a26
packetLen(0x0a26, 7)

// Packet: 0x0a27
packetLen(0x0a27, 8)

// Packet: 0x0a28
packetLen(0x0a28, 3)

// Packet: 0x0a29
packetLen(0x0a29, 6)

// Packet: 0x0a2a
packetLen(0x0a2a, 6)

// Packet: 0x0a2b
packetLen(0x0a2b, 14)

// Packet: 0x0a2c
packetLen(0x0a2c, 12)

// Packet: 0x0a2d
packetLen(0x0a2d, -1)

// Packet: 0x0a2e
packetLen(0x0a2e, 6)

// Packet: 0x0a2f
packetLen(0x0a2f, 7)

// Packet: 0x0a30
packetLen(0x0a30, 106)

// Packet: 0x0a31
packetLen(0x0a31, -1)

// Packet: 0x0a32
packetLen(0x0a32, 2)

// Packet: 0x0a33
packetLen(0x0a33, 7)

// Packet: 0x0a34
packetLen(0x0a34, 6)

// Packet: 0x0a35
packetLen(0x0a35, 4)

// Packet: 0x0a36
packetLen(0x0a36, 7)

// Packet: 0x0a37
#if PACKETVER >= 20181114
packetLen(0x0a37, 69)
#elif PACKETVER >= 20180103
packetLen(0x0a37, 59)
#endif

// Packet: 0x0a38
packetLen(0x0a38, 3)

// Packet: 0x0a39
packetLen(0x0a39, 36)

// Packet: 0x0a3a
packetLen(0x0a3a, 12)

// Packet: 0x0a3b
packetLen(0x0a3b, -1)

// Packet: 0x0a3c
packetLen(0x0a3c, -1)

// Packet: 0x0a3d
#if PACKETVER >= 20181114
packetLen(0x0a3d, 20)
#elif PACKETVER >= 20180103
packetLen(0x0a3d, 18)
#endif

// Packet: 0x0a3e
packetLen(0x0a3e, -1)

// Packet: 0x0a3f
#if PACKETVER >= 20181114
packetLen(0x0a3f, 11)
#elif PACKETVER >= 20180103
packetLen(0x0a3f, 9)
#endif

// Packet: 0x0a40
packetLen(0x0a40, 11)

// Packet: 0x0a41
packetLen(0x0a41, 18)

// Packet: 0x0a42
packetLen(0x0a42, 43)

// Packet: 0x0a43
packetLen(0x0a43, 85)

// Packet: 0x0a44
packetLen(0x0a44, -1)

// Packet: 0x0a46
packetLen(0x0a46, 14)

// Packet: 0x0a47
packetLen(0x0a47, 3)

// Packet: 0x0a48
packetLen(0x0a48, 2)

// Packet: 0x0a49
#if PACKETVER >= 20181114
packetLen(0x0a49, 22)
#elif PACKETVER >= 20180103
packetLen(0x0a49, 20)
#endif

// Packet: 0x0a4a
packetLen(0x0a4a, 6)

// Packet: 0x0a4b
packetLen(0x0a4b, 22)

// Packet: 0x0a4c
packetLen(0x0a4c, 28)

// Packet: 0x0a4d
packetLen(0x0a4d, -1)

// Packet: 0x0a4e
#if PACKETVER >= 20181114
packetLen(0x0a4e, 6)
#elif PACKETVER >= 20180103
packetLen(0x0a4e, 4)
#endif

// Packet: 0x0a4f
packetLen(0x0a4f, -1)

// Packet: 0x0a50
packetLen(0x0a50, 4)

// Packet: 0x0a51
packetLen(0x0a51, 34)

// Packet: 0x0a52
packetLen(0x0a52, 20)

// Packet: 0x0a53
packetLen(0x0a53, 10)

// Packet: 0x0a54
packetLen(0x0a54, -1)

// Packet: 0x0a55
packetLen(0x0a55, 2)

// Packet: 0x0a56
packetLen(0x0a56, 6)

// Packet: 0x0a57
packetLen(0x0a57, 6)

// Packet: 0x0a58
packetLen(0x0a58, 8)

// Packet: 0x0a59
packetLen(0x0a59, -1)

// Packet: 0x0a5a
packetLen(0x0a5a, 2)

// Packet: 0x0a5b
packetLen(0x0a5b, 7)

// Packet: 0x0a5c
packetLen(0x0a5c, 18)

// Packet: 0x0a5d
packetLen(0x0a5d, 6)

// Packet: 0x0a68
packetLen(0x0a68, 3)

// Packet: 0x0a69
packetLen(0x0a69, 6)

// Packet: 0x0a6a
packetLen(0x0a6a, 12)

// Packet: 0x0a6b
packetLen(0x0a6b, -1)

// Packet: 0x0a6c
packetLen(0x0a6c, 7)

// Packet: 0x0a6d
packetLen(0x0a6d, -1)

// Packet: 0x0a6e
packetLen(0x0a6e, -1)

// Packet: 0x0a6f
packetLen(0x0a6f, -1)

// Packet: 0x0a70
packetLen(0x0a70, 2)

// Packet: 0x0a71
packetLen(0x0a71, -1)

// Packet: 0x0a72
packetLen(0x0a72, 61)

// Packet: 0x0a73
packetLen(0x0a73, 2)

// Packet: 0x0a74
packetLen(0x0a74, 8)

// Packet: 0x0a76
packetLen(0x0a76, 80)

// Packet: 0x0a77
packetLen(0x0a77, 15)

// Packet: 0x0a78
packetLen(0x0a78, 15)

// Packet: 0x0a79
packetLen(0x0a79, -1)

// Packet: 0x0a7b
packetLen(0x0a7b, -1)

// Packet: 0x0a7c
packetLen(0x0a7c, -1)

// Packet: 0x0a7d
packetLen(0x0a7d, -1)

// Packet: 0x0a7e
packetLen(0x0a7e, -1)

// Packet: 0x0a7f
packetLen(0x0a7f, -1)

// Packet: 0x0a80
packetLen(0x0a80, 6)

// Packet: 0x0a81
packetLen(0x0a81, 4)

// Packet: 0x0a82
packetLen(0x0a82, 46)

// Packet: 0x0a83
packetLen(0x0a83, 46)

// Packet: 0x0a84
packetLen(0x0a84, 94)

// Packet: 0x0a85
packetLen(0x0a85, 82)

// Packet: 0x0a86
packetLen(0x0a86, -1)

// Packet: 0x0a87
packetLen(0x0a87, -1)

// Packet: 0x0a88
packetLen(0x0a88, 2)

// Packet: 0x0a89
#if PACKETVER >= 20181114
packetLen(0x0a89, 61)
#elif PACKETVER >= 20180103
packetLen(0x0a89, 57)
#endif

// Packet: 0x0a8a
packetLen(0x0a8a, 6)

// Packet: 0x0a8b
packetLen(0x0a8b, 2)

// Packet: 0x0a8c
packetLen(0x0a8c, 2)

// Packet: 0x0a8d
packetLen(0x0a8d, -1)

// Packet: 0x0a8e
packetLen(0x0a8e, 2)

// Packet: 0x0a8f
packetLen(0x0a8f, 2)

// Packet: 0x0a90
packetLen(0x0a90, 3)

// Packet: 0x0a91
packetLen(0x0a91, -1)

// Packet: 0x0a92
packetLen(0x0a92, -1)

// Packet: 0x0a93
packetLen(0x0a93, 3)

// Packet: 0x0a94
packetLen(0x0a94, 2)

// Packet: 0x0a95
packetLen(0x0a95, 4)

// Packet: 0x0a96
#if PACKETVER >= 20181114
packetLen(0x0a96, 61)
#elif PACKETVER >= 20180103
packetLen(0x0a96, 51)
#endif

// Packet: 0x0a97
packetLen(0x0a97, 8)

// Packet: 0x0a98
packetLen(0x0a98, 10)

// Packet: 0x0a99
packetLen(0x0a99, 4)

// Packet: 0x0a9a
packetLen(0x0a9a, 10)

// Packet: 0x0a9b
packetLen(0x0a9b, -1)

// Packet: 0x0a9c
packetLen(0x0a9c, 2)

// Packet: 0x0a9d
packetLen(0x0a9d, 4)

// Packet: 0x0a9e
packetLen(0x0a9e, 2)

// Packet: 0x0a9f
packetLen(0x0a9f, 2)

// Packet: 0x0aa0
packetLen(0x0aa0, 2)

// Packet: 0x0aa1
packetLen(0x0aa1, 4)

// Packet: 0x0aa2
packetLen(0x0aa2, -1)

// Packet: 0x0aa3
#if PACKETVER >= 20181114
packetLen(0x0aa3, 9)
#elif PACKETVER >= 20180103
packetLen(0x0aa3, 7)
#endif

// Packet: 0x0aa4
packetLen(0x0aa4, 2)

// Packet: 0x0aa5
packetLen(0x0aa5, -1)

// Packet: 0x0aa6
packetLen(0x0aa6, 36)

// Packet: 0x0aa7
packetLen(0x0aa7, 6)

// Packet: 0x0aa8
packetLen(0x0aa8, 5)

// Packet: 0x0aa9
packetLen(0x0aa9, -1)

// Packet: 0x0aaa
packetLen(0x0aaa, -1)

// Packet: 0x0aab
packetLen(0x0aab, -1)

// Packet: 0x0aac
packetLen(0x0aac, 69)

// Packet: 0x0aad
packetLen(0x0aad, 51)

// Packet: 0x0aae
packetLen(0x0aae, 2)

// Packet: 0x0aaf
packetLen(0x0aaf, 6)

// Packet: 0x0ab0
packetLen(0x0ab0, 6)

// Packet: 0x0ab1
packetLen(0x0ab1, 14)

// Packet: 0x0ab2
packetLen(0x0ab2, 7)

// Packet: 0x0ab3
packetLen(0x0ab3, 19)

// Packet: 0x0ab4
#if PACKETVER >= 20181114
packetLen(0x0ab4, 6)
#elif PACKETVER >= 20180103
packetLen(0x0ab4, 4)
#endif

// Packet: 0x0ab5
packetLen(0x0ab5, 2)

// Packet: 0x0ab6
#if PACKETVER >= 20181114
packetLen(0x0ab6, 8)
#elif PACKETVER >= 20180103
packetLen(0x0ab6, 6)
#endif

// Packet: 0x0ab7
packetLen(0x0ab7, 4)

// Packet: 0x0ab8
packetLen(0x0ab8, 2)

// Packet: 0x0ab9
#if PACKETVER >= 20181114
packetLen(0x0ab9, 47)
#elif PACKETVER >= 20180103
packetLen(0x0ab9, 39)
#endif

// Packet: 0x0aba
packetLen(0x0aba, 2)

// Packet: 0x0abb
packetLen(0x0abb, 2)

// Packet: 0x0abc
packetLen(0x0abc, -1)

// Packet: 0x0abd
packetLen(0x0abd, 10)

// Packet: 0x0abe
packetLen(0x0abe, -1)

// Packet: 0x0abf
packetLen(0x0abf, -1)

// Packet: 0x0ac0
packetLen(0x0ac0, 26)

// Packet: 0x0ac1
packetLen(0x0ac1, 26)

// Packet: 0x0ac2
packetLen(0x0ac2, -1)

// Packet: 0x0ac3
packetLen(0x0ac3, 2)

// Packet: 0x0ac4
packetLen(0x0ac4, -1)

// Packet: 0x0ac5
packetLen(0x0ac5, 156)

// Packet: 0x0ac6
packetLen(0x0ac6, 156)

// Packet: 0x0ac7
packetLen(0x0ac7, 156)

// Packet: 0x0ac8
packetLen(0x0ac8, 2)

// Packet: 0x0ac9
packetLen(0x0ac9, -1)

// Packet: 0x0aca
packetLen(0x0aca, 3)

// Packet: 0x0acb
packetLen(0x0acb, 12)

// Packet: 0x0acc
packetLen(0x0acc, 18)

// Packet: 0x0acd
packetLen(0x0acd, 23)

// Packet: 0x0ace
packetLen(0x0ace, 4)

// Packet: 0x0acf
packetLen(0x0acf, 68)

// Packet: 0x0ad0
packetLen(0x0ad0, 11)

// Packet: 0x0ad1
packetLen(0x0ad1, -1)

// Packet: 0x0ad2
packetLen(0x0ad2, 30)

// Packet: 0x0ad3
packetLen(0x0ad3, -1)

// Packet: 0x0ad4
packetLen(0x0ad4, -1)

// Packet: 0x0ad5
packetLen(0x0ad5, 2)

// Packet: 0x0ad6
packetLen(0x0ad6, 2)

// Packet: 0x0ad7
packetLen(0x0ad7, 8)

// Packet: 0x0ad8
packetLen(0x0ad8, 8)

// Packet: 0x0ad9
packetLen(0x0ad9, -1)

// Packet: 0x0ada
#if PACKETVER >= 20181114
packetLen(0x0ada, 32)
#elif PACKETVER >= 20180103
packetLen(0x0ada, 30)
#endif

// Packet: 0x0adb
packetLen(0x0adb, -1)

// Packet: 0x0adc
packetLen(0x0adc, 6)

// Packet: 0x0add
#if PACKETVER >= 20181114
packetLen(0x0add, 24)
#elif PACKETVER >= 20180103
packetLen(0x0add, 22)
#endif

// Packet: 0x0ade
packetLen(0x0ade, 6)

// Packet: 0x0adf
packetLen(0x0adf, 58)

// Packet: 0x0ae0
packetLen(0x0ae0, 30)

// Packet: 0x0ae1
packetLen(0x0ae1, 28)

// Packet: 0x0ae2
packetLen(0x0ae2, 7)

// Packet: 0x0ae3
packetLen(0x0ae3, -1)

// Packet: 0x0ae4
packetLen(0x0ae4, 89)

// Packet: 0x0ae5
packetLen(0x0ae5, -1)

// Packet: 0x0ae6
#if PACKETVER >= 20180131
packetLen(0x0ae6, 10)
#elif PACKETVER >= 20180103
packetLen(0x0ae6, 30)
#endif

// Packet: 0x0ae7
#if PACKETVER >= 20180328
packetLen(0x0ae7, 38)
#elif PACKETVER >= 20180103
packetLen(0x0ae7, 30)
#endif

// Packet: 0x0ae8
packetLen(0x0ae8, 2)

// Packet: 0x0ae9
#if PACKETVER >= 20180117
packetLen(0x0ae9, 13)
#elif PACKETVER >= 20180103
packetLen(0x0ae9, 64)
#endif

// Packet: 0x0aea
#if PACKETVER >= 20180117
// removed
#elif PACKETVER >= 20180103
packetLen(0x0aea, 2)
#endif

// Packet: 0x0aeb
#if PACKETVER >= 20180117
// removed
#elif PACKETVER >= 20180103
packetLen(0x0aeb, 11)
#endif

// Packet: 0x0aec
packetLen(0x0aec, 2)

// Packet: 0x0aed
packetLen(0x0aed, 2)

// Packet: 0x0aee
packetLen(0x0aee, 2)

// Packet: 0x0aef
#if PACKETVER >= 20180117
packetLen(0x0aef, 2)
#endif

// Packet: 0x0af0
#if PACKETVER >= 20180117
packetLen(0x0af0, 10)
#endif

// Packet: 0x0af2
#if PACKETVER >= 20180131
packetLen(0x0af2, 40)
#endif

// Packet: 0x0af3
#if PACKETVER >= 20180131
packetLen(0x0af3, -1)
#endif

// Packet: 0x0af4
#if PACKETVER >= 20180131
packetLen(0x0af4, 11)
#endif

// Packet: 0x0af5
#if PACKETVER >= 20180207
packetLen(0x0af5, 3)
#endif

// Packet: 0x0af6
#if PACKETVER >= 20180207
packetLen(0x0af6, 88)
#endif

// Packet: 0x0af7
#if PACKETVER >= 20180207
packetLen(0x0af7, 32)
#endif

// Packet: 0x0af8
#if PACKETVER >= 20180328
packetLen(0x0af8, 11)
#endif

// Packet: 0x0af9
#if PACKETVER >= 20180328
packetLen(0x0af9, 6)
#endif

// Packet: 0x0afa
#if PACKETVER >= 20180328
packetLen(0x0afa, 54)
#endif

// Packet: 0x0afb
#if PACKETVER >= 20180425
packetLen(0x0afb, -1)
#endif

// Packet: 0x0afc
#if PACKETVER >= 20180523
packetLen(0x0afc, 16)
#endif

// Packet: 0x0afd
#if PACKETVER >= 20180605
packetLen(0x0afd, -1)
#endif

// Packet: 0x0afe
#if PACKETVER >= 20180605
packetLen(0x0afe, -1)
#endif

// Packet: 0x0aff
#if PACKETVER >= 20180605
packetLen(0x0aff, -1)
#endif

// Packet: 0x0b00
#if PACKETVER >= 20180627
packetLen(0x0b00, 8)
#endif

// Packet: 0x0b01
#if PACKETVER >= 20180627
packetLen(0x0b01, 56)
#endif

// Packet: 0x0b02
#if PACKETVER >= 20180627
packetLen(0x0b02, 26)
#endif

// Packet: 0x0b03
#if PACKETVER >= 20180725
packetLen(0x0b03, -1)
#endif

// Packet: 0x0b04
#if PACKETVER >= 20180808
packetLen(0x0b04, 80)
#endif

// Packet: 0x0b05
#if PACKETVER >= 20181114
packetLen(0x0b05, 63)
#elif PACKETVER >= 20180822
packetLen(0x0b05, 59)
#endif

// Packet: 0x0b06
#if PACKETVER >= 20181010
// removed
#elif PACKETVER >= 20180822
packetLen(0x0b06, 53)
#endif

// Packet: 0x0b07
#if PACKETVER >= 20180822
packetLen(0x0b07, -1)
#endif

// Packet: 0x0b08
#if PACKETVER >= 20180919
packetLen(0x0b08, -1)
#elif PACKETVER >= 20180905
packetLen(0x0b08, 27)
#elif PACKETVER >= 20180822
packetLen(0x0b08, 26)
#endif

// Packet: 0x0b09
#if PACKETVER >= 20180822
packetLen(0x0b09, -1)
#endif

// Packet: 0x0b0a
#if PACKETVER >= 20180822
packetLen(0x0b0a, -1)
#endif

// Packet: 0x0b0b
#if PACKETVER >= 20180905
packetLen(0x0b0b, 4)
#elif PACKETVER >= 20180822
packetLen(0x0b0b, 3)
#endif

// Packet: 0x0b0c
#if PACKETVER >= 20180822
packetLen(0x0b0c, 155)
#endif

// Packet: 0x0b0d
#if PACKETVER >= 20180919
packetLen(0x0b0d, 10)
#elif PACKETVER >= 20180905
packetLen(0x0b0d, 6)
#endif

// Packet: 0x0b0e
#if PACKETVER >= 20180919
packetLen(0x0b0e, -1)
#endif

// Packet: 0x0b0f
#if PACKETVER >= 20180919
packetLen(0x0b0f, -1)
#endif

// Packet: 0x0b10
#if PACKETVER >= 20181010
packetLen(0x0b10, 10)
#endif

// Packet: 0x0b11
#if PACKETVER >= 20181010
packetLen(0x0b11, 4)
#endif

// Packet: 0x0b12
#if PACKETVER >= 20181024
packetLen(0x0b12, 2)
#endif

// Packet: 0x0b13
#if PACKETVER >= 20181114
packetLen(0x0b13, 48)
#elif PACKETVER >= 20181024
packetLen(0x0b13, 40)
#endif

// Packet: 0x0b14
#if PACKETVER >= 20181114
packetLen(0x0b14, 2)
#endif

// Packet: 0x0b15
#if PACKETVER >= 20181114
packetLen(0x0b15, 7)
#endif

// Packet: 0x0b16
#if PACKETVER >= 20181114
packetLen(0x0b16, 2)
#endif

// Packet: 0x0b17
#if PACKETVER >= 20181114
packetLen(0x0b17, 3)
#endif

// Packet: 0x0b18
#if PACKETVER >= 20181114
packetLen(0x0b18, 4)
#endif

// Packet: 0x0b19
#if PACKETVER >= 20181114
packetLen(0x0b19, 2)
#endif

// Packet: 0x0b1a
#if PACKETVER >= 20181212
packetLen(0x0b1a, 29)
#endif


#endif /* COMMON_PACKETS2018_LEN_ZERO_H */
