/**
 * This file is part of Hercules.
 * http://herc.ws - http://github.com/HerculesWS/Hercules
 *
 * Copyright (C) 2018-2026 Hercules Dev Team
 * Copyright (C) 2018-2022 Andrei Karas (4144)
 *
 * Hercules is free software: you can redistribute it and/or modify
 * it under the terms of the GNU General Public License as published by
 * the Free Software Foundation, either version 3 of the License, or
 * (at your option) any later version.
 *
 * This program is distributed in the hope that it will be useful,
 * but WITHOUT ANY WARRANTY; without even the implied warranty of
 * MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
 * GNU General Public License for more details.
 *
 * You should have received a copy of the GNU General Public License
 * along with this program.  If not, see <http://www.gnu.org/licenses/>.
 */

#ifndef COMMON_PACKETS2009_LEN_RE_H
#define COMMON_PACKETS2009_LEN_RE_H

/* This file is autogenerated, please do not commit manual changes */

// Packet: 0x0064
packetLen(0x0064, 55)

// Packet: 0x0065
packetLen(0x0065, 17)

// Packet: 0x0066
packetLen(0x0066, 3)

// Packet: 0x0067
packetLen(0x0067, 37)

// Packet: 0x0068
packetLen(0x0068, 46)

// Packet: 0x0069
packetLen(0x0069, -1)

// Packet: 0x006a
packetLen(0x006A, 23)

// Packet: 0x006b
packetLen(0x006B, -1)

// Packet: 0x006c
packetLen(0x006C, 3)

// Packet: 0x006d
packetLen(0x006D, 114)

// Packet: 0x006e
packetLen(0x006E, 3)

// Packet: 0x006f
packetLen(0x006F, 2)

// Packet: 0x0070
packetLen(0x0070, 3)

// Packet: 0x0071
packetLen(0x0071, 28)

// Packet: 0x0072
#if PACKETVER >= 20090617
packetLen(0x0072, 25)
// ignored packet from 2009-06-17cRagexeRE
#elif PACKETVER >= 20090107
packetLen(0x0072, 22)
#endif

// Packet: 0x0073
packetLen(0x0073, 11)

// Packet: 0x0074
packetLen(0x0074, 3)

// Packet: 0x0075
packetLen(0x0075, -1)

// Packet: 0x0076
packetLen(0x0076, 9)

// Packet: 0x0077
packetLen(0x0077, 5)

// Packet: 0x0078
packetLen(0x0078, 55)

// Packet: 0x0079
packetLen(0x0079, 53)

// Packet: 0x007a
packetLen(0x007A, 58)

// Packet: 0x007b
packetLen(0x007B, 60)

// Packet: 0x007c
packetLen(0x007C, 44)

// Packet: 0x007d
packetLen(0x007D, 2)

// Packet: 0x007e
#if PACKETVER >= 20090617
packetLen(0x007E, 105)
// ignored packet from 2009-06-17bRagexeRE
#elif PACKETVER >= 20090107
packetLen(0x007E, 105)
#endif

// Packet: 0x007f
packetLen(0x007F, 6)

// Packet: 0x0080
packetLen(0x0080, 7)

// Packet: 0x0081
packetLen(0x0081, 3)

// Packet: 0x0082
packetLen(0x0082, 2)

// Packet: 0x0083
packetLen(0x0083, 2)

// Packet: 0x0084
packetLen(0x0084, 2)

// Packet: 0x0085
#if PACKETVER >= 20090617
packetLen(0x0085, 11)
// ignored packet from 2009-06-17cRagexeRE
#elif PACKETVER >= 20090107
packetLen(0x0085, 10)
#endif

// Packet: 0x0086
packetLen(0x0086, 16)

// Packet: 0x0087
packetLen(0x0087, 12)

// Packet: 0x0088
packetLen(0x0088, 10)

// Packet: 0x0089
#if PACKETVER >= 20090617
packetLen(0x0089, 11)
// ignored packet from 2009-06-17bRagexeRE
#elif PACKETVER >= 20090107
packetLen(0x0089, 11)
#endif

// Packet: 0x008a
packetLen(0x008A, 29)

// Packet: 0x008b
packetLen(0x008B, 23)

// Packet: 0x008c
#if PACKETVER >= 20090617
packetLen(0x008C, 14)
// ignored packet from 2009-06-17bRagexeRE
#elif PACKETVER >= 20090107
packetLen(0x008C, 14)
#endif

// Packet: 0x008d
packetLen(0x008D, -1)

// Packet: 0x008e
packetLen(0x008E, -1)

// Packet: 0x0090
packetLen(0x0090, 7)

// Packet: 0x0091
packetLen(0x0091, 22)

// Packet: 0x0092
packetLen(0x0092, 28)

// Packet: 0x0093
packetLen(0x0093, 2)

// Packet: 0x0094
#if PACKETVER >= 20090617
packetLen(0x0094, 19)
// ignored packet from 2009-06-17bRagexeRE
#elif PACKETVER >= 20090107
packetLen(0x0094, 19)
#endif

// Packet: 0x0095
packetLen(0x0095, 30)

// Packet: 0x0096
packetLen(0x0096, -1)

// Packet: 0x0097
packetLen(0x0097, -1)

// Packet: 0x0098
packetLen(0x0098, 3)

// Packet: 0x0099
packetLen(0x0099, -1)

// Packet: 0x009a
packetLen(0x009A, -1)

// Packet: 0x009b
#if PACKETVER >= 20090617
packetLen(0x009B, 34)
// ignored packet from 2009-06-17bRagexeRE
#elif PACKETVER >= 20090107
packetLen(0x009B, 34)
#endif

// Packet: 0x009c
packetLen(0x009C, 9)

// Packet: 0x009d
packetLen(0x009D, 17)

// Packet: 0x009e
packetLen(0x009E, 17)

// Packet: 0x009f
#if PACKETVER >= 20090617
packetLen(0x009F, 20)
// ignored packet from 2009-06-17bRagexeRE
#elif PACKETVER >= 20090107
packetLen(0x009F, 20)
#endif

// Packet: 0x00a0
packetLen(0x00A0, 23)

// Packet: 0x00a1
packetLen(0x00A1, 6)

// Packet: 0x00a2
#if PACKETVER >= 20090617
packetLen(0x00A2, 15)
// ignored packet from 2009-06-17cRagexeRE
#elif PACKETVER >= 20090107
packetLen(0x00A2, 14)
#endif

// Packet: 0x00a3
packetLen(0x00A3, -1)

// Packet: 0x00a4
packetLen(0x00A4, -1)

// Packet: 0x00a5
packetLen(0x00A5, -1)

// Packet: 0x00a6
packetLen(0x00A6, -1)

// Packet: 0x00a7
#if PACKETVER >= 20090617
packetLen(0x00A7, 9)
// ignored packet from 2009-06-17bRagexeRE
#elif PACKETVER >= 20090107
packetLen(0x00A7, 9)
#endif

// Packet: 0x00a8
packetLen(0x00A8, 7)

// Packet: 0x00a9
packetLen(0x00A9, 6)

// Packet: 0x00aa
packetLen(0x00AA, 7)

// Packet: 0x00ab
packetLen(0x00AB, 4)

// Packet: 0x00ac
packetLen(0x00AC, 7)

// Packet: 0x00ae
packetLen(0x00AE, -1)

// Packet: 0x00af
packetLen(0x00AF, 6)

// Packet: 0x00b0
packetLen(0x00B0, 8)

// Packet: 0x00b1
packetLen(0x00B1, 8)

// Packet: 0x00b2
packetLen(0x00B2, 3)

// Packet: 0x00b3
packetLen(0x00B3, 3)

// Packet: 0x00b4
packetLen(0x00B4, -1)

// Packet: 0x00b5
packetLen(0x00B5, 6)

// Packet: 0x00b6
packetLen(0x00B6, 6)

// Packet: 0x00b7
packetLen(0x00B7, -1)

// Packet: 0x00b8
packetLen(0x00B8, 7)

// Packet: 0x00b9
packetLen(0x00B9, 6)

// Packet: 0x00ba
packetLen(0x00BA, 2)

// Packet: 0x00bb
packetLen(0x00BB, 5)

// Packet: 0x00bc
packetLen(0x00BC, 6)

// Packet: 0x00bd
packetLen(0x00BD, 44)

// Packet: 0x00be
packetLen(0x00BE, 5)

// Packet: 0x00bf
packetLen(0x00BF, 3)

// Packet: 0x00c0
packetLen(0x00C0, 7)

// Packet: 0x00c1
packetLen(0x00C1, 2)

// Packet: 0x00c2
packetLen(0x00C2, 6)

// Packet: 0x00c3
packetLen(0x00C3, 8)

// Packet: 0x00c4
packetLen(0x00C4, 6)

// Packet: 0x00c5
packetLen(0x00C5, 7)

// Packet: 0x00c6
packetLen(0x00C6, -1)

// Packet: 0x00c7
packetLen(0x00C7, -1)

// Packet: 0x00c8
packetLen(0x00C8, -1)

// Packet: 0x00c9
packetLen(0x00C9, -1)

// Packet: 0x00ca
packetLen(0x00CA, 3)

// Packet: 0x00cb
packetLen(0x00CB, 3)

// Packet: 0x00cc
packetLen(0x00CC, 6)

// Packet: 0x00cd
packetLen(0x00CD, 3)

// Packet: 0x00ce
packetLen(0x00CE, 2)

// Packet: 0x00cf
packetLen(0x00CF, 27)

// Packet: 0x00d0
packetLen(0x00D0, 3)

// Packet: 0x00d1
packetLen(0x00D1, 4)

// Packet: 0x00d2
packetLen(0x00D2, 4)

// Packet: 0x00d3
packetLen(0x00D3, 2)

// Packet: 0x00d4
packetLen(0x00D4, -1)

// Packet: 0x00d5
packetLen(0x00D5, -1)

// Packet: 0x00d6
packetLen(0x00D6, 3)

// Packet: 0x00d7
packetLen(0x00D7, -1)

// Packet: 0x00d8
packetLen(0x00D8, 6)

// Packet: 0x00d9
packetLen(0x00D9, 14)

// Packet: 0x00da
packetLen(0x00DA, 3)

// Packet: 0x00db
packetLen(0x00DB, -1)

// Packet: 0x00dc
packetLen(0x00DC, 28)

// Packet: 0x00dd
packetLen(0x00DD, 29)

// Packet: 0x00de
packetLen(0x00DE, -1)

// Packet: 0x00df
packetLen(0x00DF, -1)

// Packet: 0x00e0
packetLen(0x00E0, 30)

// Packet: 0x00e1
packetLen(0x00E1, 30)

// Packet: 0x00e2
packetLen(0x00E2, 26)

// Packet: 0x00e3
packetLen(0x00E3, 2)

// Packet: 0x00e4
packetLen(0x00E4, 6)

// Packet: 0x00e5
packetLen(0x00E5, 26)

// Packet: 0x00e6
packetLen(0x00E6, 3)

// Packet: 0x00e7
packetLen(0x00E7, 3)

// Packet: 0x00e8
packetLen(0x00E8, 8)

// Packet: 0x00e9
packetLen(0x00E9, 19)

// Packet: 0x00ea
packetLen(0x00EA, 5)

// Packet: 0x00eb
packetLen(0x00EB, 2)

// Packet: 0x00ec
packetLen(0x00EC, 3)

// Packet: 0x00ed
packetLen(0x00ED, 2)

// Packet: 0x00ee
packetLen(0x00EE, 2)

// Packet: 0x00ef
packetLen(0x00EF, 2)

// Packet: 0x00f0
packetLen(0x00F0, 3)

// Packet: 0x00f1
packetLen(0x00F1, 2)

// Packet: 0x00f2
packetLen(0x00F2, 6)

// Packet: 0x00f3
packetLen(0x00F3, -1)

// Packet: 0x00f4
packetLen(0x00F4, 21)

// Packet: 0x00f5
#if PACKETVER >= 20090617
packetLen(0x00F5, 11)
// ignored packet from 2009-06-17bRagexeRE
#elif PACKETVER >= 20090107
packetLen(0x00F5, 11)
#endif

// Packet: 0x00f6
packetLen(0x00F6, 8)

// Packet: 0x00f7
#if PACKETVER >= 20090617
packetLen(0x00F7, 22)
// ignored packet from 2009-06-17cRagexeRE
#elif PACKETVER >= 20090107
packetLen(0x00F7, 17)
#endif

// Packet: 0x00f8
packetLen(0x00F8, 2)

// Packet: 0x00f9
packetLen(0x00F9, 26)

// Packet: 0x00fa
packetLen(0x00FA, 3)

// Packet: 0x00fb
packetLen(0x00FB, -1)

// Packet: 0x00fc
packetLen(0x00FC, 6)

// Packet: 0x00fd
packetLen(0x00FD, 27)

// Packet: 0x00fe
packetLen(0x00FE, 30)

// Packet: 0x00ff
packetLen(0x00FF, 10)

// Packet: 0x0100
packetLen(0x0100, 2)

// Packet: 0x0101
packetLen(0x0101, 6)

// Packet: 0x0102
packetLen(0x0102, 6)

// Packet: 0x0103
packetLen(0x0103, 30)

// Packet: 0x0104
packetLen(0x0104, 79)

// Packet: 0x0105
packetLen(0x0105, 31)

// Packet: 0x0106
packetLen(0x0106, 10)

// Packet: 0x0107
packetLen(0x0107, 10)

// Packet: 0x0108
packetLen(0x0108, -1)

// Packet: 0x0109
packetLen(0x0109, -1)

// Packet: 0x010a
packetLen(0x010A, 4)

// Packet: 0x010b
packetLen(0x010B, 6)

// Packet: 0x010c
packetLen(0x010C, 6)

// Packet: 0x010d
packetLen(0x010D, 2)

// Packet: 0x010e
packetLen(0x010E, 11)

// Packet: 0x010f
packetLen(0x010F, -1)

// Packet: 0x0110
packetLen(0x0110, 10)

// Packet: 0x0111
packetLen(0x0111, 39)

// Packet: 0x0112
packetLen(0x0112, 4)

// Packet: 0x0113
#if PACKETVER >= 20090617
packetLen(0x0113, 25)
// ignored packet from 2009-06-17bRagexeRE
#elif PACKETVER >= 20090107
packetLen(0x0113, 25)
#endif

// Packet: 0x0114
packetLen(0x0114, 31)

// Packet: 0x0115
packetLen(0x0115, 35)

// Packet: 0x0116
#if PACKETVER >= 20090617
packetLen(0x0116, 17)
// ignored packet from 2009-06-17bRagexeRE
#elif PACKETVER >= 20090107
packetLen(0x0116, 17)
#endif

// Packet: 0x0117
packetLen(0x0117, 18)

// Packet: 0x0118
packetLen(0x0118, 2)

// Packet: 0x0119
packetLen(0x0119, 13)

// Packet: 0x011a
packetLen(0x011A, 15)

// Packet: 0x011b
packetLen(0x011B, 20)

// Packet: 0x011c
packetLen(0x011C, 68)

// Packet: 0x011d
packetLen(0x011D, 2)

// Packet: 0x011e
packetLen(0x011E, 3)

// Packet: 0x011f
packetLen(0x011F, 16)

// Packet: 0x0120
packetLen(0x0120, 6)

// Packet: 0x0121
packetLen(0x0121, 14)

// Packet: 0x0122
packetLen(0x0122, -1)

// Packet: 0x0123
packetLen(0x0123, -1)

// Packet: 0x0124
packetLen(0x0124, 21)

// Packet: 0x0125
packetLen(0x0125, 8)

// Packet: 0x0126
packetLen(0x0126, 8)

// Packet: 0x0127
packetLen(0x0127, 8)

// Packet: 0x0128
packetLen(0x0128, 8)

// Packet: 0x0129
packetLen(0x0129, 8)

// Packet: 0x012a
packetLen(0x012A, 2)

// Packet: 0x012b
packetLen(0x012B, 2)

// Packet: 0x012c
packetLen(0x012C, 3)

// Packet: 0x012d
packetLen(0x012D, 4)

// Packet: 0x012e
packetLen(0x012E, 2)

// Packet: 0x012f
packetLen(0x012F, -1)

// Packet: 0x0130
packetLen(0x0130, 6)

// Packet: 0x0131
packetLen(0x0131, 86)

// Packet: 0x0132
packetLen(0x0132, 6)

// Packet: 0x0133
packetLen(0x0133, -1)

// Packet: 0x0134
packetLen(0x0134, -1)

// Packet: 0x0135
packetLen(0x0135, 7)

// Packet: 0x0136
packetLen(0x0136, -1)

// Packet: 0x0137
packetLen(0x0137, 6)

// Packet: 0x0138
packetLen(0x0138, 3)

// Packet: 0x0139
packetLen(0x0139, 16)

// Packet: 0x013a
packetLen(0x013A, 4)

// Packet: 0x013b
packetLen(0x013B, 4)

// Packet: 0x013c
packetLen(0x013C, 4)

// Packet: 0x013d
packetLen(0x013D, 6)

// Packet: 0x013e
packetLen(0x013E, 24)

// Packet: 0x013f
packetLen(0x013F, 26)

// Packet: 0x0140
packetLen(0x0140, 22)

// Packet: 0x0141
packetLen(0x0141, 14)

// Packet: 0x0142
packetLen(0x0142, 6)

// Packet: 0x0143
packetLen(0x0143, 10)

// Packet: 0x0144
packetLen(0x0144, 23)

// Packet: 0x0145
packetLen(0x0145, 19)

// Packet: 0x0146
packetLen(0x0146, 6)

// Packet: 0x0147
packetLen(0x0147, 39)

// Packet: 0x0148
packetLen(0x0148, 8)

// Packet: 0x0149
packetLen(0x0149, 9)

// Packet: 0x014a
packetLen(0x014A, 6)

// Packet: 0x014b
packetLen(0x014B, 27)

// Packet: 0x014c
packetLen(0x014C, -1)

// Packet: 0x014d
packetLen(0x014D, 2)

// Packet: 0x014e
packetLen(0x014E, 6)

// Packet: 0x014f
packetLen(0x014F, 6)

// Packet: 0x0150
packetLen(0x0150, 110)

// Packet: 0x0151
packetLen(0x0151, 6)

// Packet: 0x0152
packetLen(0x0152, -1)

// Packet: 0x0153
packetLen(0x0153, -1)

// Packet: 0x0154
packetLen(0x0154, -1)

// Packet: 0x0155
packetLen(0x0155, -1)

// Packet: 0x0156
packetLen(0x0156, -1)

// Packet: 0x0157
packetLen(0x0157, 6)

// Packet: 0x0158
packetLen(0x0158, -1)

// Packet: 0x0159
packetLen(0x0159, 54)

// Packet: 0x015a
packetLen(0x015A, 66)

// Packet: 0x015b
packetLen(0x015B, 54)

// Packet: 0x015c
packetLen(0x015C, 90)

// Packet: 0x015d
packetLen(0x015D, 42)

// Packet: 0x015e
packetLen(0x015E, 6)

// Packet: 0x015f
packetLen(0x015F, 42)

// Packet: 0x0160
packetLen(0x0160, -1)

// Packet: 0x0161
packetLen(0x0161, -1)

// Packet: 0x0162
packetLen(0x0162, -1)

// Packet: 0x0163
packetLen(0x0163, -1)

// Packet: 0x0164
packetLen(0x0164, -1)

// Packet: 0x0165
packetLen(0x0165, 30)

// Packet: 0x0166
packetLen(0x0166, -1)

// Packet: 0x0167
packetLen(0x0167, 3)

// Packet: 0x0168
packetLen(0x0168, 14)

// Packet: 0x0169
packetLen(0x0169, 3)

// Packet: 0x016a
packetLen(0x016A, 30)

// Packet: 0x016b
packetLen(0x016B, 10)

// Packet: 0x016c
packetLen(0x016C, 43)

// Packet: 0x016d
packetLen(0x016D, 14)

// Packet: 0x016e
packetLen(0x016E, 186)

// Packet: 0x016f
packetLen(0x016F, 182)

// Packet: 0x0170
packetLen(0x0170, 14)

// Packet: 0x0171
packetLen(0x0171, 30)

// Packet: 0x0172
packetLen(0x0172, 10)

// Packet: 0x0173
packetLen(0x0173, 3)

// Packet: 0x0174
packetLen(0x0174, -1)

// Packet: 0x0175
packetLen(0x0175, 6)

// Packet: 0x0176
packetLen(0x0176, 106)

// Packet: 0x0177
packetLen(0x0177, -1)

// Packet: 0x0178
packetLen(0x0178, 4)

// Packet: 0x0179
packetLen(0x0179, 5)

// Packet: 0x017a
packetLen(0x017A, 4)

// Packet: 0x017b
packetLen(0x017B, -1)

// Packet: 0x017c
packetLen(0x017C, 6)

// Packet: 0x017d
packetLen(0x017D, 7)

// Packet: 0x017e
packetLen(0x017E, -1)

// Packet: 0x017f
packetLen(0x017F, -1)

// Packet: 0x0180
packetLen(0x0180, 6)

// Packet: 0x0181
packetLen(0x0181, 3)

// Packet: 0x0182
packetLen(0x0182, 106)

// Packet: 0x0183
packetLen(0x0183, 10)

// Packet: 0x0184
packetLen(0x0184, 10)

// Packet: 0x0185
packetLen(0x0185, 34)

// Packet: 0x0187
packetLen(0x0187, 6)

// Packet: 0x0188
packetLen(0x0188, 8)

// Packet: 0x0189
packetLen(0x0189, 4)

// Packet: 0x018a
packetLen(0x018A, 4)

// Packet: 0x018b
packetLen(0x018B, 4)

// Packet: 0x018c
packetLen(0x018C, 29)

// Packet: 0x018d
packetLen(0x018D, -1)

// Packet: 0x018e
packetLen(0x018E, 10)

// Packet: 0x018f
packetLen(0x018F, 6)

// Packet: 0x0190
#if PACKETVER >= 20090617
packetLen(0x0190, 23)
// ignored packet from 2009-06-17bRagexeRE
#elif PACKETVER >= 20090107
packetLen(0x0190, 23)
#endif

// Packet: 0x0191
packetLen(0x0191, 86)

// Packet: 0x0192
packetLen(0x0192, 24)

// Packet: 0x0193
packetLen(0x0193, 2)

// Packet: 0x0194
packetLen(0x0194, 30)

// Packet: 0x0195
packetLen(0x0195, 102)

// Packet: 0x0196
packetLen(0x0196, 9)

// Packet: 0x0197
packetLen(0x0197, 4)

// Packet: 0x0198
packetLen(0x0198, 8)

// Packet: 0x0199
packetLen(0x0199, 4)

// Packet: 0x019a
packetLen(0x019A, 14)

// Packet: 0x019b
packetLen(0x019B, 10)

// Packet: 0x019c
packetLen(0x019C, -1)

// Packet: 0x019d
packetLen(0x019D, 6)

// Packet: 0x019e
packetLen(0x019E, 2)

// Packet: 0x019f
packetLen(0x019F, 6)

// Packet: 0x01a0
packetLen(0x01A0, 3)

// Packet: 0x01a1
packetLen(0x01A1, 3)

// Packet: 0x01a2
packetLen(0x01A2, 37)

// Packet: 0x01a3
packetLen(0x01A3, 5)

// Packet: 0x01a4
packetLen(0x01A4, 11)

// Packet: 0x01a5
packetLen(0x01A5, 26)

// Packet: 0x01a6
packetLen(0x01A6, -1)

// Packet: 0x01a7
packetLen(0x01A7, 4)

// Packet: 0x01a8
packetLen(0x01A8, 4)

// Packet: 0x01a9
packetLen(0x01A9, 6)

// Packet: 0x01aa
packetLen(0x01AA, 10)

// Packet: 0x01ab
packetLen(0x01AB, 12)

// Packet: 0x01ac
packetLen(0x01AC, 6)

// Packet: 0x01ad
packetLen(0x01AD, -1)

// Packet: 0x01ae
packetLen(0x01AE, 4)

// Packet: 0x01af
packetLen(0x01AF, 4)

// Packet: 0x01b0
packetLen(0x01B0, 11)

// Packet: 0x01b1
packetLen(0x01B1, 7)

// Packet: 0x01b2
packetLen(0x01B2, -1)

// Packet: 0x01b3
packetLen(0x01B3, 67)

// Packet: 0x01b4
packetLen(0x01B4, 12)

// Packet: 0x01b5
packetLen(0x01B5, 18)

// Packet: 0x01b6
packetLen(0x01B6, 114)

// Packet: 0x01b7
packetLen(0x01B7, 6)

// Packet: 0x01b8
packetLen(0x01B8, 3)

// Packet: 0x01b9
packetLen(0x01B9, 6)

// Packet: 0x01ba
packetLen(0x01BA, 26)

// Packet: 0x01bb
packetLen(0x01BB, 26)

// Packet: 0x01bc
packetLen(0x01BC, 26)

// Packet: 0x01bd
packetLen(0x01BD, 26)

// Packet: 0x01be
packetLen(0x01BE, 2)

// Packet: 0x01bf
packetLen(0x01BF, 3)

// Packet: 0x01c0
packetLen(0x01C0, 2)

// Packet: 0x01c1
packetLen(0x01C1, 14)

// Packet: 0x01c2
packetLen(0x01C2, 10)

// Packet: 0x01c3
packetLen(0x01C3, -1)

// Packet: 0x01c4
packetLen(0x01C4, 22)

// Packet: 0x01c5
packetLen(0x01C5, 22)

// Packet: 0x01c6
packetLen(0x01C6, 4)

// Packet: 0x01c7
packetLen(0x01C7, 2)

// Packet: 0x01c8
packetLen(0x01C8, 13)

// Packet: 0x01c9
packetLen(0x01C9, 97)

// Packet: 0x01ca
packetLen(0x01CA, 3)

// Packet: 0x01cb
packetLen(0x01CB, 9)

// Packet: 0x01cc
packetLen(0x01CC, 9)

// Packet: 0x01cd
packetLen(0x01CD, 30)

// Packet: 0x01ce
packetLen(0x01CE, 6)

// Packet: 0x01cf
packetLen(0x01CF, 28)

// Packet: 0x01d0
packetLen(0x01D0, 8)

// Packet: 0x01d1
packetLen(0x01D1, 14)

// Packet: 0x01d2
packetLen(0x01D2, 10)

// Packet: 0x01d3
packetLen(0x01D3, 35)

// Packet: 0x01d4
packetLen(0x01D4, 6)

// Packet: 0x01d5
packetLen(0x01D5, -1)

// Packet: 0x01d6
packetLen(0x01D6, 4)

// Packet: 0x01d7
packetLen(0x01D7, 11)

// Packet: 0x01d8
packetLen(0x01D8, 54)

// Packet: 0x01d9
packetLen(0x01D9, 53)

// Packet: 0x01da
packetLen(0x01DA, 60)

// Packet: 0x01db
packetLen(0x01DB, 2)

// Packet: 0x01dc
packetLen(0x01DC, -1)

// Packet: 0x01dd
packetLen(0x01DD, 47)

// Packet: 0x01de
packetLen(0x01DE, 33)

// Packet: 0x01df
packetLen(0x01DF, 6)

// Packet: 0x01e0
packetLen(0x01E0, 30)

// Packet: 0x01e1
packetLen(0x01E1, 8)

// Packet: 0x01e2
packetLen(0x01E2, 34)

// Packet: 0x01e3
packetLen(0x01E3, 14)

// Packet: 0x01e4
packetLen(0x01E4, 2)

// Packet: 0x01e5
packetLen(0x01E5, 6)

// Packet: 0x01e6
packetLen(0x01E6, 26)

// Packet: 0x01e7
packetLen(0x01E7, 2)

// Packet: 0x01e8
packetLen(0x01E8, 28)

// Packet: 0x01e9
packetLen(0x01E9, 81)

// Packet: 0x01ea
packetLen(0x01EA, 6)

// Packet: 0x01eb
packetLen(0x01EB, 10)

// Packet: 0x01ec
packetLen(0x01EC, 26)

// Packet: 0x01ed
packetLen(0x01ED, 2)

// Packet: 0x01ee
packetLen(0x01EE, -1)

// Packet: 0x01ef
packetLen(0x01EF, -1)

// Packet: 0x01f0
packetLen(0x01F0, -1)

// Packet: 0x01f1
packetLen(0x01F1, -1)

// Packet: 0x01f2
packetLen(0x01F2, 20)

// Packet: 0x01f3
packetLen(0x01F3, 10)

// Packet: 0x01f4
packetLen(0x01F4, 32)

// Packet: 0x01f5
packetLen(0x01F5, 9)

// Packet: 0x01f6
packetLen(0x01F6, 34)

// Packet: 0x01f7
packetLen(0x01F7, 14)

// Packet: 0x01f8
packetLen(0x01F8, 2)

// Packet: 0x01f9
packetLen(0x01F9, 6)

// Packet: 0x01fa
packetLen(0x01FA, 48)

// Packet: 0x01fb
packetLen(0x01FB, 56)

// Packet: 0x01fc
packetLen(0x01FC, -1)

// Packet: 0x01fd
packetLen(0x01FD, 15)

// Packet: 0x01fe
packetLen(0x01FE, 5)

// Packet: 0x01ff
packetLen(0x01FF, 10)

// Packet: 0x0200
packetLen(0x0200, 26)

// Packet: 0x0201
packetLen(0x0201, -1)

// Packet: 0x0202
packetLen(0x0202, 26)

// Packet: 0x0203
packetLen(0x0203, 10)

// Packet: 0x0204
packetLen(0x0204, 18)

// Packet: 0x0205
packetLen(0x0205, 26)

// Packet: 0x0206
packetLen(0x0206, 11)

// Packet: 0x0207
packetLen(0x0207, 34)

// Packet: 0x0208
packetLen(0x0208, 14)

// Packet: 0x0209
packetLen(0x0209, 36)

// Packet: 0x020a
packetLen(0x020A, 10)

// Packet: 0x020d
packetLen(0x020D, -1)

// Packet: 0x020e
packetLen(0x020E, 32)

// Packet: 0x020f
packetLen(0x020F, 10)

// Packet: 0x0210
packetLen(0x0210, 22)

// Packet: 0x0212
packetLen(0x0212, 26)

// Packet: 0x0213
packetLen(0x0213, 26)

// Packet: 0x0214
packetLen(0x0214, 42)

// Packet: 0x0215
packetLen(0x0215, 6)

// Packet: 0x0216
packetLen(0x0216, 6)

// Packet: 0x0217
packetLen(0x0217, 2)

// Packet: 0x0218
packetLen(0x0218, 2)

// Packet: 0x0219
packetLen(0x0219, 282)

// Packet: 0x021a
packetLen(0x021A, 282)

// Packet: 0x021b
packetLen(0x021B, 10)

// Packet: 0x021c
packetLen(0x021C, 10)

// Packet: 0x021d
packetLen(0x021D, 6)

// Packet: 0x021e
packetLen(0x021E, 6)

// Packet: 0x021f
packetLen(0x021F, 66)

// Packet: 0x0220
packetLen(0x0220, 10)

// Packet: 0x0221
packetLen(0x0221, -1)

// Packet: 0x0222
packetLen(0x0222, 6)

// Packet: 0x0223
packetLen(0x0223, 8)

// Packet: 0x0224
packetLen(0x0224, 10)

// Packet: 0x0225
packetLen(0x0225, 2)

// Packet: 0x0226
packetLen(0x0226, 282)

// Packet: 0x0227
packetLen(0x0227, 18)

// Packet: 0x0228
packetLen(0x0228, 18)

// Packet: 0x0229
packetLen(0x0229, 15)

// Packet: 0x022a
packetLen(0x022A, 58)

// Packet: 0x022b
packetLen(0x022B, 57)

// Packet: 0x022c
packetLen(0x022C, 65)

// Packet: 0x022d
packetLen(0x022D, 5)

// Packet: 0x022e
packetLen(0x022E, 71)

// Packet: 0x022f
packetLen(0x022F, 5)

// Packet: 0x0230
packetLen(0x0230, 12)

// Packet: 0x0231
packetLen(0x0231, 26)

// Packet: 0x0232
packetLen(0x0232, 9)

// Packet: 0x0233
packetLen(0x0233, 11)

// Packet: 0x0234
packetLen(0x0234, 6)

// Packet: 0x0235
packetLen(0x0235, -1)

// Packet: 0x0236
packetLen(0x0236, 10)

// Packet: 0x0237
packetLen(0x0237, 2)

// Packet: 0x0238
packetLen(0x0238, 282)

// Packet: 0x0239
packetLen(0x0239, 11)

// Packet: 0x023a
packetLen(0x023A, 4)

// Packet: 0x023b
packetLen(0x023B, 36)

// Packet: 0x023c
packetLen(0x023C, 6)

// Packet: 0x023d
packetLen(0x023D, 6)

// Packet: 0x023e
packetLen(0x023E, 8)

// Packet: 0x023f
packetLen(0x023F, 2)

// Packet: 0x0240
packetLen(0x0240, -1)

// Packet: 0x0241
packetLen(0x0241, 6)

// Packet: 0x0242
packetLen(0x0242, -1)

// Packet: 0x0243
packetLen(0x0243, 6)

// Packet: 0x0244
packetLen(0x0244, 6)

// Packet: 0x0245
packetLen(0x0245, 3)

// Packet: 0x0246
packetLen(0x0246, 4)

// Packet: 0x0247
packetLen(0x0247, 8)

// Packet: 0x0248
packetLen(0x0248, -1)

// Packet: 0x0249
packetLen(0x0249, 3)

// Packet: 0x024a
packetLen(0x024A, 70)

// Packet: 0x024b
packetLen(0x024B, 4)

// Packet: 0x024c
packetLen(0x024C, 8)

// Packet: 0x024d
packetLen(0x024D, 12)

// Packet: 0x024e
packetLen(0x024E, 6)

// Packet: 0x024f
packetLen(0x024F, 10)

// Packet: 0x0250
packetLen(0x0250, 3)

// Packet: 0x0251
packetLen(0x0251, 34)

// Packet: 0x0252
packetLen(0x0252, -1)

// Packet: 0x0253
packetLen(0x0253, 3)

// Packet: 0x0254
packetLen(0x0254, 3)

// Packet: 0x0255
packetLen(0x0255, 5)

// Packet: 0x0256
packetLen(0x0256, 5)

// Packet: 0x0257
packetLen(0x0257, 8)

// Packet: 0x0258
packetLen(0x0258, 2)

// Packet: 0x0259
packetLen(0x0259, 3)

// Packet: 0x025a
packetLen(0x025A, -1)

// Packet: 0x025b
packetLen(0x025B, 6)

// Packet: 0x025c
packetLen(0x025C, 4)

// Packet: 0x025d
packetLen(0x025D, 6)

// Packet: 0x025e
packetLen(0x025E, 4)

// Packet: 0x025f
packetLen(0x025F, 6)

// Packet: 0x0260
packetLen(0x0260, 6)

// Packet: 0x0261
packetLen(0x0261, 11)

// Packet: 0x0262
packetLen(0x0262, 11)

// Packet: 0x0263
packetLen(0x0263, 11)

// Packet: 0x0264
packetLen(0x0264, 20)

// Packet: 0x0265
packetLen(0x0265, 20)

// Packet: 0x0266
packetLen(0x0266, 30)

// Packet: 0x0267
packetLen(0x0267, 4)

// Packet: 0x0268
packetLen(0x0268, 4)

// Packet: 0x0269
packetLen(0x0269, 4)

// Packet: 0x026a
packetLen(0x026A, 4)

// Packet: 0x026b
packetLen(0x026B, 4)

// Packet: 0x026c
packetLen(0x026C, 4)

// Packet: 0x026d
packetLen(0x026D, 4)

// Packet: 0x026f
packetLen(0x026F, 2)

// Packet: 0x0270
packetLen(0x0270, 2)

// Packet: 0x0271
packetLen(0x0271, 40)

// Packet: 0x0272
packetLen(0x0272, 44)

// Packet: 0x0273
packetLen(0x0273, 30)

// Packet: 0x0274
packetLen(0x0274, 8)

// Packet: 0x0275
#if PACKETVER >= 20090701
packetLen(0x0275, 37)
#endif

// Packet: 0x0276
#if PACKETVER >= 20090701
packetLen(0x0276, -1)
#endif

// Packet: 0x0277
packetLen(0x0277, 84)

// Packet: 0x0278
packetLen(0x0278, 2)

// Packet: 0x0279
packetLen(0x0279, 2)

// Packet: 0x027a
packetLen(0x027A, -1)

// Packet: 0x027b
packetLen(0x027B, 14)

// Packet: 0x027c
packetLen(0x027C, 60)

// Packet: 0x027d
packetLen(0x027D, 62)

// Packet: 0x027e
packetLen(0x027E, -1)

// Packet: 0x027f
packetLen(0x027F, 8)

// Packet: 0x0280
packetLen(0x0280, 12)

// Packet: 0x0281
packetLen(0x0281, 4)

// Packet: 0x0282
packetLen(0x0282, 284)

// Packet: 0x0283
packetLen(0x0283, 6)

// Packet: 0x0284
packetLen(0x0284, 14)

// Packet: 0x0285
packetLen(0x0285, 6)

// Packet: 0x0286
packetLen(0x0286, 4)

// Packet: 0x0287
packetLen(0x0287, -1)

// Packet: 0x0288
packetLen(0x0288, 10)

// Packet: 0x0289
packetLen(0x0289, 12)

// Packet: 0x028a
packetLen(0x028A, 18)

// Packet: 0x028b
packetLen(0x028B, -1)

// Packet: 0x028c
packetLen(0x028C, 46)

// Packet: 0x028d
packetLen(0x028D, 34)

// Packet: 0x028e
packetLen(0x028E, 4)

// Packet: 0x028f
packetLen(0x028F, 6)

// Packet: 0x0290
packetLen(0x0290, 4)

// Packet: 0x0291
packetLen(0x0291, 4)

// Packet: 0x0292
packetLen(0x0292, 2)

// Packet: 0x0293
packetLen(0x0293, 70)

// Packet: 0x0294
packetLen(0x0294, 10)

// Packet: 0x0295
packetLen(0x0295, -1)

// Packet: 0x0296
packetLen(0x0296, -1)

// Packet: 0x0297
packetLen(0x0297, -1)

// Packet: 0x0298
packetLen(0x0298, 8)

// Packet: 0x0299
packetLen(0x0299, 6)

// Packet: 0x029a
packetLen(0x029A, 27)

// Packet: 0x029b
packetLen(0x029B, 80)

// Packet: 0x029c
packetLen(0x029C, 66)

// Packet: 0x029d
packetLen(0x029D, -1)

// Packet: 0x029e
packetLen(0x029E, 11)

// Packet: 0x029f
packetLen(0x029F, 3)

// Packet: 0x02a2
packetLen(0x02A2, 8)

// Packet: 0x02a5
packetLen(0x02A5, 8)

// Packet: 0x02a6
#if PACKETVER >= 20090722
// removed
#elif PACKETVER >= 20090408
packetLen(0x02A6, -1)
#elif PACKETVER >= 20090325
packetLen(0x02A6, 404)
#endif

// Packet: 0x02a7
#if PACKETVER >= 20090722
// removed
#elif PACKETVER >= 20090408
packetLen(0x02A7, -1)
#elif PACKETVER >= 20090325
packetLen(0x02A7, 404)
#endif

// Packet: 0x02aa
packetLen(0x02AA, 4)

// Packet: 0x02ab
packetLen(0x02AB, 36)

// Packet: 0x02ac
packetLen(0x02AC, 6)

// Packet: 0x02ad
packetLen(0x02AD, 8)

// Packet: 0x02b0
packetLen(0x02B0, 85)

// Packet: 0x02b1
packetLen(0x02B1, -1)

// Packet: 0x02b2
packetLen(0x02B2, -1)

// Packet: 0x02b3
packetLen(0x02B3, 107)

// Packet: 0x02b4
packetLen(0x02B4, 6)

// Packet: 0x02b5
packetLen(0x02B5, -1)

// Packet: 0x02b6
packetLen(0x02B6, 7)

// Packet: 0x02b7
packetLen(0x02B7, 7)

// Packet: 0x02b8
packetLen(0x02B8, 22)

// Packet: 0x02b9
packetLen(0x02B9, 191)

// Packet: 0x02ba
packetLen(0x02BA, 11)

// Packet: 0x02bb
packetLen(0x02BB, 8)

// Packet: 0x02bc
packetLen(0x02BC, 6)

// Packet: 0x02c1
packetLen(0x02C1, -1)

// Packet: 0x02c2
packetLen(0x02C2, -1)

// Packet: 0x02c4
packetLen(0x02C4, 26)

// Packet: 0x02c5
packetLen(0x02C5, 30)

// Packet: 0x02c6
packetLen(0x02C6, 30)

// Packet: 0x02c7
packetLen(0x02C7, 7)

// Packet: 0x02c8
packetLen(0x02C8, 3)

// Packet: 0x02c9
packetLen(0x02C9, 3)

// Packet: 0x02ca
packetLen(0x02CA, 3)

// Packet: 0x02cb
packetLen(0x02CB, 65)

// Packet: 0x02cc
packetLen(0x02CC, 4)

// Packet: 0x02cd
packetLen(0x02CD, 71)

// Packet: 0x02ce
packetLen(0x02CE, 10)

// Packet: 0x02cf
packetLen(0x02CF, 6)

// Packet: 0x02d0
packetLen(0x02D0, -1)

// Packet: 0x02d1
packetLen(0x02D1, -1)

// Packet: 0x02d2
packetLen(0x02D2, -1)

// Packet: 0x02d3
packetLen(0x02D3, 4)

// Packet: 0x02d4
packetLen(0x02D4, 29)

// Packet: 0x02d5
packetLen(0x02D5, 2)

// Packet: 0x02d6
packetLen(0x02D6, 6)

// Packet: 0x02d7
packetLen(0x02D7, -1)

// Packet: 0x02d8
packetLen(0x02D8, 10)

// Packet: 0x02d9
packetLen(0x02D9, 10)

// Packet: 0x02da
packetLen(0x02DA, 3)

// Packet: 0x02db
packetLen(0x02DB, -1)

// Packet: 0x02dc
packetLen(0x02DC, -1)

// Packet: 0x02dd
packetLen(0x02DD, 32)

// Packet: 0x02de
packetLen(0x02DE, 6)

// Packet: 0x02df
packetLen(0x02DF, 36)

// Packet: 0x02e0
packetLen(0x02E0, 34)

// Packet: 0x02e1
packetLen(0x02E1, 33)

// Packet: 0x02e2
#if PACKETVER >= 20090617
packetLen(0x02E2, 20)
// ignored packet from 2009-06-17bRagexeRE
#elif PACKETVER >= 20090107
packetLen(0x02E2, 20)
#endif

// Packet: 0x02e3
#if PACKETVER >= 20090617
packetLen(0x02E3, 25)
// ignored packet from 2009-06-17cRagexeRE
#elif PACKETVER >= 20090107
packetLen(0x02E3, 22)
#endif

// Packet: 0x02e4
#if PACKETVER >= 20090617
packetLen(0x02E4, 11)
// ignored packet from 2009-06-17bRagexeRE
#elif PACKETVER >= 20090107
packetLen(0x02E4, 11)
#endif

// Packet: 0x02e5
#if PACKETVER >= 20090617
packetLen(0x02E5, 9)
// ignored packet from 2009-06-17bRagexeRE
#elif PACKETVER >= 20090107
packetLen(0x02E5, 9)
#endif

// Packet: 0x02e6
packetLen(0x02E6, 6)

// Packet: 0x02e7
packetLen(0x02E7, -1)

// Packet: 0x02e8
packetLen(0x02E8, -1)

// Packet: 0x02e9
packetLen(0x02E9, -1)

// Packet: 0x02ea
packetLen(0x02EA, -1)

// Packet: 0x02eb
packetLen(0x02EB, 13)

// Packet: 0x02ec
packetLen(0x02EC, 67)

// Packet: 0x02ed
packetLen(0x02ED, 59)

// Packet: 0x02ee
packetLen(0x02EE, 60)

// Packet: 0x02ef
packetLen(0x02EF, 8)

// Packet: 0x02f0
packetLen(0x02F0, 10)

// Packet: 0x02f1
packetLen(0x02F1, 2)

// Packet: 0x02f2
packetLen(0x02F2, 2)

// Packet: 0x02f3
packetLen(0x02F3, -1)

// Packet: 0x02f4
packetLen(0x02F4, -1)

// Packet: 0x02f5
packetLen(0x02F5, -1)

// Packet: 0x02f6
packetLen(0x02F6, -1)

// Packet: 0x02f7
packetLen(0x02F7, -1)

// Packet: 0x02f8
packetLen(0x02F8, -1)

// Packet: 0x02f9
packetLen(0x02F9, -1)

// Packet: 0x02fa
packetLen(0x02FA, -1)

// Packet: 0x02fb
packetLen(0x02FB, -1)

// Packet: 0x02fc
packetLen(0x02FC, -1)

// Packet: 0x02fd
packetLen(0x02FD, -1)

// Packet: 0x02fe
packetLen(0x02FE, -1)

// Packet: 0x02ff
packetLen(0x02FF, -1)

// Packet: 0x0300
packetLen(0x0300, -1)

// Packet: 0x0301
packetLen(0x0301, -1)

// Packet: 0x0302
packetLen(0x0302, -1)

// Packet: 0x0303
packetLen(0x0303, -1)

// Packet: 0x0304
packetLen(0x0304, -1)

// Packet: 0x0305
packetLen(0x0305, -1)

// Packet: 0x0306
packetLen(0x0306, -1)

// Packet: 0x0307
packetLen(0x0307, -1)

// Packet: 0x0308
packetLen(0x0308, -1)

// Packet: 0x0309
packetLen(0x0309, -1)

// Packet: 0x030a
packetLen(0x030A, -1)

// Packet: 0x030b
packetLen(0x030B, -1)

// Packet: 0x030c
packetLen(0x030C, -1)

// Packet: 0x030d
packetLen(0x030D, -1)

// Packet: 0x030e
packetLen(0x030E, -1)

// Packet: 0x030f
packetLen(0x030F, -1)

// Packet: 0x0310
packetLen(0x0310, -1)

// Packet: 0x0311
packetLen(0x0311, -1)

// Packet: 0x0312
packetLen(0x0312, -1)

// Packet: 0x0313
packetLen(0x0313, -1)

// Packet: 0x0314
packetLen(0x0314, -1)

// Packet: 0x0315
packetLen(0x0315, -1)

// Packet: 0x0316
packetLen(0x0316, -1)

// Packet: 0x0317
packetLen(0x0317, -1)

// Packet: 0x0318
packetLen(0x0318, -1)

// Packet: 0x0319
packetLen(0x0319, -1)

// Packet: 0x031a
packetLen(0x031A, -1)

// Packet: 0x031b
packetLen(0x031B, -1)

// Packet: 0x031c
packetLen(0x031C, -1)

// Packet: 0x031d
packetLen(0x031D, -1)

// Packet: 0x031e
packetLen(0x031E, -1)

// Packet: 0x031f
packetLen(0x031F, -1)

// Packet: 0x0320
packetLen(0x0320, -1)

// Packet: 0x0321
packetLen(0x0321, -1)

// Packet: 0x0322
packetLen(0x0322, -1)

// Packet: 0x0323
packetLen(0x0323, -1)

// Packet: 0x0324
packetLen(0x0324, -1)

// Packet: 0x0325
packetLen(0x0325, -1)

// Packet: 0x0326
packetLen(0x0326, -1)

// Packet: 0x0327
packetLen(0x0327, -1)

// Packet: 0x0328
packetLen(0x0328, -1)

// Packet: 0x0329
packetLen(0x0329, -1)

// Packet: 0x032a
packetLen(0x032A, -1)

// Packet: 0x032b
packetLen(0x032B, -1)

// Packet: 0x032c
packetLen(0x032C, -1)

// Packet: 0x032d
packetLen(0x032D, -1)

// Packet: 0x032e
packetLen(0x032E, -1)

// Packet: 0x032f
packetLen(0x032F, -1)

// Packet: 0x0330
packetLen(0x0330, -1)

// Packet: 0x0331
packetLen(0x0331, -1)

// Packet: 0x0332
packetLen(0x0332, -1)

// Packet: 0x0333
packetLen(0x0333, -1)

// Packet: 0x0334
packetLen(0x0334, -1)

// Packet: 0x0335
packetLen(0x0335, -1)

// Packet: 0x0336
packetLen(0x0336, -1)

// Packet: 0x0337
packetLen(0x0337, -1)

// Packet: 0x0338
packetLen(0x0338, -1)

// Packet: 0x0339
packetLen(0x0339, -1)

// Packet: 0x033a
packetLen(0x033A, -1)

// Packet: 0x033b
packetLen(0x033B, -1)

// Packet: 0x033c
packetLen(0x033C, -1)

// Packet: 0x033d
packetLen(0x033D, -1)

// Packet: 0x033e
packetLen(0x033E, -1)

// Packet: 0x033f
packetLen(0x033F, -1)

// Packet: 0x0340
packetLen(0x0340, -1)

// Packet: 0x0341
packetLen(0x0341, -1)

// Packet: 0x0342
packetLen(0x0342, -1)

// Packet: 0x0343
packetLen(0x0343, -1)

// Packet: 0x0344
packetLen(0x0344, -1)

// Packet: 0x0345
packetLen(0x0345, -1)

// Packet: 0x0346
packetLen(0x0346, -1)

// Packet: 0x0347
packetLen(0x0347, -1)

// Packet: 0x0348
packetLen(0x0348, -1)

// Packet: 0x0349
packetLen(0x0349, -1)

// Packet: 0x034a
packetLen(0x034A, -1)

// Packet: 0x034b
packetLen(0x034B, -1)

// Packet: 0x034c
packetLen(0x034C, -1)

// Packet: 0x034d
packetLen(0x034D, -1)

// Packet: 0x034e
packetLen(0x034E, -1)

// Packet: 0x034f
packetLen(0x034F, -1)

// Packet: 0x0350
packetLen(0x0350, -1)

// Packet: 0x0351
packetLen(0x0351, -1)

// Packet: 0x0352
packetLen(0x0352, -1)

// Packet: 0x0353
packetLen(0x0353, -1)

// Packet: 0x0354
packetLen(0x0354, -1)

// Packet: 0x0355
packetLen(0x0355, -1)

// Packet: 0x0356
packetLen(0x0356, -1)

// Packet: 0x0357
packetLen(0x0357, -1)

// Packet: 0x0358
packetLen(0x0358, -1)

// Packet: 0x0359
packetLen(0x0359, -1)

// Packet: 0x035a
packetLen(0x035A, -1)

// Packet: 0x035b
packetLen(0x035B, -1)

// Packet: 0x035c
packetLen(0x035C, 2)

// Packet: 0x035d
packetLen(0x035D, -1)

// Packet: 0x035e
packetLen(0x035E, 2)

// Packet: 0x035f
packetLen(0x035F, -1)

// Packet: 0x0360
packetLen(0x0360, -1)

// Packet: 0x0361
packetLen(0x0361, -1)

// Packet: 0x0362
packetLen(0x0362, -1)

// Packet: 0x0363
packetLen(0x0363, -1)

// Packet: 0x0364
packetLen(0x0364, -1)

// Packet: 0x0365
packetLen(0x0365, -1)

// Packet: 0x0366
packetLen(0x0366, -1)

// Packet: 0x0367
packetLen(0x0367, -1)

// Packet: 0x0368
packetLen(0x0368, -1)

// Packet: 0x0369
packetLen(0x0369, -1)

// Packet: 0x036a
packetLen(0x036A, -1)

// Packet: 0x036b
packetLen(0x036B, -1)

// Packet: 0x036c
packetLen(0x036C, -1)

// Packet: 0x036d
packetLen(0x036D, -1)

// Packet: 0x036e
packetLen(0x036E, -1)

// Packet: 0x036f
packetLen(0x036F, -1)

// Packet: 0x0370
packetLen(0x0370, -1)

// Packet: 0x0371
packetLen(0x0371, -1)

// Packet: 0x0372
packetLen(0x0372, -1)

// Packet: 0x0373
packetLen(0x0373, -1)

// Packet: 0x0374
packetLen(0x0374, -1)

// Packet: 0x0375
packetLen(0x0375, -1)

// Packet: 0x0376
packetLen(0x0376, -1)

// Packet: 0x0377
packetLen(0x0377, -1)

// Packet: 0x0378
packetLen(0x0378, -1)

// Packet: 0x0379
packetLen(0x0379, -1)

// Packet: 0x037a
packetLen(0x037A, -1)

// Packet: 0x037b
packetLen(0x037B, -1)

// Packet: 0x037c
packetLen(0x037C, -1)

// Packet: 0x037d
packetLen(0x037D, -1)

// Packet: 0x037e
packetLen(0x037E, -1)

// Packet: 0x037f
packetLen(0x037F, -1)

// Packet: 0x0380
packetLen(0x0380, -1)

// Packet: 0x0381
packetLen(0x0381, -1)

// Packet: 0x0382
packetLen(0x0382, -1)

// Packet: 0x0383
packetLen(0x0383, -1)

// Packet: 0x0384
packetLen(0x0384, -1)

// Packet: 0x0385
packetLen(0x0385, -1)

// Packet: 0x0386
packetLen(0x0386, -1)

// Packet: 0x0387
packetLen(0x0387, -1)

// Packet: 0x0388
packetLen(0x0388, -1)

// Packet: 0x0389
packetLen(0x0389, -1)

// Packet: 0x038a
packetLen(0x038A, -1)

// Packet: 0x038b
packetLen(0x038B, -1)

// Packet: 0x038c
packetLen(0x038C, -1)

// Packet: 0x038d
packetLen(0x038D, -1)

// Packet: 0x038e
packetLen(0x038E, -1)

// Packet: 0x038f
packetLen(0x038F, -1)

// Packet: 0x0390
packetLen(0x0390, -1)

// Packet: 0x0391
packetLen(0x0391, -1)

// Packet: 0x0392
packetLen(0x0392, -1)

// Packet: 0x0393
packetLen(0x0393, -1)

// Packet: 0x0394
packetLen(0x0394, -1)

// Packet: 0x0395
packetLen(0x0395, -1)

// Packet: 0x0396
packetLen(0x0396, -1)

// Packet: 0x0397
packetLen(0x0397, -1)

// Packet: 0x0398
packetLen(0x0398, -1)

// Packet: 0x0399
packetLen(0x0399, -1)

// Packet: 0x039a
packetLen(0x039A, -1)

// Packet: 0x039b
packetLen(0x039B, -1)

// Packet: 0x039c
packetLen(0x039C, -1)

// Packet: 0x039d
packetLen(0x039D, -1)

// Packet: 0x039e
packetLen(0x039E, -1)

// Packet: 0x039f
packetLen(0x039F, -1)

// Packet: 0x03a0
packetLen(0x03A0, -1)

// Packet: 0x03a1
packetLen(0x03A1, -1)

// Packet: 0x03a2
packetLen(0x03A2, -1)

// Packet: 0x03a3
packetLen(0x03A3, -1)

// Packet: 0x03a4
packetLen(0x03A4, -1)

// Packet: 0x03a5
packetLen(0x03A5, -1)

// Packet: 0x03a6
packetLen(0x03A6, -1)

// Packet: 0x03a7
packetLen(0x03A7, -1)

// Packet: 0x03a8
packetLen(0x03A8, -1)

// Packet: 0x03a9
packetLen(0x03A9, -1)

// Packet: 0x03aa
packetLen(0x03AA, -1)

// Packet: 0x03ab
packetLen(0x03AB, -1)

// Packet: 0x03ac
packetLen(0x03AC, -1)

// Packet: 0x03ad
packetLen(0x03AD, -1)

// Packet: 0x03ae
packetLen(0x03AE, -1)

// Packet: 0x03af
packetLen(0x03AF, -1)

// Packet: 0x03b0
packetLen(0x03B0, -1)

// Packet: 0x03b1
packetLen(0x03B1, -1)

// Packet: 0x03b2
packetLen(0x03B2, -1)

// Packet: 0x03b3
packetLen(0x03B3, -1)

// Packet: 0x03b4
packetLen(0x03B4, -1)

// Packet: 0x03b5
packetLen(0x03B5, -1)

// Packet: 0x03b6
packetLen(0x03B6, -1)

// Packet: 0x03b7
packetLen(0x03B7, -1)

// Packet: 0x03b8
packetLen(0x03B8, -1)

// Packet: 0x03b9
packetLen(0x03B9, -1)

// Packet: 0x03ba
packetLen(0x03BA, -1)

// Packet: 0x03bb
packetLen(0x03BB, -1)

// Packet: 0x03bc
packetLen(0x03BC, -1)

// Packet: 0x03bd
packetLen(0x03BD, -1)

// Packet: 0x03be
packetLen(0x03BE, -1)

// Packet: 0x03bf
packetLen(0x03BF, -1)

// Packet: 0x03c0
packetLen(0x03C0, -1)

// Packet: 0x03c1
packetLen(0x03C1, -1)

// Packet: 0x03c2
packetLen(0x03C2, -1)

// Packet: 0x03c3
packetLen(0x03C3, -1)

// Packet: 0x03c4
packetLen(0x03C4, -1)

// Packet: 0x03c5
packetLen(0x03C5, -1)

// Packet: 0x03c6
packetLen(0x03C6, -1)

// Packet: 0x03c7
packetLen(0x03C7, -1)

// Packet: 0x03c8
packetLen(0x03C8, -1)

// Packet: 0x03c9
packetLen(0x03C9, -1)

// Packet: 0x03ca
packetLen(0x03CA, -1)

// Packet: 0x03cb
packetLen(0x03CB, -1)

// Packet: 0x03cc
packetLen(0x03CC, -1)

// Packet: 0x03cd
packetLen(0x03CD, -1)

// Packet: 0x03ce
packetLen(0x03CE, -1)

// Packet: 0x03cf
packetLen(0x03CF, -1)

// Packet: 0x03d0
packetLen(0x03D0, -1)

// Packet: 0x03d1
packetLen(0x03D1, -1)

// Packet: 0x03d2
packetLen(0x03D2, -1)

// Packet: 0x03d3
packetLen(0x03D3, -1)

// Packet: 0x03d4
packetLen(0x03D4, -1)

// Packet: 0x03d5
packetLen(0x03D5, -1)

// Packet: 0x03d6
packetLen(0x03D6, -1)

// Packet: 0x03d7
packetLen(0x03D7, -1)

// Packet: 0x03d8
packetLen(0x03D8, -1)

// Packet: 0x03d9
packetLen(0x03D9, -1)

// Packet: 0x03da
packetLen(0x03DA, -1)

// Packet: 0x03db
packetLen(0x03DB, -1)

// Packet: 0x03dc
packetLen(0x03DC, -1)

// Packet: 0x03dd
packetLen(0x03DD, 18)

// Packet: 0x03de
packetLen(0x03DE, 18)

// Packet: 0x03e2
packetLen(0x03E2, -1)

// Packet: 0x03e3
packetLen(0x03E3, -1)

// Packet: 0x03e4
packetLen(0x03E4, -1)

// Packet: 0x03e5
packetLen(0x03E5, -1)

// Packet: 0x03e6
packetLen(0x03E6, -1)

// Packet: 0x03e7
packetLen(0x03E7, -1)

// Packet: 0x03e8
packetLen(0x03E8, -1)

// Packet: 0x03e9
packetLen(0x03E9, -1)

// Packet: 0x03ea
packetLen(0x03EA, -1)

// Packet: 0x03eb
packetLen(0x03EB, -1)

// Packet: 0x03ec
packetLen(0x03EC, -1)

// Packet: 0x03ed
packetLen(0x03ED, -1)

// Packet: 0x03ee
packetLen(0x03EE, -1)

// Packet: 0x03ef
packetLen(0x03EF, -1)

// Packet: 0x03f0
packetLen(0x03F0, -1)

// Packet: 0x03f1
packetLen(0x03F1, -1)

// Packet: 0x03f2
packetLen(0x03F2, -1)

// Packet: 0x03f3
packetLen(0x03F3, -1)

// Packet: 0x03f4
packetLen(0x03F4, -1)

// Packet: 0x03f5
packetLen(0x03F5, -1)

// Packet: 0x03f6
packetLen(0x03F6, -1)

// Packet: 0x03f7
packetLen(0x03F7, -1)

// Packet: 0x03f8
packetLen(0x03F8, -1)

// Packet: 0x03f9
packetLen(0x03F9, -1)

// Packet: 0x03fa
packetLen(0x03FA, -1)

// Packet: 0x03fb
packetLen(0x03FB, -1)

// Packet: 0x03fc
packetLen(0x03FC, -1)

// Packet: 0x03fd
packetLen(0x03FD, -1)

// Packet: 0x03fe
packetLen(0x03FE, -1)

// Packet: 0x03ff
packetLen(0x03FF, -1)

// Packet: 0x0400
packetLen(0x0400, -1)

// Packet: 0x0401
packetLen(0x0401, -1)

// Packet: 0x0402
packetLen(0x0402, -1)

// Packet: 0x0403
packetLen(0x0403, -1)

// Packet: 0x0404
packetLen(0x0404, -1)

// Packet: 0x0405
packetLen(0x0405, -1)

// Packet: 0x0406
packetLen(0x0406, -1)

// Packet: 0x0407
packetLen(0x0407, -1)

// Packet: 0x0408
packetLen(0x0408, -1)

// Packet: 0x0409
packetLen(0x0409, -1)

// Packet: 0x040a
packetLen(0x040A, -1)

// Packet: 0x040b
packetLen(0x040B, -1)

// Packet: 0x040c
packetLen(0x040C, -1)

// Packet: 0x040d
packetLen(0x040D, -1)

// Packet: 0x040e
packetLen(0x040E, -1)

// Packet: 0x040f
packetLen(0x040F, -1)

// Packet: 0x0410
packetLen(0x0410, -1)

// Packet: 0x0411
packetLen(0x0411, -1)

// Packet: 0x0412
packetLen(0x0412, -1)

// Packet: 0x0413
packetLen(0x0413, -1)

// Packet: 0x0414
packetLen(0x0414, -1)

// Packet: 0x0415
packetLen(0x0415, -1)

// Packet: 0x0416
packetLen(0x0416, -1)

// Packet: 0x0417
packetLen(0x0417, -1)

// Packet: 0x0418
packetLen(0x0418, -1)

// Packet: 0x0419
packetLen(0x0419, -1)

// Packet: 0x041a
packetLen(0x041A, -1)

// Packet: 0x041b
packetLen(0x041B, -1)

// Packet: 0x041c
packetLen(0x041C, -1)

// Packet: 0x041d
packetLen(0x041D, -1)

// Packet: 0x041e
packetLen(0x041E, -1)

// Packet: 0x041f
packetLen(0x041F, -1)

// Packet: 0x0420
packetLen(0x0420, -1)

// Packet: 0x0421
packetLen(0x0421, -1)

// Packet: 0x0422
packetLen(0x0422, -1)

// Packet: 0x0423
packetLen(0x0423, -1)

// Packet: 0x0424
packetLen(0x0424, -1)

// Packet: 0x0425
packetLen(0x0425, -1)

// Packet: 0x0426
packetLen(0x0426, -1)

// Packet: 0x0427
packetLen(0x0427, -1)

// Packet: 0x0428
packetLen(0x0428, -1)

// Packet: 0x0429
packetLen(0x0429, -1)

// Packet: 0x042a
packetLen(0x042A, -1)

// Packet: 0x042b
packetLen(0x042B, -1)

// Packet: 0x042c
packetLen(0x042C, -1)

// Packet: 0x042d
packetLen(0x042D, -1)

// Packet: 0x042e
packetLen(0x042E, -1)

// Packet: 0x042f
packetLen(0x042F, -1)

// Packet: 0x0430
packetLen(0x0430, -1)

// Packet: 0x0431
packetLen(0x0431, -1)

// Packet: 0x0432
packetLen(0x0432, -1)

// Packet: 0x0433
packetLen(0x0433, -1)

// Packet: 0x0434
packetLen(0x0434, -1)

// Packet: 0x0435
packetLen(0x0435, -1)

// Packet: 0x0436
packetLen(0x0436, 19)

// Packet: 0x0437
packetLen(0x0437, 7)

// Packet: 0x0438
packetLen(0x0438, 10)

// Packet: 0x0439
packetLen(0x0439, 8)

// Packet: 0x043d
packetLen(0x043D, 8)

// Packet: 0x043e
packetLen(0x043E, -1)

// Packet: 0x043f
#if PACKETVER >= 20090113
packetLen(0x043F, 25)
#elif PACKETVER >= 20090107
packetLen(0x043F, 8)
#endif

// Packet: 0x0440
packetLen(0x0440, 10)

// Packet: 0x0441
packetLen(0x0441, 4)

// Packet: 0x0442
packetLen(0x0442, 8)

// Packet: 0x0443
packetLen(0x0443, 8)

// Packet: 0x0444
#if PACKETVER >= 20090113
packetLen(0x0444, -1)
#endif

// Packet: 0x0445
#if PACKETVER >= 20090113
packetLen(0x0445, 10)
#endif

// Packet: 0x0446
#if PACKETVER >= 20090218
packetLen(0x0446, 14)
#endif

// Packet: 0x0447
#if PACKETVER >= 20090520
packetLen(0x0447, 2)
#endif

// Packet: 0x0448
#if PACKETVER >= 20090226
packetLen(0x0448, -1)
#endif

// Packet: 0x0449
#if PACKETVER >= 20090722
// removed
#elif PACKETVER >= 20090401
packetLen(0x0449, 4)
#endif

// Packet: 0x044a
#if PACKETVER >= 20090408
packetLen(0x044A, 6)
#endif

// Packet: 0x044b
#if PACKETVER >= 20090514
packetLen(0x044B, 2)
#endif

// Packet: 0x07d0
#if PACKETVER >= 20090520
packetLen(0x07D0, 6)
#endif

// Packet: 0x07d1
#if PACKETVER >= 20090520
packetLen(0x07D1, 2)
#endif

// Packet: 0x07d2
#if PACKETVER >= 20090520
packetLen(0x07D2, -1)
#endif

// Packet: 0x07d3
#if PACKETVER >= 20090520
packetLen(0x07D3, 4)
#endif

// Packet: 0x07d4
#if PACKETVER >= 20090520
packetLen(0x07D4, 4)
#endif

// Packet: 0x07d5
#if PACKETVER >= 20090520
packetLen(0x07D5, 4)
#endif

// Packet: 0x07d6
#if PACKETVER >= 20090520
packetLen(0x07D6, 4)
#endif

// Packet: 0x07d7
#if PACKETVER >= 20090603
packetLen(0x07D7, 8)
#endif

// Packet: 0x07d8
#if PACKETVER >= 20090603
packetLen(0x07D8, 8)
#endif

// Packet: 0x07d9
#if PACKETVER >= 20090617
packetLen(0x07D9, 268)
#elif PACKETVER >= 20090603
packetLen(0x07D9, 254)
#endif

// Packet: 0x07da
#if PACKETVER >= 20090603
packetLen(0x07DA, 6)
#endif

// Packet: 0x07db
#if PACKETVER >= 20090610
packetLen(0x07DB, 8)
#endif

// Packet: 0x07dc
#if PACKETVER >= 20090617
packetLen(0x07DC, 6)
#endif

// Packet: 0x07dd
#if PACKETVER >= 20090617
packetLen(0x07DD, 54)
#endif

// Packet: 0x07de
#if PACKETVER >= 20090617
packetLen(0x07DE, 30)
#endif

// Packet: 0x07df
#if PACKETVER >= 20090617
packetLen(0x07DF, 54)
#endif

// Packet: 0x07e0
#if PACKETVER >= 20090708
packetLen(0x07E0, 58)
#endif

// Packet: 0x07e1
#if PACKETVER >= 20090715
packetLen(0x07E1, 15)
#endif

// Packet: 0x07e2
#if PACKETVER >= 20090805
packetLen(0x07E2, 8)
#endif

// Packet: 0x07e3
#if PACKETVER >= 20090818
packetLen(0x07E3, 6)
#endif

// Packet: 0x07e4
#if PACKETVER >= 20090818
packetLen(0x07E4, -1)
#endif

// Packet: 0x07e5
#if PACKETVER >= 20090922
packetLen(0x07E5, 8)
#elif PACKETVER >= 20090825
packetLen(0x07E5, -1)
#endif

// Packet: 0x07e6
#if PACKETVER >= 20090818
packetLen(0x07E6, 8)
#endif

// Packet: 0x07e7
#if PACKETVER >= 20090922
packetLen(0x07E7, 32)
#elif PACKETVER >= 20090825
packetLen(0x07E7, 5)
#endif

// Packet: 0x07e8
#if PACKETVER >= 20090922
packetLen(0x07E8, -1)
#endif

// Packet: 0x07e9
#if PACKETVER >= 20090922
packetLen(0x07E9, 5)
#endif

// Packet: 0x07ea
#if PACKETVER >= 20090929
packetLen(0x07EA, 2)
#endif

// Packet: 0x07eb
#if PACKETVER >= 20090929
packetLen(0x07EB, -1)
#endif

// Packet: 0x07ec
#if PACKETVER >= 20091006
packetLen(0x07EC, 8)
#elif PACKETVER >= 20090929
packetLen(0x07EC, 6)
#endif

// Packet: 0x07ed
#if PACKETVER >= 20091006
packetLen(0x07ED, 10)
#elif PACKETVER >= 20090929
packetLen(0x07ED, 8)
#endif

// Packet: 0x07ee
#if PACKETVER >= 20090929
packetLen(0x07EE, 6)
#endif

// Packet: 0x07ef
#if PACKETVER >= 20090929
packetLen(0x07EF, 8)
#endif

// Packet: 0x07f0
#if PACKETVER >= 20090929
packetLen(0x07F0, 8)
#endif

// Packet: 0x07f1
#if PACKETVER >= 20090929
packetLen(0x07F1, 15)
#endif

// Packet: 0x07f2
#if PACKETVER >= 20091006
packetLen(0x07F2, 6)
#elif PACKETVER >= 20090929
packetLen(0x07F2, 4)
#endif

// Packet: 0x07f3
#if PACKETVER >= 20091006
packetLen(0x07F3, 4)
#elif PACKETVER >= 20090929
packetLen(0x07F3, 3)
#endif

// Packet: 0x07f4
#if PACKETVER >= 20091006
packetLen(0x07F4, 3)
#endif

// Packet: 0x07f5
#if PACKETVER >= 20091027
packetLen(0x07F5, 6)
#endif

// Packet: 0x07f6
#if PACKETVER >= 20091027
packetLen(0x07F6, 14)
#endif

// Packet: 0x07f7
#if PACKETVER >= 20091103
packetLen(0x07F7, -1)
#endif

// Packet: 0x07f8
#if PACKETVER >= 20091103
packetLen(0x07F8, -1)
#endif

// Packet: 0x07f9
#if PACKETVER >= 20091103
packetLen(0x07F9, -1)
#endif

// Packet: 0x07fa
#if PACKETVER >= 20091117
packetLen(0x07FA, 8)
#endif

// Packet: 0x07fb
#if PACKETVER >= 20091124
packetLen(0x07FB, 25)
#endif

// Packet: 0x07fc
#if PACKETVER >= 20091201
packetLen(0x07FC, 10)
#endif

// Packet: 0x07fd
#if PACKETVER >= 20091201
packetLen(0x07FD, -1)
#endif

// Packet: 0x07fe
#if PACKETVER >= 20091201
packetLen(0x07FE, 26)
#endif

// Packet: 0x07ff
#if PACKETVER >= 20091201
packetLen(0x07FF, -1)
#endif

// Packet: 0x0800
#if PACKETVER >= 20091215
packetLen(0x0800, -1)
#endif

// Packet: 0x0801
#if PACKETVER >= 20091215
packetLen(0x0801, -1)
#endif

// Packet: 0x0802
#if PACKETVER >= 20091222
packetLen(0x0802, 18)
#endif

// Packet: 0x0803
#if PACKETVER >= 20091222
packetLen(0x0803, 4)
#endif

// Packet: 0x0804
#if PACKETVER >= 20091229
packetLen(0x0804, 14)
#elif PACKETVER >= 20091222
packetLen(0x0804, 8)
#endif

// Packet: 0x0805
#if PACKETVER >= 20091222
packetLen(0x0805, -1)
#endif

// Packet: 0x0806
#if PACKETVER >= 20091229
packetLen(0x0806, 2)
#elif PACKETVER >= 20091222
packetLen(0x0806, 4)
#endif

// Packet: 0x0807
#if PACKETVER >= 20091229
packetLen(0x0807, 4)
#elif PACKETVER >= 20091222
packetLen(0x0807, 2)
#endif

// Packet: 0x0808
#if PACKETVER >= 20091229
packetLen(0x0808, 14)
#elif PACKETVER >= 20091222
packetLen(0x0808, 4)
#endif

// Packet: 0x0809
#if PACKETVER >= 20091229
packetLen(0x0809, 50)
#elif PACKETVER >= 20091222
packetLen(0x0809, 14)
#endif

// Packet: 0x080a
#if PACKETVER >= 20091229
packetLen(0x080A, 18)
#elif PACKETVER >= 20091222
packetLen(0x080A, 50)
#endif

// Packet: 0x080b
#if PACKETVER >= 20091229
packetLen(0x080B, 6)
#elif PACKETVER >= 20091222
packetLen(0x080B, 18)
#endif

// Packet: 0x080c
#if PACKETVER >= 20091229
// removed
#elif PACKETVER >= 20091222
packetLen(0x080C, 6)
#endif

#endif /* COMMON_PACKETS2009_LEN_RE_H */
