/**
 * This file is part of Hercules.
 * http://herc.ws - http://github.com/HerculesWS/Hercules
 *
 * Copyright (C) 2019  Hercules Dev Team
 * Copyright (C) 2019  Andrei Karas (4144)
 *
 * Hercules is free software: you can redistribute it and/or modify
 * it under the terms of the GNU General Public License as published by
 * the Free Software Foundation, either version 3 of the License, or
 * (at your option) any later version.
 *
 * This program is distributed in the hope that it will be useful,
 * but WITHOUT ANY WARRANTY; without even the implied warranty of
 * MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
 * GNU General Public License for more details.
 *
 * You should have received a copy of the GNU General Public License
 * along with this program.  If not, see <http://www.gnu.org/licenses/>.
 */

#ifndef COMMON_PACKETS2007_LEN_SAK_H
#define COMMON_PACKETS2007_LEN_SAK_H

/* This file is autogenerated, please do not commit manual changes */

// Packet: 0x0064
packetLen(0x0064, 55)  // CA_LOGIN

// Packet: 0x0065
packetLen(0x0065, 17)  // CH_ENTER

// Packet: 0x0066
packetLen(0x0066, 3)  // CH_SELECT_CHAR

// Packet: 0x0067
packetLen(0x0067, 37)  // CH_MAKE_CHAR

// Packet: 0x0068
packetLen(0x0068, 46)  // CH_DELETE_CHAR

// Packet: 0x0069
packetLen(0x0069, -1)  // AC_ACCEPT_LOGIN

// Packet: 0x006a
packetLen(0x006a, 23)  // AC_REFUSE_LOGIN

// Packet: 0x006b
packetLen(0x006b, -1)  // HC_ACCEPT_ENTER

// Packet: 0x006c
packetLen(0x006c, 3)  // HC_REFUSE_ENTER

// Packet: 0x006d
packetLen(0x006d, 110)  // HC_ACCEPT_MAKECHAR

// Packet: 0x006e
packetLen(0x006e, 3)  // HC_REFUSE_MAKECHAR

// Packet: 0x006f
packetLen(0x006f, 2)  // HC_ACCEPT_DELETECHAR

// Packet: 0x0070
packetLen(0x0070, 3)  // HC_REFUSE_DELETECHAR

// Packet: 0x0071
packetLen(0x0071, 28)  // HC_NOTIFY_ZONESVR

// Packet: 0x0072
#if PACKETVER >= 20070212
packetLen(0x0072, 25)  // CZ_ENTER
#elif PACKETVER >= 20070108
packetLen(0x0072, 30)  // CZ_ENTER
#elif PACKETVER >= 20070102
packetLen(0x0072, 26)  // CZ_ENTER
#endif

// Packet: 0x0073
packetLen(0x0073, 11)  // ZC_ACCEPT_ENTER

// Packet: 0x0074
packetLen(0x0074, 3)  // ZC_REFUSE_ENTER

// Packet: 0x0075
packetLen(0x0075, -1)  // ZC_NOTIFY_INITCHAR

// Packet: 0x0076
packetLen(0x0076, 9)  // ZC_NOTIFY_UPDATECHAR

// Packet: 0x0077
packetLen(0x0077, 5)  // ZC_NOTIFY_UPDATEPLAYER

// Packet: 0x0078
#if PACKETVER >= 20071106
packetLen(0x0078, 55)  // ZC_NOTIFY_STANDENTRY
#elif PACKETVER >= 20070102
packetLen(0x0078, 54)  // ZC_NOTIFY_STANDENTRY
#endif

// Packet: 0x0079
packetLen(0x0079, 53)  // ZC_NOTIFY_NEWENTRY

// Packet: 0x007a
packetLen(0x007a, 58)  // ZC_NOTIFY_ACTENTRY

// Packet: 0x007b
packetLen(0x007b, 60)  // ZC_NOTIFY_MOVEENTRY

// Packet: 0x007c
#if PACKETVER >= 20071106
packetLen(0x007c, 42)  // ZC_NOTIFY_STANDENTRY_NPC
#elif PACKETVER >= 20070102
packetLen(0x007c, 41)  // ZC_NOTIFY_STANDENTRY_NPC
#endif

// Packet: 0x007d
packetLen(0x007d, 2)  // CZ_NOTIFY_ACTORINIT

// Packet: 0x007e
#if PACKETVER >= 20070212
packetLen(0x007e, 102)  // CZ_REQUEST_TIME
#elif PACKETVER >= 20070102
packetLen(0x007e, 120)  // CZ_REQUEST_TIME
#endif

// Packet: 0x007f
packetLen(0x007f, 6)  // ZC_NOTIFY_TIME

// Packet: 0x0080
packetLen(0x0080, 7)  // ZC_NOTIFY_VANISH

// Packet: 0x0081
packetLen(0x0081, 3)  // SC_NOTIFY_BAN

// Packet: 0x0082
packetLen(0x0082, 2)  // CZ_REQUEST_QUIT

// Packet: 0x0083
packetLen(0x0083, 2)  // ZC_ACCEPT_QUIT

// Packet: 0x0084
packetLen(0x0084, 2)  // ZC_REFUSE_QUIT

// Packet: 0x0085
#if PACKETVER >= 20070212
packetLen(0x0085, 11)  // CZ_REQUEST_MOVE
#elif PACKETVER >= 20070108
packetLen(0x0085, 14)  // CZ_REQUEST_MOVE
#elif PACKETVER >= 20070102
packetLen(0x0085, 12)  // CZ_REQUEST_MOVE
#endif

// Packet: 0x0086
packetLen(0x0086, 16)  // ZC_NOTIFY_MOVE

// Packet: 0x0087
packetLen(0x0087, 12)  // ZC_NOTIFY_PLAYERMOVE

// Packet: 0x0088
packetLen(0x0088, 10)  // ZC_STOPMOVE

// Packet: 0x0089
#if PACKETVER >= 20070212
packetLen(0x0089, 8)  // CZ_REQUEST_ACT
#elif PACKETVER >= 20070108
packetLen(0x0089, 11)  // CZ_REQUEST_ACT
#elif PACKETVER >= 20070102
packetLen(0x0089, 13)  // CZ_REQUEST_ACT
#endif

// Packet: 0x008a
packetLen(0x008a, 29)  // ZC_NOTIFY_ACT

// Packet: 0x008b
packetLen(0x008b, 23)  // ZC_NOTIFY_ACT_POSITION

// Packet: 0x008c
#if PACKETVER >= 20070212
packetLen(0x008c, 11)
#elif PACKETVER >= 20070108
packetLen(0x008c, 17)
#elif PACKETVER >= 20070102
packetLen(0x008c, 12)
#endif

// Packet: 0x008d
packetLen(0x008d, -1)  // ZC_NOTIFY_CHAT

// Packet: 0x008e
packetLen(0x008e, -1)  // ZC_NOTIFY_PLAYERCHAT

// Packet: 0x0090
packetLen(0x0090, 7)  // CZ_CONTACTNPC

// Packet: 0x0091
packetLen(0x0091, 22)  // ZC_NPCACK_MAPMOVE

// Packet: 0x0092
packetLen(0x0092, 28)  // ZC_NPCACK_SERVERMOVE

// Packet: 0x0093
packetLen(0x0093, 2)  // ZC_NPCACK_ENABLE

// Packet: 0x0094
#if PACKETVER >= 20070212
packetLen(0x0094, 14)  // CZ_REQNAME
#elif PACKETVER >= 20070108
packetLen(0x0094, 17)  // CZ_REQNAME
#elif PACKETVER >= 20070102
packetLen(0x0094, 23)  // CZ_REQNAME
#endif

// Packet: 0x0095
packetLen(0x0095, 30)  // ZC_ACK_REQNAME

// Packet: 0x0096
packetLen(0x0096, -1)  // CZ_WHISPER

// Packet: 0x0097
packetLen(0x0097, -1)  // ZC_WHISPER

// Packet: 0x0098
packetLen(0x0098, 3)  // ZC_ACK_WHISPER

// Packet: 0x0099
packetLen(0x0099, -1)  // CZ_BROADCAST

// Packet: 0x009a
packetLen(0x009a, -1)  // ZC_BROADCAST

// Packet: 0x009b
#if PACKETVER >= 20070212
packetLen(0x009b, 26)  // CZ_CHANGE_DIRECTION
#elif PACKETVER >= 20070108
packetLen(0x009b, 35)  // CZ_CHANGE_DIRECTION
#elif PACKETVER >= 20070102
packetLen(0x009b, 37)  // CZ_CHANGE_DIRECTION
#endif

// Packet: 0x009c
packetLen(0x009c, 9)  // ZC_CHANGE_DIRECTION

// Packet: 0x009d
packetLen(0x009d, 17)  // ZC_ITEM_ENTRY

// Packet: 0x009e
packetLen(0x009e, 17)  // ZC_ITEM_FALL_ENTRY

// Packet: 0x009f
#if PACKETVER >= 20070212
packetLen(0x009f, 14)  // CZ_ITEM_PICKUP
#elif PACKETVER >= 20070108
packetLen(0x009f, 21)  // CZ_ITEM_PICKUP
#elif PACKETVER >= 20070102
packetLen(0x009f, 24)  // CZ_ITEM_PICKUP
#endif

// Packet: 0x00a0
packetLen(0x00a0, 23)  // ZC_ITEM_PICKUP_ACK

// Packet: 0x00a1
packetLen(0x00a1, 6)  // ZC_ITEM_DISAPPEAR

// Packet: 0x00a2
#if PACKETVER >= 20070212
packetLen(0x00a2, 15)  // CZ_ITEM_THROW
#elif PACKETVER >= 20070108
packetLen(0x00a2, 10)  // CZ_ITEM_THROW
#elif PACKETVER >= 20070102
packetLen(0x00a2, 11)  // CZ_ITEM_THROW
#endif

// Packet: 0x00a3
packetLen(0x00a3, -1)  // ZC_NORMAL_ITEMLIST

// Packet: 0x00a4
packetLen(0x00a4, -1)  // ZC_EQUIPMENT_ITEMLIST

// Packet: 0x00a5
packetLen(0x00a5, -1)  // ZC_STORE_NORMAL_ITEMLIST

// Packet: 0x00a6
packetLen(0x00a6, -1)  // ZC_STORE_EQUIPMENT_ITEMLIST

// Packet: 0x00a7
#if PACKETVER >= 20070108
packetLen(0x00a7, 8)
#elif PACKETVER >= 20070102
packetLen(0x00a7, 15)
#endif

// Packet: 0x00a8
packetLen(0x00a8, 7)  // ZC_USE_ITEM_ACK

// Packet: 0x00a9
packetLen(0x00a9, 6)  // CZ_REQ_WEAR_EQUIP

// Packet: 0x00aa
packetLen(0x00aa, 7)  // ZC_REQ_WEAR_EQUIP_ACK

// Packet: 0x00ab
packetLen(0x00ab, 4)  // CZ_REQ_TAKEOFF_EQUIP

// Packet: 0x00ac
packetLen(0x00ac, 7)  // ZC_REQ_TAKEOFF_EQUIP_ACK

// Packet: 0x00ae
packetLen(0x00ae, -1)  // ZC_REQ_ITEM_EXPLANATION_ACK

// Packet: 0x00af
packetLen(0x00af, 6)  // ZC_ITEM_THROW_ACK

// Packet: 0x00b0
packetLen(0x00b0, 8)  // ZC_PAR_CHANGE

// Packet: 0x00b1
packetLen(0x00b1, 8)  // ZC_LONGPAR_CHANGE

// Packet: 0x00b2
packetLen(0x00b2, 3)  // CZ_RESTART

// Packet: 0x00b3
packetLen(0x00b3, 3)  // ZC_RESTART_ACK

// Packet: 0x00b4
packetLen(0x00b4, -1)  // ZC_SAY_DIALOG

// Packet: 0x00b5
packetLen(0x00b5, 6)  // ZC_WAIT_DIALOG

// Packet: 0x00b6
packetLen(0x00b6, 6)  // ZC_CLOSE_DIALOG

// Packet: 0x00b7
packetLen(0x00b7, -1)  // ZC_MENU_LIST

// Packet: 0x00b8
packetLen(0x00b8, 7)  // CZ_CHOOSE_MENU

// Packet: 0x00b9
packetLen(0x00b9, 6)  // CZ_REQ_NEXT_SCRIPT

// Packet: 0x00ba
packetLen(0x00ba, 2)  // CZ_REQ_STATUS

// Packet: 0x00bb
packetLen(0x00bb, 5)  // CZ_STATUS_CHANGE

// Packet: 0x00bc
packetLen(0x00bc, 6)  // ZC_STATUS_CHANGE_ACK

// Packet: 0x00bd
packetLen(0x00bd, 44)  // ZC_STATUS

// Packet: 0x00be
packetLen(0x00be, 5)  // ZC_STATUS_CHANGE

// Packet: 0x00bf
packetLen(0x00bf, 3)  // CZ_REQ_EMOTION

// Packet: 0x00c0
packetLen(0x00c0, 7)  // ZC_EMOTION

// Packet: 0x00c1
packetLen(0x00c1, 2)  // CZ_REQ_USER_COUNT

// Packet: 0x00c2
packetLen(0x00c2, 6)  // ZC_USER_COUNT

// Packet: 0x00c3
packetLen(0x00c3, 8)  // ZC_SPRITE_CHANGE

// Packet: 0x00c4
packetLen(0x00c4, 6)  // ZC_SELECT_DEALTYPE

// Packet: 0x00c5
packetLen(0x00c5, 7)  // CZ_ACK_SELECT_DEALTYPE

// Packet: 0x00c6
packetLen(0x00c6, -1)  // ZC_PC_PURCHASE_ITEMLIST

// Packet: 0x00c7
packetLen(0x00c7, -1)  // ZC_PC_SELL_ITEMLIST

// Packet: 0x00c8
packetLen(0x00c8, -1)  // CZ_PC_PURCHASE_ITEMLIST

// Packet: 0x00c9
packetLen(0x00c9, -1)  // CZ_PC_SELL_ITEMLIST

// Packet: 0x00ca
packetLen(0x00ca, 3)  // ZC_PC_PURCHASE_RESULT

// Packet: 0x00cb
packetLen(0x00cb, 3)  // ZC_PC_SELL_RESULT

// Packet: 0x00cc
packetLen(0x00cc, 6)  // CZ_DISCONNECT_CHARACTER

// Packet: 0x00cd
packetLen(0x00cd, 3)  // ZC_ACK_DISCONNECT_CHARACTER

// Packet: 0x00ce
packetLen(0x00ce, 2)  // CZ_DISCONNECT_ALL_CHARACTER

// Packet: 0x00cf
packetLen(0x00cf, 27)  // CZ_SETTING_WHISPER_PC

// Packet: 0x00d0
packetLen(0x00d0, 3)  // CZ_SETTING_WHISPER_STATE

// Packet: 0x00d1
packetLen(0x00d1, 4)  // ZC_SETTING_WHISPER_PC

// Packet: 0x00d2
packetLen(0x00d2, 4)  // ZC_SETTING_WHISPER_STATE

// Packet: 0x00d3
packetLen(0x00d3, 2)  // CZ_REQ_WHISPER_LIST

// Packet: 0x00d4
packetLen(0x00d4, -1)  // ZC_WHISPER_LIST

// Packet: 0x00d5
packetLen(0x00d5, -1)  // CZ_CREATE_CHATROOM

// Packet: 0x00d6
packetLen(0x00d6, 3)  // ZC_ACK_CREATE_CHATROOM

// Packet: 0x00d7
packetLen(0x00d7, -1)  // ZC_ROOM_NEWENTRY

// Packet: 0x00d8
packetLen(0x00d8, 6)  // ZC_DESTROY_ROOM

// Packet: 0x00d9
packetLen(0x00d9, 14)  // CZ_REQ_ENTER_ROOM

// Packet: 0x00da
packetLen(0x00da, 3)  // ZC_REFUSE_ENTER_ROOM

// Packet: 0x00db
packetLen(0x00db, -1)  // ZC_ENTER_ROOM

// Packet: 0x00dc
packetLen(0x00dc, 28)  // ZC_MEMBER_NEWENTRY

// Packet: 0x00dd
packetLen(0x00dd, 29)  // ZC_MEMBER_EXIT

// Packet: 0x00de
packetLen(0x00de, -1)  // CZ_CHANGE_CHATROOM

// Packet: 0x00df
packetLen(0x00df, -1)  // ZC_CHANGE_CHATROOM

// Packet: 0x00e0
packetLen(0x00e0, 30)  // CZ_REQ_ROLE_CHANGE

// Packet: 0x00e1
packetLen(0x00e1, 30)  // ZC_ROLE_CHANGE

// Packet: 0x00e2
packetLen(0x00e2, 26)  // CZ_REQ_EXPEL_MEMBER

// Packet: 0x00e3
packetLen(0x00e3, 2)  // CZ_EXIT_ROOM

// Packet: 0x00e4
packetLen(0x00e4, 6)  // CZ_REQ_EXCHANGE_ITEM

// Packet: 0x00e5
packetLen(0x00e5, 26)  // ZC_REQ_EXCHANGE_ITEM

// Packet: 0x00e6
packetLen(0x00e6, 3)  // CZ_ACK_EXCHANGE_ITEM

// Packet: 0x00e7
packetLen(0x00e7, 3)  // ZC_ACK_EXCHANGE_ITEM

// Packet: 0x00e8
packetLen(0x00e8, 8)  // CZ_ADD_EXCHANGE_ITEM

// Packet: 0x00e9
packetLen(0x00e9, 19)  // ZC_ADD_EXCHANGE_ITEM

// Packet: 0x00ea
packetLen(0x00ea, 5)  // ZC_ACK_ADD_EXCHANGE_ITEM

// Packet: 0x00eb
packetLen(0x00eb, 2)  // CZ_CONCLUDE_EXCHANGE_ITEM

// Packet: 0x00ec
packetLen(0x00ec, 3)  // ZC_CONCLUDE_EXCHANGE_ITEM

// Packet: 0x00ed
packetLen(0x00ed, 2)  // CZ_CANCEL_EXCHANGE_ITEM

// Packet: 0x00ee
packetLen(0x00ee, 2)  // ZC_CANCEL_EXCHANGE_ITEM

// Packet: 0x00ef
packetLen(0x00ef, 2)  // CZ_EXEC_EXCHANGE_ITEM

// Packet: 0x00f0
packetLen(0x00f0, 3)  // ZC_EXEC_EXCHANGE_ITEM

// Packet: 0x00f1
packetLen(0x00f1, 2)  // ZC_EXCHANGEITEM_UNDO

// Packet: 0x00f2
packetLen(0x00f2, 6)  // ZC_NOTIFY_STOREITEM_COUNTINFO

// Packet: 0x00f3
packetLen(0x00f3, -1)  // CZ_REQUEST_CHAT

// Packet: 0x00f4
packetLen(0x00f4, 21)  // ZC_ADD_ITEM_TO_STORE

// Packet: 0x00f5
#if PACKETVER >= 20070212
packetLen(0x00f5, 8)  // CZ_MOVE_ITEM_FROM_STORE_TO_BODY
#elif PACKETVER >= 20070108
packetLen(0x00f5, 11)  // CZ_MOVE_ITEM_FROM_STORE_TO_BODY
#elif PACKETVER >= 20070102
packetLen(0x00f5, 13)  // CZ_MOVE_ITEM_FROM_STORE_TO_BODY
#endif

// Packet: 0x00f6
packetLen(0x00f6, 8)  // ZC_DELETE_ITEM_FROM_STORE

// Packet: 0x00f7
#if PACKETVER >= 20070212
packetLen(0x00f7, 22)  // CZ_REQUEST_TIME
#elif PACKETVER >= 20070108
packetLen(0x00f7, 15)  // CZ_REQUEST_TIME
#elif PACKETVER >= 20070102
packetLen(0x00f7, 26)  // CZ_REQUEST_TIME
#endif

// Packet: 0x00f8
packetLen(0x00f8, 2)  // ZC_CLOSE_STORE

// Packet: 0x00f9
packetLen(0x00f9, 26)  // CZ_MAKE_GROUP

// Packet: 0x00fa
packetLen(0x00fa, 3)  // ZC_ACK_MAKE_GROUP

// Packet: 0x00fb
packetLen(0x00fb, -1)  // ZC_GROUP_LIST

// Packet: 0x00fc
packetLen(0x00fc, 6)  // CZ_REQ_JOIN_GROUP

// Packet: 0x00fd
packetLen(0x00fd, 27)  // ZC_ACK_REQ_JOIN_GROUP

// Packet: 0x00fe
packetLen(0x00fe, 30)  // ZC_REQ_JOIN_GROUP

// Packet: 0x00ff
packetLen(0x00ff, 10)  // CZ_JOIN_GROUP

// Packet: 0x0100
packetLen(0x0100, 2)  // CZ_REQ_LEAVE_GROUP

// Packet: 0x0101
packetLen(0x0101, 6)  // ZC_GROUPINFO_CHANGE

// Packet: 0x0102
packetLen(0x0102, 6)  // CZ_CHANGE_GROUPEXPOPTION

// Packet: 0x0103
packetLen(0x0103, 30)  // CZ_REQ_EXPEL_GROUP_MEMBER

// Packet: 0x0104
packetLen(0x0104, 79)  // ZC_ADD_MEMBER_TO_GROUP

// Packet: 0x0105
packetLen(0x0105, 31)  // ZC_DELETE_MEMBER_FROM_GROUP

// Packet: 0x0106
packetLen(0x0106, 10)  // ZC_NOTIFY_HP_TO_GROUPM

// Packet: 0x0107
packetLen(0x0107, 10)  // ZC_NOTIFY_POSITION_TO_GROUPM

// Packet: 0x0108
packetLen(0x0108, -1)  // CZ_REQUEST_CHAT_PARTY

// Packet: 0x0109
packetLen(0x0109, -1)  // ZC_NOTIFY_CHAT_PARTY

// Packet: 0x010a
packetLen(0x010a, 4)  // ZC_MVP_GETTING_ITEM

// Packet: 0x010b
packetLen(0x010b, 6)  // ZC_MVP_GETTING_SPECIAL_EXP

// Packet: 0x010c
packetLen(0x010c, 6)  // ZC_MVP

// Packet: 0x010d
packetLen(0x010d, 2)  // ZC_THROW_MVPITEM

// Packet: 0x010e
packetLen(0x010e, 11)  // ZC_SKILLINFO_UPDATE

// Packet: 0x010f
packetLen(0x010f, -1)  // ZC_SKILLINFO_LIST

// Packet: 0x0110
packetLen(0x0110, 10)  // ZC_ACK_TOUSESKILL

// Packet: 0x0111
packetLen(0x0111, 39)  // ZC_ADD_SKILL

// Packet: 0x0112
packetLen(0x0112, 4)  // CZ_UPGRADE_SKILLLEVEL

// Packet: 0x0113
#if PACKETVER >= 20070212
packetLen(0x0113, 22)  // CZ_USE_SKILL
#elif PACKETVER >= 20070102
packetLen(0x0113, 40)  // CZ_USE_SKILL
#endif

// Packet: 0x0114
packetLen(0x0114, 31)  // ZC_NOTIFY_SKILL

// Packet: 0x0115
packetLen(0x0115, 35)  // ZC_NOTIFY_SKILL_POSITION

// Packet: 0x0116
#if PACKETVER >= 20070212
packetLen(0x0116, 10)  // CZ_USE_SKILL_TOGROUND
#elif PACKETVER >= 20070108
packetLen(0x0116, 19)  // CZ_USE_SKILL_TOGROUND
#elif PACKETVER >= 20070102
packetLen(0x0116, 17)  // CZ_USE_SKILL_TOGROUND
#endif

// Packet: 0x0117
packetLen(0x0117, 18)  // ZC_NOTIFY_GROUNDSKILL

// Packet: 0x0118
packetLen(0x0118, 2)  // CZ_CANCEL_LOCKON

// Packet: 0x0119
packetLen(0x0119, 13)  // ZC_STATE_CHANGE

// Packet: 0x011a
packetLen(0x011a, 15)  // ZC_USE_SKILL

// Packet: 0x011b
packetLen(0x011b, 20)  // CZ_SELECT_WARPPOINT

// Packet: 0x011c
packetLen(0x011c, 68)  // ZC_WARPLIST

// Packet: 0x011d
packetLen(0x011d, 2)  // CZ_REMEMBER_WARPPOINT

// Packet: 0x011e
packetLen(0x011e, 3)  // ZC_ACK_REMEMBER_WARPPOINT

// Packet: 0x011f
packetLen(0x011f, 16)  // ZC_SKILL_ENTRY

// Packet: 0x0120
packetLen(0x0120, 6)  // ZC_SKILL_DISAPPEAR

// Packet: 0x0121
packetLen(0x0121, 14)  // ZC_NOTIFY_CARTITEM_COUNTINFO

// Packet: 0x0122
packetLen(0x0122, -1)  // ZC_CART_EQUIPMENT_ITEMLIST

// Packet: 0x0123
packetLen(0x0123, -1)  // ZC_CART_NORMAL_ITEMLIST

// Packet: 0x0124
packetLen(0x0124, 21)  // ZC_ADD_ITEM_TO_CART

// Packet: 0x0125
packetLen(0x0125, 8)  // ZC_DELETE_ITEM_FROM_CART

// Packet: 0x0126
packetLen(0x0126, 8)  // CZ_MOVE_ITEM_FROM_BODY_TO_CART

// Packet: 0x0127
packetLen(0x0127, 8)  // CZ_MOVE_ITEM_FROM_CART_TO_BODY

// Packet: 0x0128
packetLen(0x0128, 8)  // CZ_MOVE_ITEM_FROM_STORE_TO_CART

// Packet: 0x0129
packetLen(0x0129, 8)  // CZ_MOVE_ITEM_FROM_CART_TO_STORE

// Packet: 0x012a
packetLen(0x012a, 2)  // CZ_REQ_CARTOFF

// Packet: 0x012b
packetLen(0x012b, 2)  // ZC_CARTOFF

// Packet: 0x012c
packetLen(0x012c, 3)  // ZC_ACK_ADDITEM_TO_CART

// Packet: 0x012d
packetLen(0x012d, 4)  // ZC_OPENSTORE

// Packet: 0x012e
packetLen(0x012e, 2)  // CZ_REQ_CLOSESTORE

// Packet: 0x012f
packetLen(0x012f, -1)  // CZ_REQ_OPENSTORE

// Packet: 0x0130
packetLen(0x0130, 6)  // CZ_REQ_BUY_FROMMC

// Packet: 0x0131
packetLen(0x0131, 86)  // ZC_STORE_ENTRY

// Packet: 0x0132
packetLen(0x0132, 6)  // ZC_DISAPPEAR_ENTRY

// Packet: 0x0133
packetLen(0x0133, -1)  // ZC_PC_PURCHASE_ITEMLIST_FROMMC

// Packet: 0x0134
packetLen(0x0134, -1)  // CZ_PC_PURCHASE_ITEMLIST_FROMMC

// Packet: 0x0135
packetLen(0x0135, 7)  // ZC_PC_PURCHASE_RESULT_FROMMC

// Packet: 0x0136
packetLen(0x0136, -1)  // ZC_PC_PURCHASE_MYITEMLIST

// Packet: 0x0137
packetLen(0x0137, 6)  // ZC_DELETEITEM_FROM_MCSTORE

// Packet: 0x0138
packetLen(0x0138, 3)  // CZ_PKMODE_CHANGE

// Packet: 0x0139
packetLen(0x0139, 16)  // ZC_ATTACK_FAILURE_FOR_DISTANCE

// Packet: 0x013a
packetLen(0x013a, 4)  // ZC_ATTACK_RANGE

// Packet: 0x013b
packetLen(0x013b, 4)  // ZC_ACTION_FAILURE

// Packet: 0x013c
packetLen(0x013c, 4)  // ZC_EQUIP_ARROW

// Packet: 0x013d
packetLen(0x013d, 6)  // ZC_RECOVERY

// Packet: 0x013e
packetLen(0x013e, 24)  // ZC_USESKILL_ACK

// Packet: 0x013f
packetLen(0x013f, 26)  // CZ_ITEM_CREATE

// Packet: 0x0140
packetLen(0x0140, 22)  // CZ_MOVETO_MAP

// Packet: 0x0141
packetLen(0x0141, 14)  // ZC_COUPLESTATUS

// Packet: 0x0142
packetLen(0x0142, 6)  // ZC_OPEN_EDITDLG

// Packet: 0x0143
packetLen(0x0143, 10)  // CZ_INPUT_EDITDLG

// Packet: 0x0144
packetLen(0x0144, 23)  // ZC_COMPASS

// Packet: 0x0145
packetLen(0x0145, 19)  // ZC_SHOW_IMAGE

// Packet: 0x0146
packetLen(0x0146, 6)  // CZ_CLOSE_DIALOG

// Packet: 0x0147
packetLen(0x0147, 39)  // ZC_AUTORUN_SKILL

// Packet: 0x0148
packetLen(0x0148, 8)  // ZC_RESURRECTION

// Packet: 0x0149
packetLen(0x0149, 9)  // CZ_REQ_GIVE_MANNER_POINT

// Packet: 0x014a
packetLen(0x014a, 6)  // ZC_ACK_GIVE_MANNER_POINT

// Packet: 0x014b
packetLen(0x014b, 27)  // ZC_NOTIFY_MANNER_POINT_GIVEN

// Packet: 0x014c
packetLen(0x014c, -1)  // ZC_MYGUILD_BASIC_INFO

// Packet: 0x014d
packetLen(0x014d, 2)  // CZ_REQ_GUILD_MENUINTERFACE

// Packet: 0x014e
packetLen(0x014e, 6)  // ZC_ACK_GUILD_MENUINTERFACE

// Packet: 0x014f
packetLen(0x014f, 6)  // CZ_REQ_GUILD_MENU

// Packet: 0x0150
packetLen(0x0150, 110)  // ZC_GUILD_INFO

// Packet: 0x0151
packetLen(0x0151, 6)  // CZ_REQ_GUILD_EMBLEM_IMG

// Packet: 0x0152
packetLen(0x0152, -1)  // ZC_GUILD_EMBLEM_IMG

// Packet: 0x0153
packetLen(0x0153, -1)  // CZ_REGISTER_GUILD_EMBLEM_IMG

// Packet: 0x0154
packetLen(0x0154, -1)  // ZC_MEMBERMGR_INFO

// Packet: 0x0155
packetLen(0x0155, -1)  // CZ_REQ_CHANGE_MEMBERPOS

// Packet: 0x0156
packetLen(0x0156, -1)  // ZC_ACK_REQ_CHANGE_MEMBERS

// Packet: 0x0157
packetLen(0x0157, 6)  // CZ_REQ_OPEN_MEMBER_INFO

// Packet: 0x0158
packetLen(0x0158, -1)  // ZC_ACK_OPEN_MEMBER_INFO

// Packet: 0x0159
packetLen(0x0159, 54)  // CZ_REQ_LEAVE_GUILD

// Packet: 0x015a
packetLen(0x015a, 66)  // ZC_ACK_LEAVE_GUILD

// Packet: 0x015b
packetLen(0x015b, 54)  // CZ_REQ_BAN_GUILD

// Packet: 0x015c
packetLen(0x015c, 90)  // ZC_ACK_BAN_GUILD

// Packet: 0x015d
packetLen(0x015d, 42)  // CZ_REQ_DISORGANIZE_GUILD

// Packet: 0x015e
packetLen(0x015e, 6)  // ZC_ACK_DISORGANIZE_GUILD_RESULT

// Packet: 0x015f
packetLen(0x015f, 42)  // ZC_ACK_DISORGANIZE_GUILD

// Packet: 0x0160
packetLen(0x0160, -1)  // ZC_POSITION_INFO

// Packet: 0x0161
packetLen(0x0161, -1)  // CZ_REG_CHANGE_GUILD_POSITIONINFO

// Packet: 0x0162
packetLen(0x0162, -1)  // ZC_GUILD_SKILLINFO

// Packet: 0x0163
packetLen(0x0163, -1)  // ZC_BAN_LIST

// Packet: 0x0164
packetLen(0x0164, -1)  // ZC_OTHER_GUILD_LIST

// Packet: 0x0165
packetLen(0x0165, 30)  // CZ_REQ_MAKE_GUILD

// Packet: 0x0166
packetLen(0x0166, -1)  // ZC_POSITION_ID_NAME_INFO

// Packet: 0x0167
packetLen(0x0167, 3)  // ZC_RESULT_MAKE_GUILD

// Packet: 0x0168
packetLen(0x0168, 14)  // CZ_REQ_JOIN_GUILD

// Packet: 0x0169
packetLen(0x0169, 3)  // ZC_ACK_REQ_JOIN_GUILD

// Packet: 0x016a
packetLen(0x016a, 30)  // ZC_REQ_JOIN_GUILD

// Packet: 0x016b
packetLen(0x016b, 10)  // CZ_JOIN_GUILD

// Packet: 0x016c
packetLen(0x016c, 43)  // ZC_UPDATE_GDID

// Packet: 0x016d
packetLen(0x016d, 14)  // ZC_UPDATE_CHARSTAT

// Packet: 0x016e
packetLen(0x016e, 186)  // CZ_GUILD_NOTICE

// Packet: 0x016f
packetLen(0x016f, 182)  // ZC_GUILD_NOTICE

// Packet: 0x0170
packetLen(0x0170, 14)  // CZ_REQ_ALLY_GUILD

// Packet: 0x0171
packetLen(0x0171, 30)  // ZC_REQ_ALLY_GUILD

// Packet: 0x0172
packetLen(0x0172, 10)  // CZ_ALLY_GUILD

// Packet: 0x0173
packetLen(0x0173, 3)  // ZC_ACK_REQ_ALLY_GUILD

// Packet: 0x0174
packetLen(0x0174, -1)  // ZC_ACK_CHANGE_GUILD_POSITIONINFO

// Packet: 0x0175
packetLen(0x0175, 6)  // CZ_REQ_GUILD_MEMBER_INFO

// Packet: 0x0176
packetLen(0x0176, 106)  // ZC_ACK_GUILD_MEMBER_INFO

// Packet: 0x0177
packetLen(0x0177, -1)  // ZC_ITEMIDENTIFY_LIST

// Packet: 0x0178
packetLen(0x0178, 4)  // CZ_REQ_ITEMIDENTIFY

// Packet: 0x0179
packetLen(0x0179, 5)  // ZC_ACK_ITEMIDENTIFY

// Packet: 0x017a
packetLen(0x017a, 4)  // CZ_REQ_ITEMCOMPOSITION_LIST

// Packet: 0x017b
packetLen(0x017b, -1)  // ZC_ITEMCOMPOSITION_LIST

// Packet: 0x017c
packetLen(0x017c, 6)  // CZ_REQ_ITEMCOMPOSITION

// Packet: 0x017d
packetLen(0x017d, 7)  // ZC_ACK_ITEMCOMPOSITION

// Packet: 0x017e
packetLen(0x017e, -1)  // CZ_GUILD_CHAT

// Packet: 0x017f
packetLen(0x017f, -1)  // ZC_GUILD_CHAT

// Packet: 0x0180
packetLen(0x0180, 6)  // CZ_REQ_HOSTILE_GUILD

// Packet: 0x0181
packetLen(0x0181, 3)  // ZC_ACK_REQ_HOSTILE_GUILD

// Packet: 0x0182
packetLen(0x0182, 106)  // ZC_MEMBER_ADD

// Packet: 0x0183
packetLen(0x0183, 10)  // CZ_REQ_DELETE_RELATED_GUILD

// Packet: 0x0184
packetLen(0x0184, 10)  // ZC_DELETE_RELATED_GUILD

// Packet: 0x0185
packetLen(0x0185, 34)  // ZC_ADD_RELATED_GUILD

// Packet: 0x0187
packetLen(0x0187, 6)  // CH_UNKNOWN_PING

// Packet: 0x0188
packetLen(0x0188, 8)  // ZC_ACK_ITEMREFINING

// Packet: 0x0189
packetLen(0x0189, 4)  // ZC_NOTIFY_MAPINFO

// Packet: 0x018a
packetLen(0x018a, 4)  // CZ_REQ_DISCONNECT

// Packet: 0x018b
packetLen(0x018b, 4)  // ZC_ACK_REQ_DISCONNECT

// Packet: 0x018c
packetLen(0x018c, 29)  // ZC_MONSTER_INFO

// Packet: 0x018d
packetLen(0x018d, -1)  // ZC_MAKABLEITEMLIST

// Packet: 0x018e
packetLen(0x018e, 10)  // CZ_REQMAKINGITEM

// Packet: 0x018f
packetLen(0x018f, 6)  // ZC_ACK_REQMAKINGITEM

// Packet: 0x0190
#if PACKETVER >= 20070212
packetLen(0x0190, 19)  // CZ_USE_SKILL_TOGROUND_WITHTALKBOX
#elif PACKETVER >= 20070108
packetLen(0x0190, 10)  // CZ_USE_SKILL_TOGROUND_WITHTALKBOX
#elif PACKETVER >= 20070102
packetLen(0x0190, 18)  // CZ_USE_SKILL_TOGROUND_WITHTALKBOX
#endif

// Packet: 0x0191
packetLen(0x0191, 86)  // ZC_TALKBOX_CHATCONTENTS

// Packet: 0x0192
packetLen(0x0192, 24)  // ZC_UPDATE_MAPINFO

// Packet: 0x0193
packetLen(0x0193, 2)  // CZ_REQNAME_BYGID

// Packet: 0x0194
packetLen(0x0194, 30)  // ZC_ACK_REQNAME_BYGID

// Packet: 0x0195
packetLen(0x0195, 102)  // ZC_ACK_REQNAMEALL

// Packet: 0x0196
packetLen(0x0196, 9)  // ZC_MSG_STATE_CHANGE

// Packet: 0x0197
packetLen(0x0197, 4)  // CZ_RESET

// Packet: 0x0198
packetLen(0x0198, 8)  // CZ_CHANGE_MAPTYPE

// Packet: 0x0199
packetLen(0x0199, 4)  // ZC_NOTIFY_MAPPROPERTY

// Packet: 0x019a
packetLen(0x019a, 14)  // ZC_NOTIFY_RANKING

// Packet: 0x019b
packetLen(0x019b, 10)  // ZC_NOTIFY_EFFECT

// Packet: 0x019c
packetLen(0x019c, -1)  // CZ_LOCALBROADCAST

// Packet: 0x019d
packetLen(0x019d, 6)  // CZ_CHANGE_EFFECTSTATE

// Packet: 0x019e
packetLen(0x019e, 2)  // ZC_START_CAPTURE

// Packet: 0x019f
packetLen(0x019f, 6)  // CZ_TRYCAPTURE_MONSTER

// Packet: 0x01a0
packetLen(0x01a0, 3)  // ZC_TRYCAPTURE_MONSTER

// Packet: 0x01a1
packetLen(0x01a1, 3)  // CZ_COMMAND_PET

// Packet: 0x01a2
packetLen(0x01a2, 35)  // ZC_PROPERTY_PET

// Packet: 0x01a3
packetLen(0x01a3, 5)  // ZC_FEED_PET

// Packet: 0x01a4
packetLen(0x01a4, 11)  // ZC_CHANGESTATE_PET

// Packet: 0x01a5
packetLen(0x01a5, 26)  // CZ_RENAME_PET

// Packet: 0x01a6
packetLen(0x01a6, -1)  // ZC_PETEGG_LIST

// Packet: 0x01a7
packetLen(0x01a7, 4)  // CZ_SELECT_PETEGG

// Packet: 0x01a8
packetLen(0x01a8, 4)  // CZ_PETEGG_INFO

// Packet: 0x01a9
packetLen(0x01a9, 6)  // CZ_PET_ACT

// Packet: 0x01aa
packetLen(0x01aa, 10)  // ZC_PET_ACT

// Packet: 0x01ab
packetLen(0x01ab, 12)  // ZC_PAR_CHANGE_USER

// Packet: 0x01ac
packetLen(0x01ac, 6)  // ZC_SKILL_UPDATE

// Packet: 0x01ad
packetLen(0x01ad, -1)  // ZC_MAKINGARROW_LIST

// Packet: 0x01ae
packetLen(0x01ae, 4)  // CZ_REQ_MAKINGARROW

// Packet: 0x01af
packetLen(0x01af, 4)  // CZ_REQ_CHANGECART

// Packet: 0x01b0
packetLen(0x01b0, 11)  // ZC_NPCSPRITE_CHANGE

// Packet: 0x01b1
packetLen(0x01b1, 7)  // ZC_SHOWDIGIT

// Packet: 0x01b2
packetLen(0x01b2, -1)  // CZ_REQ_OPENSTORE2

// Packet: 0x01b3
packetLen(0x01b3, 67)  // ZC_SHOW_IMAGE2

// Packet: 0x01b4
packetLen(0x01b4, 12)  // ZC_CHANGE_GUILD

// Packet: 0x01b5
packetLen(0x01b5, 18)  // SC_BILLING_INFO

// Packet: 0x01b6
packetLen(0x01b6, 114)  // ZC_GUILD_INFO2

// Packet: 0x01b7
packetLen(0x01b7, 6)  // CZ_GUILD_ZENY

// Packet: 0x01b8
packetLen(0x01b8, 3)  // ZC_GUILD_ZENY_ACK

// Packet: 0x01b9
packetLen(0x01b9, 6)  // ZC_DISPEL

// Packet: 0x01ba
packetLen(0x01ba, 26)  // CZ_REMOVE_AID

// Packet: 0x01bb
packetLen(0x01bb, 26)  // CZ_SHIFT

// Packet: 0x01bc
packetLen(0x01bc, 26)  // CZ_RECALL

// Packet: 0x01bd
packetLen(0x01bd, 26)  // CZ_RECALL_GID

// Packet: 0x01be
packetLen(0x01be, 2)  // AC_ASK_PNGAMEROOM

// Packet: 0x01bf
packetLen(0x01bf, 3)  // CA_REPLY_PNGAMEROOM

// Packet: 0x01c0
packetLen(0x01c0, 2)  // CZ_REQ_REMAINTIME

// Packet: 0x01c1
packetLen(0x01c1, 14)  // ZC_REPLY_REMAINTIME

// Packet: 0x01c2
packetLen(0x01c2, 10)  // ZC_INFO_REMAINTIME

// Packet: 0x01c3
packetLen(0x01c3, -1)  // ZC_BROADCAST2

// Packet: 0x01c4
packetLen(0x01c4, 22)  // ZC_ADD_ITEM_TO_STORE2

// Packet: 0x01c5
packetLen(0x01c5, 22)  // ZC_ADD_ITEM_TO_CART2

// Packet: 0x01c6
packetLen(0x01c6, 4)  // CS_REQ_ENCRYPTION

// Packet: 0x01c7
packetLen(0x01c7, 2)  // SC_ACK_ENCRYPTION

// Packet: 0x01c8
packetLen(0x01c8, 13)  // ZC_USE_ITEM_ACK2

// Packet: 0x01c9
packetLen(0x01c9, 97)  // ZC_SKILL_ENTRY2

// Packet: 0x01ca
packetLen(0x01ca, 3)  // CZ_REQMAKINGHOMUN

// Packet: 0x01cb
packetLen(0x01cb, 9)  // CZ_MONSTER_TALK

// Packet: 0x01cc
packetLen(0x01cc, 9)  // ZC_MONSTER_TALK

// Packet: 0x01cd
packetLen(0x01cd, 30)  // ZC_AUTOSPELLLIST

// Packet: 0x01ce
packetLen(0x01ce, 6)  // CZ_SELECTAUTOSPELL

// Packet: 0x01cf
packetLen(0x01cf, 28)  // ZC_DEVOTIONLIST

// Packet: 0x01d0
packetLen(0x01d0, 8)  // ZC_SPIRITS

// Packet: 0x01d1
packetLen(0x01d1, 14)  // ZC_BLADESTOP

// Packet: 0x01d2
packetLen(0x01d2, 10)  // ZC_COMBODELAY

// Packet: 0x01d3
packetLen(0x01d3, 35)  // ZC_SOUND

// Packet: 0x01d4
packetLen(0x01d4, 6)  // ZC_OPEN_EDITDLGSTR

// Packet: 0x01d5
packetLen(0x01d5, -1)  // CZ_INPUT_EDITDLGSTR

// Packet: 0x01d6
packetLen(0x01d6, 4)  // ZC_NOTIFY_MAPPROPERTY2

// Packet: 0x01d7
packetLen(0x01d7, 11)  // ZC_SPRITE_CHANGE2

// Packet: 0x01d8
packetLen(0x01d8, 54)  // ZC_NOTIFY_STANDENTRY2

// Packet: 0x01d9
packetLen(0x01d9, 53)  // ZC_NOTIFY_NEWENTRY2

// Packet: 0x01da
packetLen(0x01da, 60)  // ZC_NOTIFY_MOVEENTRY2

// Packet: 0x01db
packetLen(0x01db, 2)  // CA_REQ_HASH

// Packet: 0x01dc
packetLen(0x01dc, -1)  // AC_ACK_HASH

// Packet: 0x01dd
packetLen(0x01dd, 47)  // CA_LOGIN2

// Packet: 0x01de
packetLen(0x01de, 33)  // ZC_NOTIFY_SKILL2

// Packet: 0x01df
packetLen(0x01df, 6)  // CZ_REQ_ACCOUNTNAME

// Packet: 0x01e0
packetLen(0x01e0, 30)  // ZC_ACK_ACCOUNTNAME

// Packet: 0x01e1
packetLen(0x01e1, 8)  // ZC_SPIRITS2

// Packet: 0x01e2
packetLen(0x01e2, 34)  // ZC_REQ_COUPLE

// Packet: 0x01e3
packetLen(0x01e3, 14)  // CZ_JOIN_COUPLE

// Packet: 0x01e4
packetLen(0x01e4, 2)  // ZC_START_COUPLE

// Packet: 0x01e5
packetLen(0x01e5, 6)  // CZ_REQ_JOIN_COUPLE

// Packet: 0x01e6
packetLen(0x01e6, 26)  // ZC_COUPLENAME

// Packet: 0x01e7
packetLen(0x01e7, 2)  // CZ_DORIDORI

// Packet: 0x01e8
packetLen(0x01e8, 28)  // CZ_MAKE_GROUP2

// Packet: 0x01e9
packetLen(0x01e9, 81)  // ZC_ADD_MEMBER_TO_GROUP2

// Packet: 0x01ea
packetLen(0x01ea, 6)  // ZC_CONGRATULATION

// Packet: 0x01eb
packetLen(0x01eb, 10)  // ZC_NOTIFY_POSITION_TO_GUILDM

// Packet: 0x01ec
packetLen(0x01ec, 26)  // ZC_GUILD_MEMBER_MAP_CHANGE

// Packet: 0x01ed
packetLen(0x01ed, 2)  // CZ_CHOPOKGI

// Packet: 0x01ee
packetLen(0x01ee, -1)  // ZC_NORMAL_ITEMLIST2

// Packet: 0x01ef
packetLen(0x01ef, -1)  // ZC_CART_NORMAL_ITEMLIST2

// Packet: 0x01f0
packetLen(0x01f0, -1)  // ZC_STORE_NORMAL_ITEMLIST2

// Packet: 0x01f1
packetLen(0x01f1, -1)  // AC_NOTIFY_ERROR

// Packet: 0x01f2
packetLen(0x01f2, 20)  // ZC_UPDATE_CHARSTAT2

// Packet: 0x01f3
packetLen(0x01f3, 10)  // ZC_NOTIFY_EFFECT2

// Packet: 0x01f4
packetLen(0x01f4, 32)  // ZC_REQ_EXCHANGE_ITEM2

// Packet: 0x01f5
packetLen(0x01f5, 9)  // ZC_ACK_EXCHANGE_ITEM2

// Packet: 0x01f6
packetLen(0x01f6, 34)  // ZC_REQ_BABY

// Packet: 0x01f7
packetLen(0x01f7, 14)  // CZ_JOIN_BABY

// Packet: 0x01f8
packetLen(0x01f8, 2)  // ZC_START_BABY

// Packet: 0x01f9
packetLen(0x01f9, 6)  // CZ_REQ_JOIN_BABY

// Packet: 0x01fa
packetLen(0x01fa, 48)  // CA_LOGIN3

// Packet: 0x01fb
packetLen(0x01fb, 56)  // CH_DELETE_CHAR2

// Packet: 0x01fc
packetLen(0x01fc, -1)  // ZC_REPAIRITEMLIST

// Packet: 0x01fd
#if PACKETVER >= 20070507
packetLen(0x01fd, 15)  // CZ_REQ_ITEMREPAIR
#elif PACKETVER >= 20070102
packetLen(0x01fd, 4)  // CZ_REQ_ITEMREPAIR
#endif

// Packet: 0x01fe
packetLen(0x01fe, 5)  // ZC_ACK_ITEMREPAIR

// Packet: 0x01ff
packetLen(0x01ff, 10)  // ZC_HIGHJUMP

// Packet: 0x0200
packetLen(0x0200, 26)  // CA_CONNECT_INFO_CHANGED

// Packet: 0x0201
packetLen(0x0201, -1)  // ZC_FRIENDS_LIST

// Packet: 0x0202
packetLen(0x0202, 26)  // CZ_ADD_FRIENDS

// Packet: 0x0203
packetLen(0x0203, 10)  // CZ_DELETE_FRIENDS

// Packet: 0x0204
packetLen(0x0204, 18)  // CA_EXE_HASHCHECK

// Packet: 0x0205
packetLen(0x0205, 26)  // ZC_DIVORCE

// Packet: 0x0206
packetLen(0x0206, 11)  // ZC_FRIENDS_STATE

// Packet: 0x0207
packetLen(0x0207, 34)  // ZC_REQ_ADD_FRIENDS

// Packet: 0x0208
packetLen(0x0208, 14)  // CZ_ACK_REQ_ADD_FRIENDS

// Packet: 0x0209
packetLen(0x0209, 36)  // ZC_ADD_FRIENDS_LIST

// Packet: 0x020a
packetLen(0x020a, 10)  // ZC_DELETE_FRIENDS

// Packet: 0x020d
packetLen(0x020d, -1)  // HC_BLOCK_CHARACTER

// Packet: 0x020e
packetLen(0x020e, 32)  // ZC_STARSKILL

// Packet: 0x020f
packetLen(0x020f, 10)  // CZ_REQ_PVPPOINT

// Packet: 0x0210
packetLen(0x0210, 22)  // ZC_ACK_PVPPOINT

// Packet: 0x0212
packetLen(0x0212, 26)  // CZ_REQ_GIVE_MANNER_BYNAME

// Packet: 0x0213
packetLen(0x0213, 26)  // CZ_REQ_STATUS_GM

// Packet: 0x0214
packetLen(0x0214, 42)  // ZC_ACK_STATUS_GM

// Packet: 0x0215
packetLen(0x0215, 6)  // ZC_SKILLMSG

// Packet: 0x0216
packetLen(0x0216, 6)  // ZC_BABYMSG

// Packet: 0x0217
packetLen(0x0217, 2)  // CZ_BLACKSMITH_RANK

// Packet: 0x0218
packetLen(0x0218, 2)  // CZ_ALCHEMIST_RANK

// Packet: 0x0219
packetLen(0x0219, 282)  // ZC_BLACKSMITH_RANK

// Packet: 0x021a
packetLen(0x021a, 282)  // ZC_ALCHEMIST_RANK

// Packet: 0x021b
packetLen(0x021b, 10)  // ZC_BLACKSMITH_POINT

// Packet: 0x021c
packetLen(0x021c, 10)  // ZC_ALCHEMIST_POINT

// Packet: 0x021d
packetLen(0x021d, 6)  // CZ_LESSEFFECT

// Packet: 0x021e
packetLen(0x021e, 6)  // ZC_LESSEFFECT

// Packet: 0x021f
packetLen(0x021f, 66)  // ZC_NOTIFY_PKINFO

// Packet: 0x0220
packetLen(0x0220, 10)  // ZC_NOTIFY_CRAZYKILLER

// Packet: 0x0221
packetLen(0x0221, -1)  // ZC_NOTIFY_WEAPONITEMLIST

// Packet: 0x0222
packetLen(0x0222, 6)  // CZ_REQ_WEAPONREFINE

// Packet: 0x0223
packetLen(0x0223, 8)  // ZC_ACK_WEAPONREFINE

// Packet: 0x0224
packetLen(0x0224, 10)  // ZC_TAEKWON_POINT

// Packet: 0x0225
packetLen(0x0225, 2)  // CZ_TAEKWON_RANK

// Packet: 0x0226
packetLen(0x0226, 282)  // ZC_TAEKWON_RANK

// Packet: 0x0227
packetLen(0x0227, 18)  // ZC_GAME_GUARD

// Packet: 0x0228
packetLen(0x0228, 18)  // CZ_ACK_GAME_GUARD

// Packet: 0x0229
packetLen(0x0229, 15)  // ZC_STATE_CHANGE3

// Packet: 0x022a
packetLen(0x022a, 58)  // ZC_NOTIFY_STANDENTRY3

// Packet: 0x022b
packetLen(0x022b, 57)  // ZC_NOTIFY_NEWENTRY3

// Packet: 0x022c
#if PACKETVER >= 20071106
packetLen(0x022c, 65)  // ZC_NOTIFY_MOVEENTRY3
#elif PACKETVER >= 20070102
packetLen(0x022c, 64)  // ZC_NOTIFY_MOVEENTRY3
#endif

// Packet: 0x022d
packetLen(0x022d, 5)  // CZ_COMMAND_MER

// Packet: 0x022e
packetLen(0x022e, 71)  // ZC_PROPERTY_HOMUN

// Packet: 0x022f
packetLen(0x022f, 5)  // ZC_FEED_MER

// Packet: 0x0230
packetLen(0x0230, 12)  // ZC_CHANGESTATE_MER

// Packet: 0x0231
packetLen(0x0231, 26)  // CZ_RENAME_MER

// Packet: 0x0232
packetLen(0x0232, 9)  // CZ_REQUEST_MOVENPC

// Packet: 0x0233
packetLen(0x0233, 11)  // CZ_REQUEST_ACTNPC

// Packet: 0x0234
packetLen(0x0234, 6)  // CZ_REQUEST_MOVETOOWNER

// Packet: 0x0235
packetLen(0x0235, -1)  // ZC_HOSKILLINFO_LIST

// Packet: 0x0236
packetLen(0x0236, 10)  // ZC_KILLER_POINT

// Packet: 0x0237
packetLen(0x0237, 2)  // CZ_KILLER_RANK

// Packet: 0x0238
packetLen(0x0238, 282)  // ZC_KILLER_RANK

// Packet: 0x0239
packetLen(0x0239, 11)  // ZC_HOSKILLINFO_UPDATE

// Packet: 0x023a
packetLen(0x023a, 4)  // ZC_REQ_STORE_PASSWORD

// Packet: 0x023b
packetLen(0x023b, 36)  // CZ_ACK_STORE_PASSWORD

// Packet: 0x023c
packetLen(0x023c, 6)  // ZC_RESULT_STORE_PASSWORD

// Packet: 0x023d
packetLen(0x023d, 6)  // AC_EVENT_RESULT

// Packet: 0x023e
packetLen(0x023e, 8)  // HC_REQUEST_CHARACTER_PASSWORD

// Packet: 0x023f
packetLen(0x023f, 2)  // CZ_MAIL_GET_LIST

// Packet: 0x0240
packetLen(0x0240, -1)  // ZC_MAIL_REQ_GET_LIST

// Packet: 0x0241
packetLen(0x0241, 6)  // CZ_MAIL_OPEN

// Packet: 0x0242
packetLen(0x0242, -1)  // ZC_MAIL_REQ_OPEN

// Packet: 0x0243
packetLen(0x0243, 6)  // CZ_MAIL_DELETE

// Packet: 0x0244
packetLen(0x0244, 6)  // CZ_MAIL_GET_ITEM

// Packet: 0x0245
packetLen(0x0245, 3)  // ZC_MAIL_REQ_GET_ITEM

// Packet: 0x0246
packetLen(0x0246, 4)  // CZ_MAIL_RESET_ITEM

// Packet: 0x0247
packetLen(0x0247, 8)  // CZ_MAIL_ADD_ITEM

// Packet: 0x0248
packetLen(0x0248, -1)  // CZ_MAIL_SEND

// Packet: 0x0249
packetLen(0x0249, 3)  // ZC_MAIL_REQ_SEND

// Packet: 0x024a
packetLen(0x024a, 70)  // ZC_MAIL_RECEIVE

// Packet: 0x024b
packetLen(0x024b, 4)  // CZ_AUCTION_CREATE

// Packet: 0x024c
packetLen(0x024c, 8)  // CZ_AUCTION_ADD_ITEM

// Packet: 0x024d
packetLen(0x024d, 12)  // CZ_AUCTION_ADD

// Packet: 0x024e
packetLen(0x024e, 6)  // CZ_AUCTION_ADD_CANCEL

// Packet: 0x024f
packetLen(0x024f, 10)  // CZ_AUCTION_BUY

// Packet: 0x0250
packetLen(0x0250, 3)  // ZC_AUCTION_RESULT

// Packet: 0x0251
packetLen(0x0251, 34)  // CZ_AUCTION_ITEM_SEARCH

// Packet: 0x0252
packetLen(0x0252, -1)  // ZC_AUCTION_ITEM_REQ_SEARCH

// Packet: 0x0253
packetLen(0x0253, 3)  // ZC_STARPLACE

// Packet: 0x0254
packetLen(0x0254, 3)  // CZ_AGREE_STARPLACE

// Packet: 0x0255
packetLen(0x0255, 5)  // ZC_ACK_MAIL_ADD_ITEM

// Packet: 0x0256
packetLen(0x0256, 5)  // ZC_ACK_AUCTION_ADD_ITEM

// Packet: 0x0257
packetLen(0x0257, 8)  // ZC_ACK_MAIL_DELETE

// Packet: 0x0258
packetLen(0x0258, 2)  // CA_REQ_GAME_GUARD_CHECK

// Packet: 0x0259
packetLen(0x0259, 3)  // AC_ACK_GAME_GUARD

// Packet: 0x025a
packetLen(0x025a, -1)  // ZC_MAKINGITEM_LIST

// Packet: 0x025b
packetLen(0x025b, 6)  // CZ_REQ_MAKINGITEM

// Packet: 0x025c
packetLen(0x025c, 4)  // CZ_AUCTION_REQ_MY_INFO

// Packet: 0x025d
packetLen(0x025d, 6)  // CZ_AUCTION_REQ_MY_SELL_STOP

// Packet: 0x025e
packetLen(0x025e, 4)  // ZC_AUCTION_ACK_MY_SELL_STOP

// Packet: 0x025f
packetLen(0x025f, 6)  // ZC_AUCTION_WINDOWS

// Packet: 0x0260
packetLen(0x0260, 6)  // ZC_MAIL_WINDOWS

// Packet: 0x0261
packetLen(0x0261, 11)  // AC_REQ_LOGIN_OLDEKEY

// Packet: 0x0262
packetLen(0x0262, 11)  // AC_REQ_LOGIN_NEWEKEY

// Packet: 0x0263
packetLen(0x0263, 11)  // AC_REQ_LOGIN_CARDPASS

// Packet: 0x0264
packetLen(0x0264, 20)  // CA_ACK_LOGIN_OLDEKEY

// Packet: 0x0265
packetLen(0x0265, 20)  // CA_ACK_LOGIN_NEWEKEY

// Packet: 0x0266
packetLen(0x0266, 30)  // CA_ACK_LOGIN_CARDPASS

// Packet: 0x0267
packetLen(0x0267, 4)  // AC_ACK_EKEY_FAIL_NOTEXIST

// Packet: 0x0268
packetLen(0x0268, 4)  // AC_ACK_EKEY_FAIL_NOTUSESEKEY

// Packet: 0x0269
packetLen(0x0269, 4)  // AC_ACK_EKEY_FAIL_NOTUSEDEKEY

// Packet: 0x026a
packetLen(0x026a, 4)  // AC_ACK_EKEY_FAIL_AUTHREFUSE

// Packet: 0x026b
packetLen(0x026b, 4)  // AC_ACK_EKEY_FAIL_INPUTEKEY

// Packet: 0x026c
packetLen(0x026c, 4)  // AC_ACK_EKEY_FAIL_NOTICE

// Packet: 0x026d
packetLen(0x026d, 4)  // AC_ACK_EKEY_FAIL_NEEDCARDPASS

// Packet: 0x026f
packetLen(0x026f, 2)  // AC_ACK_FIRST_LOGIN

// Packet: 0x0270
packetLen(0x0270, 2)  // AC_REQ_LOGIN_ACCOUNT_INFO

// Packet: 0x0271
packetLen(0x0271, 40)  // CA_ACK_LOGIN_ACCOUNT_INFO

// Packet: 0x0272
packetLen(0x0272, 44)  // AC_ACK_PT_ID_INFO

// Packet: 0x0273
packetLen(0x0273, 30)  // CZ_REQ_MAIL_RETURN

// Packet: 0x0274
packetLen(0x0274, 8)  // ZC_ACK_MAIL_RETURN

// Packet: 0x0277
packetLen(0x0277, 84)  // CA_LOGIN_PCBANG

// Packet: 0x0278
packetLen(0x0278, 2)  // ZC_NOTIFY_PCBANG

// Packet: 0x0279
packetLen(0x0279, 2)  // CZ_HUNTINGLIST

// Packet: 0x027a
packetLen(0x027a, -1)  // ZC_HUNTINGLIST

// Packet: 0x027b
packetLen(0x027b, 14)  // ZC_PCBANG_EFFECT

// Packet: 0x027c
packetLen(0x027c, 60)  // CA_LOGIN4

// Packet: 0x027d
packetLen(0x027d, 62)  // ZC_PROPERTY_MERCE

// Packet: 0x027e
packetLen(0x027e, -1)  // ZC_SHANDA_PROTECT

// Packet: 0x027f
packetLen(0x027f, 8)  // CA_CLIENT_TYPE

// Packet: 0x0280
packetLen(0x0280, 12)  // ZC_GANGSI_POINT

// Packet: 0x0281
packetLen(0x0281, 4)  // CZ_GANGSI_RANK

// Packet: 0x0282
packetLen(0x0282, 284)  // ZC_GANGSI_RANK

// Packet: 0x0283
packetLen(0x0283, 6)  // ZC_AID

// Packet: 0x0284
packetLen(0x0284, 14)  // ZC_NOTIFY_EFFECT3

// Packet: 0x0285
packetLen(0x0285, 6)  // ZC_DEATH_QUESTION

// Packet: 0x0286
packetLen(0x0286, 4)  // CZ_DEATH_QUESTION

// Packet: 0x0287
packetLen(0x0287, -1)  // ZC_PC_CASH_POINT_ITEMLIST

// Packet: 0x0288
#if PACKETVER >= 20070711
packetLen(0x0288, 10)  // CZ_PC_BUY_CASH_POINT_ITEM
#elif PACKETVER >= 20070102
packetLen(0x0288, 6)  // CZ_PC_BUY_CASH_POINT_ITEM
#endif

// Packet: 0x0289
#if PACKETVER >= 20070711
packetLen(0x0289, 12)  // ZC_PC_CASH_POINT_UPDATE
#elif PACKETVER >= 20070102
packetLen(0x0289, 8)  // ZC_PC_CASH_POINT_UPDATE
#endif

// Packet: 0x028a
packetLen(0x028a, 18)  // ZC_NPC_SHOWEFST_UPDATE

// Packet: 0x028b
packetLen(0x028b, -1)  // HC_CHARNOTBEENSELECTED

// Packet: 0x028c
packetLen(0x028c, 46)  // CH_SELECT_CHAR_GOINGTOBEUSED

// Packet: 0x028d
packetLen(0x028d, 34)  // CH_REQ_IS_VALID_CHARNAME

// Packet: 0x028e
packetLen(0x028e, 4)  // HC_ACK_IS_VALID_CHARNAME

// Packet: 0x028f
packetLen(0x028f, 6)  // CH_REQ_CHANGE_CHARNAME

// Packet: 0x0290
packetLen(0x0290, 4)  // HC_ACK_CHANGE_CHARNAME

// Packet: 0x0291
packetLen(0x0291, 4)  // ZC_MSG

// Packet: 0x0292
packetLen(0x0292, 2)  // CZ_STANDING_RESURRECTION

// Packet: 0x0293
packetLen(0x0293, 70)  // ZC_BOSS_INFO

// Packet: 0x0294
packetLen(0x0294, 10)  // ZC_READ_BOOK

// Packet: 0x0295
packetLen(0x0295, -1)  // ZC_EQUIPMENT_ITEMLIST2

// Packet: 0x0296
packetLen(0x0296, -1)  // ZC_STORE_EQUIPMENT_ITEMLIST2

// Packet: 0x0297
packetLen(0x0297, -1)  // ZC_CART_EQUIPMENT_ITEMLIST2

// Packet: 0x0298
packetLen(0x0298, 8)  // ZC_CASH_TIME_COUNTER

// Packet: 0x0299
packetLen(0x0299, 6)  // ZC_CASH_ITEM_DELETE

// Packet: 0x029a
packetLen(0x029a, 27)  // ZC_ITEM_PICKUP_ACK2

// Packet: 0x029b
#if PACKETVER >= 20071106
packetLen(0x029b, 80)  // ZC_MER_INIT
#elif PACKETVER >= 20070122
packetLen(0x029b, 72)  // ZC_MER_INIT
#elif PACKETVER >= 20070102
packetLen(0x029b, 70)  // ZC_MER_INIT
#endif

// Packet: 0x029c
packetLen(0x029c, 66)  // ZC_MER_PROPERTY

// Packet: 0x029d
packetLen(0x029d, -1)  // ZC_MER_SKILLINFO_LIST

// Packet: 0x029e
packetLen(0x029e, 11)  // ZC_MER_SKILLINFO_UPDATE

// Packet: 0x029f
packetLen(0x029f, 3)  // CZ_MER_COMMAND

// Packet: 0x02a2
packetLen(0x02a2, 8)  // ZC_MER_PAR_CHANGE

// Packet: 0x02a3
#if PACKETVER >= 20070129
// removed
#elif PACKETVER >= 20070122
packetLen(0x02a3, 18)  // ZC_GAMEGUARD_LINGO_KEY
#endif

// Packet: 0x02a4
#if PACKETVER >= 20070129
// removed
#elif PACKETVER >= 20070122
packetLen(0x02a4, 2)  // CZ_GAMEGUARD_LINGO_READY
#endif

// Packet: 0x02a5
#if PACKETVER >= 20070129
packetLen(0x02a5, 8)  // CZ_KSY_EVENT
#endif

// Packet: 0x02a6
#if PACKETVER >= 20070611
packetLen(0x02a6, 22)  // ZC_HACKSH_CPX_MSG
#endif

// Packet: 0x02a7
#if PACKETVER >= 20070611
packetLen(0x02a7, 22)  // CZ_HACKSH_CPX_MSG
#endif

// Packet: 0x02a8
#if PACKETVER >= 20070611
packetLen(0x02a8, 162)  // ZC_HACKSHIELD_CRC_MSG
#endif

// Packet: 0x02a9
#if PACKETVER >= 20070611
packetLen(0x02a9, 58)  // CZ_HACKSHIELD_CRC_MSG
#endif

// Packet: 0x02aa
#if PACKETVER >= 20070205
packetLen(0x02aa, 4)  // ZC_REQ_CASH_PASSWORD
#endif

// Packet: 0x02ab
#if PACKETVER >= 20070205
packetLen(0x02ab, 36)  // CZ_ACK_CASH_PASSWORD
#endif

// Packet: 0x02ac
#if PACKETVER >= 20070205
packetLen(0x02ac, 6)  // ZC_RESULT_CASH_PASSWORD
#endif

// Packet: 0x02ad
#if PACKETVER >= 20070227
packetLen(0x02ad, 8)  // AC_REQUEST_SECOND_PASSWORD
#endif

// Packet: 0x02ae
#if PACKETVER >= 20070807
// removed
#elif PACKETVER >= 20070711
packetLen(0x02ae, 10)  // ZC_UNUSED_SRPACKET_INIT
#endif

// Packet: 0x02af
#if PACKETVER >= 20070807
// removed
#elif PACKETVER >= 20070711
packetLen(0x02af, 2)  // CZ_SRPACKET_START
#endif

// Packet: 0x02b0
#if PACKETVER >= 20070514
packetLen(0x02b0, 85)  // CA_LOGIN_HAN
#endif

// Packet: 0x02b1
#if PACKETVER >= 20070724
packetLen(0x02b1, -1)  // ZC_ALL_QUEST_LIST
#endif

// Packet: 0x02b2
#if PACKETVER >= 20070807
packetLen(0x02b2, -1)  // ZC_ALL_QUEST_MISSION
#endif

// Packet: 0x02b3
#if PACKETVER >= 20070821
packetLen(0x02b3, 107)  // ZC_ADD_QUEST
#elif PACKETVER >= 20070813
packetLen(0x02b3, 103)  // ZC_ADD_QUEST
#elif PACKETVER >= 20070731
packetLen(0x02b3, 31)  // ZC_ADD_QUEST
#elif PACKETVER >= 20070628
packetLen(0x02b3, 7)  // ZC_ADD_QUEST
#elif PACKETVER >= 20070622
packetLen(0x02b3, 26)  // ZC_ADD_QUEST
#endif

// Packet: 0x02b4
#if PACKETVER >= 20070622
packetLen(0x02b4, 6)  // ZC_DEL_QUEST
#endif

// Packet: 0x02b5
#if PACKETVER >= 20070813
packetLen(0x02b5, -1)  // ZC_UPDATE_MISSION_HUNT
#elif PACKETVER >= 20070807
// removed
#elif PACKETVER >= 20070628
packetLen(0x02b5, 12)  // ZC_UPDATE_MISSION_HUNT
#elif PACKETVER >= 20070622
packetLen(0x02b5, 18)  // ZC_UPDATE_MISSION_HUNT
#endif

// Packet: 0x02b6
#if PACKETVER >= 20070622
packetLen(0x02b6, 7)  // CZ_ACTIVE_QUEST
#endif

// Packet: 0x02b7
#if PACKETVER >= 20070807
packetLen(0x02b7, 7)  // ZC_ACTIVE_QUEST
#elif PACKETVER >= 20070622
packetLen(0x02b7, 10)  // ZC_ACTIVE_QUEST
#endif

// Packet: 0x02b8
#if PACKETVER >= 20070604
packetLen(0x02b8, 22)  // ZC_ITEM_PICKUP_PARTY
#endif

// Packet: 0x02b9
#if PACKETVER >= 20070611
packetLen(0x02b9, 191)  // ZC_SHORTCUT_KEY_LIST
#endif

// Packet: 0x02ba
#if PACKETVER >= 20070618
packetLen(0x02ba, 11)  // CZ_SHORTCUT_KEY_CHANGE
#elif PACKETVER >= 20070611
packetLen(0x02ba, 9)  // CZ_SHORTCUT_KEY_CHANGE
#endif

// Packet: 0x02bb
#if PACKETVER >= 20070622
packetLen(0x02bb, 8)  // ZC_EQUIPITEM_DAMAGED
#elif PACKETVER >= 20070605
packetLen(0x02bb, 4)  // ZC_EQUIPITEM_DAMAGED
#endif

// Packet: 0x02bc
#if PACKETVER >= 20070622
packetLen(0x02bc, 6)  // ZC_NOTIFY_PCBANG_PLAYING_TIME
#endif

// Packet: 0x02bf
#if PACKETVER >= 20070807
packetLen(0x02bf, 10)  // ZC_SRPACKETR2_INIT
#endif

// Packet: 0x02c0
#if PACKETVER >= 20070807
packetLen(0x02c0, 2)  // CZ_SRPACKETR2_START
#endif

// Packet: 0x02c1
#if PACKETVER >= 20070813
packetLen(0x02c1, -1)  // ZC_NPC_CHAT
#endif

// Packet: 0x02c2
#if PACKETVER >= 20070821
packetLen(0x02c2, -1)  // ZC_FORMATSTRING_MSG
#endif

// Packet: 0x02c3
#if PACKETVER >= 20070828
// removed
#elif PACKETVER >= 20070821
packetLen(0x02c3, 4)
#endif

// Packet: 0x02c4
#if PACKETVER >= 20070821
packetLen(0x02c4, 26)  // CZ_PARTY_JOIN_REQ
#endif

// Packet: 0x02c5
#if PACKETVER >= 20070821
packetLen(0x02c5, 30)  // ZC_PARTY_JOIN_REQ_ACK
#endif

// Packet: 0x02c6
#if PACKETVER >= 20070821
packetLen(0x02c6, 30)  // ZC_PARTY_JOIN_REQ
#endif

// Packet: 0x02c7
#if PACKETVER >= 20070821
packetLen(0x02c7, 7)  // CZ_PARTY_JOIN_REQ_ACK
#endif

// Packet: 0x02c8
#if PACKETVER >= 20070821
packetLen(0x02c8, 3)  // CZ_PARTY_CONFIG
#endif

// Packet: 0x02c9
#if PACKETVER >= 20070821
packetLen(0x02c9, 3)  // ZC_PARTY_CONFIG
#endif

// Packet: 0x02ca
#if PACKETVER >= 20070821
packetLen(0x02ca, 3)  // HC_REFUSE_SELECTCHAR
#endif

// Packet: 0x02cb
#if PACKETVER >= 20071023
packetLen(0x02cb, 65)  // ZC_MEMORIALDUNGEON_SUBSCRIPTION_INFO
#elif PACKETVER >= 20070828
packetLen(0x02cb, 20)  // ZC_MEMORIALDUNGEON_SUBSCRIPTION_INFO
#endif

// Packet: 0x02cc
#if PACKETVER >= 20070828
packetLen(0x02cc, 4)  // ZC_MEMORIALDUNGEON_SUBSCRIPTION_NOTIFY
#endif

// Packet: 0x02cd
#if PACKETVER >= 20071023
packetLen(0x02cd, 71)  // ZC_MEMORIALDUNGEON_INFO
#elif PACKETVER >= 20070828
packetLen(0x02cd, 26)  // ZC_MEMORIALDUNGEON_INFO
#endif

// Packet: 0x02ce
#if PACKETVER >= 20070828
packetLen(0x02ce, 10)  // ZC_MEMORIALDUNGEON_NOTIFY
#endif

// Packet: 0x02cf
#if PACKETVER >= 20070828
packetLen(0x02cf, 6)  // CZ_MEMORIALDUNGEON_COMMAND
#endif

// Packet: 0x02d0
#if PACKETVER >= 20070904
packetLen(0x02d0, -1)  // ZC_EQUIPMENT_ITEMLIST3
#endif

// Packet: 0x02d1
#if PACKETVER >= 20070904
packetLen(0x02d1, -1)  // ZC_STORE_EQUIPMENT_ITEMLIST3
#endif

// Packet: 0x02d2
#if PACKETVER >= 20070904
packetLen(0x02d2, -1)  // ZC_CART_EQUIPMENT_ITEMLIST3
#endif

// Packet: 0x02d3
#if PACKETVER >= 20070904
packetLen(0x02d3, 4)  // ZC_NOTIFY_BIND_ON_EQUIP
#endif

// Packet: 0x02d4
#if PACKETVER >= 20070904
packetLen(0x02d4, 29)  // ZC_ITEM_PICKUP_ACK3
#endif

// Packet: 0x02d5
#if PACKETVER >= 20070911
packetLen(0x02d5, 2)  // ZC_ISVR_DISCONNECT
#endif

// Packet: 0x02d6
#if PACKETVER >= 20070918
packetLen(0x02d6, 6)  // CZ_EQUIPWIN_MICROSCOPE
#endif

// Packet: 0x02d7
#if PACKETVER >= 20070918
packetLen(0x02d7, -1)  // ZC_EQUIPWIN_MICROSCOPE
#endif

// Packet: 0x02d8
#if PACKETVER >= 20070918
packetLen(0x02d8, 10)  // CZ_CONFIG
#endif

// Packet: 0x02d9
#if PACKETVER >= 20070918
packetLen(0x02d9, 10)  // ZC_CONFIG
#endif

// Packet: 0x02da
#if PACKETVER >= 20070918
packetLen(0x02da, 3)  // ZC_CONFIG_NOTIFY
#endif

// Packet: 0x02db
#if PACKETVER >= 20071002
packetLen(0x02db, -1)  // CZ_BATTLEFIELD_CHAT
#endif

// Packet: 0x02dc
#if PACKETVER >= 20071002
packetLen(0x02dc, -1)  // ZC_BATTLEFIELD_CHAT
#endif

// Packet: 0x02dd
#if PACKETVER >= 20071002
packetLen(0x02dd, 32)  // ZC_BATTLEFIELD_NOTIFY_CAMPINFO
#endif

// Packet: 0x02de
#if PACKETVER >= 20071002
packetLen(0x02de, 6)  // ZC_BATTLEFIELD_NOTIFY_POINT
#endif

// Packet: 0x02df
#if PACKETVER >= 20071002
packetLen(0x02df, 36)  // ZC_BATTLEFIELD_NOTIFY_POSITION
#endif

// Packet: 0x02e0
#if PACKETVER >= 20071002
packetLen(0x02e0, 34)  // ZC_BATTLEFIELD_NOTIFY_HP
#endif

// Packet: 0x02e1
#if PACKETVER >= 20071113
packetLen(0x02e1, 33)  // ZC_NOTIFY_ACT2
#endif

// Packet: 0x02e2
#if PACKETVER >= 20071120
packetLen(0x02e2, 14)  // CZ_USE_ITEM_NEW_JAPEN
#endif

// Packet: 0x02e3
#if PACKETVER >= 20071120
packetLen(0x02e3, 25)  // CZ_USE_SKILL_NEW_JAPEN
#endif

// Packet: 0x02e4
#if PACKETVER >= 20071120
packetLen(0x02e4, 8)  // CZ_ITEM_PICKUP_NEW_JAPEN
#endif

// Packet: 0x02e5
#if PACKETVER >= 20071120
packetLen(0x02e5, 8)  // CZ_REQUEST_MOVE_NEW_JAPEN
#endif

// Packet: 0x02e6
#if PACKETVER >= 20071120
packetLen(0x02e6, 6)  // CZ_BOT_CHECK
#endif

// Packet: 0x02e7
#if PACKETVER >= 20071127
packetLen(0x02e7, -1)  // ZC_MAPPROPERTY
#endif


#endif /* COMMON_PACKETS2007_LEN_SAK_H */
