#!/bin/bash

ORIG_CWD="$(pwd)"
BASEDIR="$(dirname "$0")"
EXECUTABLE="./map-server"

cd "${BASEDIR}"
if [ -z "$1" ]; then
	exit -1
elif [[ "$1" =~ ^\/ ]]; then
	FILE="$1"
else
	FILE="${ORIG_CWD}/$1"
fi
if [ ! -x "$EXECUTABLE" ]; then
	exit -1
fi
"$EXECUTABLE" --script-check "${FILE}" 2>&1
