#!/bin/sh

# Copyright (c) Hercules Dev Team, licensed under GNU GPL.
# See the LICENSE file
# Base Author: Haru @ http://hercules.ws

ORIG_CWD="$(pwd)"
BASEDIR="$(dirname "$0")"
EXECUTABLE="./map-server"

cd "${BASEDIR}"
if [ -z "$1" ]; then
	echo "No file specified."
	echo "Usage: $0 <path to the script>"
	echo " (you may use a relative or absolute path)"
	exit 1
fi
case "$1" in
	/*)
		FILE="$1"
		;;
	*)
		FILE="${ORIG_CWD}/$1"
		;;
esac
if [ ! -x "$EXECUTABLE" ]; then
	exit 1
fi

while [ -n "$1" ]; do
	[ -n "$FILES" ] && FILES="${FILES}!"
	if [[ "$1" =~ ^\/ ]]; then
		FILES="${FILES}--load-script!$1"
	else
		FILES="${FILES}--load-script!${ORIG_CWD}/$1"
	fi
	shift
done

# We assume that filenames don't contain exclamation marks.
IFS=!
"$EXECUTABLE" --script-check $FILES 2>&1
