--
-- Table structure for table `mob_skill_db2`
--

DROP TABLE IF EXISTS `mob_skill_db2`;
CREATE TABLE IF NOT EXISTS `mob_skill_db2` (
  `MOB_ID` SMALLINT(6) NOT NULL,
  `INFO` TEXT NOT NULL,
  `STATE` TEXT NOT NULL,
  `SKILL_ID` SMALLINT(6) NOT NULL,
  `SKILL_LV` TINYINT(4) NOT NULL,
  `RATE` SMALLINT(4) NOT NULL,
  `CASTTIME` MEDIUMINT(9) NOT NULL,
  `DELAY` INT(9) NOT NULL,
  `CANCELABLE` TEXT NOT NULL,
  `TARGET` TEXT NOT NULL,
  `CONDITION` TEXT NOT NULL,
  `CONDITION_VALUE` TEXT,
  `VAL1` MEDIUMINT(9) DEFAULT NULL,
  `VAL2` MEDIUMINT(9) DEFAULT NULL,
  `VAL3` MEDIUMINT(9) DEFAULT NULL,
  `VAL4` MEDIUMINT(9) DEFAULT NULL,
  `VAL5` MEDIUMINT(9) DEFAULT NULL,
  `EMOTION` TEXT,
  `CHAT` TEXT
) ENGINE=MyISAM;
