#
# Patch to increase the number of item ids over 65k (maximun id limit is ~2kkk)
# By Frey/Gustavo Brigo
#
ALTER TABLE `auction` MODIFY `card0` int(11) NOT NULL default '0',
ALTER TABLE `auction` MODIFY `card1` int(11) NOT NULL default '0',
ALTER TABLE `auction` MODIFY `card2` int(11) NOT NULL default '0',
ALTER TABLE `auction` MODIFY `card3` int(11) NOT NULL default '0',
ALTER TABLE `cart_inventory` MODIFY `card0` int(11) NOT NULL default '0',
ALTER TABLE `cart_inventory` MODIFY `card1` int(11) NOT NULL default '0',
ALTER TABLE `cart_inventory` MODIFY `card2` int(11) NOT NULL default '0',
ALTER TABLE `cart_inventory` MODIFY `card3` int(11) NOT NULL default '0',
ALTER TABLE `guild_storage` MODIFY `card0` int(11) NOT NULL default '0',
ALTER TABLE `guild_storage` MODIFY `card1` int(11) NOT NULL default '0',
ALTER TABLE `guild_storage` MODIFY `card2` int(11) NOT NULL default '0',
ALTER TABLE `guild_storage` MODIFY `card3` int(11) NOT NULL default '0',
ALTER TABLE `inventory` MODIFY `card0` int(11) NOT NULL default '0',
ALTER TABLE `inventory` MODIFY `card1` int(11) NOT NULL default '0',
ALTER TABLE `inventory` MODIFY `card2` int(11) NOT NULL default '0',
ALTER TABLE `inventory` MODIFY `card3` int(11) NOT NULL default '0',
ALTER TABLE `storage` MODIFY `card0` int(11) NOT NULL default '0',
ALTER TABLE `storage` MODIFY `card1` int(11) NOT NULL default '0',
ALTER TABLE `storage` MODIFY `card2` int(11) NOT NULL default '0',
ALTER TABLE `storage` MODIFY `card3` int(11) NOT NULL default '0',
ALTER TABLE `mail` MODIFY `card0` int(11) NOT NULL default '0',
ALTER TABLE `mail` MODIFY `card1` int(11) NOT NULL default '0',
ALTER TABLE `mail` MODIFY `card2` int(11) NOT NULL default '0',
ALTER TABLE `mail` MODIFY `card3` int(11) NOT NULL default '0',
ALTER TABLE `mob_db` MODIFY `MVP1id` int(11) unsigned NOT NULL default '0',
ALTER TABLE `mob_db` MODIFY `MVP1per` int(11) unsigned NOT NULL default '0',
ALTER TABLE `mob_db` MODIFY `MVP2id` int(11) unsigned NOT NULL default '0',
ALTER TABLE `mob_db` MODIFY `MVP2per` int(11) unsigned NOT NULL default '0',
ALTER TABLE `mob_db` MODIFY `MVP3id` int(11) unsigned NOT NULL default '0',
ALTER TABLE `mob_db` MODIFY `MVP3per` int(11) unsigned NOT NULL default '0',
ALTER TABLE `mob_db` MODIFY `Drop1id` int(11) unsigned NOT NULL default '0',
ALTER TABLE `mob_db` MODIFY `Drop1per` int(11) unsigned NOT NULL default '0',
ALTER TABLE `mob_db` MODIFY `Drop2id` int(11) unsigned NOT NULL default '0',
ALTER TABLE `mob_db` MODIFY `Drop2per` int(11) unsigned NOT NULL default '0',
ALTER TABLE `mob_db` MODIFY `Drop3id` int(11) unsigned NOT NULL default '0',
ALTER TABLE `mob_db` MODIFY `Drop3per` int(11) unsigned NOT NULL default '0',
ALTER TABLE `mob_db` MODIFY `Drop4id` int(11) unsigned NOT NULL default '0',
ALTER TABLE `mob_db` MODIFY `Drop4per` int(11) unsigned NOT NULL default '0',
ALTER TABLE `mob_db` MODIFY `Drop5id` int(11) unsigned NOT NULL default '0',
ALTER TABLE `mob_db` MODIFY `Drop5per` int(11) unsigned NOT NULL default '0',
ALTER TABLE `mob_db` MODIFY `Drop6id` int(11) unsigned NOT NULL default '0',
ALTER TABLE `mob_db` MODIFY `Drop6per` int(11) unsigned NOT NULL default '0',
ALTER TABLE `mob_db` MODIFY `Drop7id` int(11) unsigned NOT NULL default '0',
ALTER TABLE `mob_db` MODIFY `Drop7per` int(11) unsigned NOT NULL default '0',
ALTER TABLE `mob_db` MODIFY `Drop8id` int(11) unsigned NOT NULL default '0',
ALTER TABLE `mob_db` MODIFY `Drop8per` int(11) unsigned NOT NULL default '0',
ALTER TABLE `mob_db` MODIFY `Drop9id` int(11) unsigned NOT NULL default '0',
ALTER TABLE `mob_db` MODIFY `Drop9per` int(11) unsigned NOT NULL default '0',
ALTER TABLE `mob_db` MODIFY `DropCardid` int(11) unsigned NOT NULL default '0',
ALTER TABLE `mob_db` MODIFY `DropCardper` int(11) unsigned NOT NULL default '0',
ALTER TABLE `mob_db2` MODIFY `MVP1id` int(11) unsigned NOT NULL default '0',
ALTER TABLE `mob_db2` MODIFY `MVP1per` int(11) unsigned NOT NULL default '0',
ALTER TABLE `mob_db2` MODIFY `MVP2id` int(11) unsigned NOT NULL default '0',
ALTER TABLE `mob_db2` MODIFY `MVP2per` int(11) unsigned NOT NULL default '0',
ALTER TABLE `mob_db2` MODIFY `MVP3id` int(11) unsigned NOT NULL default '0',
ALTER TABLE `mob_db2` MODIFY `MVP3per` int(11) unsigned NOT NULL default '0',
ALTER TABLE `mob_db2` MODIFY `Drop1id` int(11) unsigned NOT NULL default '0',
ALTER TABLE `mob_db2` MODIFY `Drop1per` int(11) unsigned NOT NULL default '0',
ALTER TABLE `mob_db2` MODIFY `Drop2id` int(11) unsigned NOT NULL default '0',
ALTER TABLE `mob_db2` MODIFY `Drop2per` int(11) unsigned NOT NULL default '0',
ALTER TABLE `mob_db2` MODIFY `Drop3id` int(11) unsigned NOT NULL default '0',
ALTER TABLE `mob_db2` MODIFY `Drop3per` int(11) unsigned NOT NULL default '0',
ALTER TABLE `mob_db2` MODIFY `Drop4id` int(11) unsigned NOT NULL default '0',
ALTER TABLE `mob_db2` MODIFY `Drop4per` int(11) unsigned NOT NULL default '0',
ALTER TABLE `mob_db2` MODIFY `Drop5id` int(11) unsigned NOT NULL default '0',
ALTER TABLE `mob_db2` MODIFY `Drop5per` int(11) unsigned NOT NULL default '0',
ALTER TABLE `mob_db2` MODIFY `Drop6id` int(11) unsigned NOT NULL default '0',
ALTER TABLE `mob_db2` MODIFY `Drop6per` int(11) unsigned NOT NULL default '0',
ALTER TABLE `mob_db2` MODIFY `Drop7id` int(11) unsigned NOT NULL default '0',
ALTER TABLE `mob_db2` MODIFY `Drop7per` int(11) unsigned NOT NULL default '0',
ALTER TABLE `mob_db2` MODIFY `Drop8id` int(11) unsigned NOT NULL default '0',
ALTER TABLE `mob_db2` MODIFY `Drop8per` int(11) unsigned NOT NULL default '0',
ALTER TABLE `mob_db2` MODIFY `Drop9id` int(11) unsigned NOT NULL default '0',
ALTER TABLE `mob_db2` MODIFY `Drop9per` int(11) unsigned NOT NULL default '0',
ALTER TABLE `mob_db2` MODIFY `DropCardid` int(11) unsigned NOT NULL default '0',
ALTER TABLE `mob_db2` MODIFY `DropCardper` int(11) unsigned NOT NULL default '0',