/**
 * This file is part of Hercules.
 * http://herc.ws - http://github.com/HerculesWS/Hercules
 *
 * Copyright (C) 2013-2018  Hercules Dev Team
 *
 * Hercules is free software: you can redistribute it and/or modify
 * it under the terms of the GNU General Public License as published by
 * the Free Software Foundation, either version 3 of the License, or
 * (at your option) any later version.
 *
 * This program is distributed in the hope that it will be useful,
 * but WITHOUT ANY WARRANTY; without even the implied warranty of
 * MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
 * GNU General Public License for more details.
 *
 * You should have received a copy of the GNU General Public License
 * along with this program.  If not, see <http://www.gnu.org/licenses/>.
 */

#ifndef MAP_PACKETS_ZERO_KEYS_H
#define MAP_PACKETS_ZERO_KEYS_H

#ifndef packetKeys
	#define packetKeys(a,b,c)
#endif

/* PacketKeys: http://herc.ws/board/topic/1105-hercules-wpe-free-june-14th-patch/ */

/* This file is autogenerated, please do not commit manual changes */

// 2017-10-18aRagexe_zero, 2017-10-19aRagexe_zero, 2017-10-23aRagexe_zero, 2017-10-23bRagexe_zero, 2017-10-23cRagexe_zero, 2017-10-24aRagexe_2_zero, 2017-10-24aRagexe_zero, 2017-10-25bRagexe_zero, 2017-10-27aRagexe_zero, 2017-10-27bRagexe_zero, 2017-10-30aRagexe_zero, 2017-10-31aRagexe_zero, 2017-11-09aRagexe_zero, 2017-11-13aRagexe_zero, 2017-11-13bRagexe_zero, 2018-03-15aRagexe_zero, 2018-03-21aRagexe_zero, 2018-03-21bRagexe_zero, 2018-03-28_1aRagexe_zero, 2018-03-28cRagexe_zero, 2018-04-11aRagexe_zero, 2018-04-25_3aRagexe_zero, 2018-05-09_3aRagexe_zero, 2018-05-23aRagexe_zero, 2018-06-05bRagexe_zero, 2018-06-05cRagexe_zero
#if PACKETVER == 20171018 || \
    PACKETVER == 20171019 || \
    PACKETVER == 20171023 || \
    PACKETVER == 20171024 || \
    PACKETVER == 20171025 || \
    PACKETVER == 20171027 || \
    PACKETVER == 20171030 || \
    PACKETVER == 20171031 || \
    PACKETVER == 20171109 || \
    PACKETVER == 20171113 || \
    PACKETVER == 20180315 || \
    PACKETVER == 20180321 || \
    PACKETVER == 20180328 || \
    PACKETVER == 20180411 || \
    PACKETVER == 20180425 || \
    PACKETVER == 20180509 || \
    PACKETVER == 20180523 || \
    PACKETVER >= 20180605
	packetKeys(0x00000000,0x00000000,0x00000000);
#endif

// 2017-11-15aRagexe_zero, 2017-11-15bRagexe_zero, 2017-11-16aRagexe_zero, 2017-11-17aRagexe_zero
#if PACKETVER == 20171115 || \
    PACKETVER == 20171116 || \
    PACKETVER == 20171117
	packetKeys(0x3B93061D,0x3CB50DCD,0x410A197E);
#endif

// 2017-11-21aRagexe_zero, 2017-11-22aRagexe_zero
#if PACKETVER == 20171121 || \
    PACKETVER == 20171122
	packetKeys(0x195B4DA8,0x6E3A473B,0x126F4B61);
#endif

// 2017-11-23dRagexe_zero
#if PACKETVER == 20171123
	packetKeys(0x6087733A,0x5C5C4AEE,0x0F10408F);
#endif

// 2017-11-27aRagexe_zero, 2017-11-27cRagexe_zero, 2017-11-28aRagexe_zero
#if PACKETVER == 20171127 || \
    PACKETVER == 20171128
	packetKeys(0x141C135C,0x675C275C,0x275C275C);
#endif

// 2017-11-30bRagexe_zero
#if PACKETVER == 20171130
	packetKeys(0x31A04B32,0x3AC96B76,0x1742085D);
#endif

// 2017-12-04bRagexe_zero
#if PACKETVER == 20171204
	packetKeys(0x06A109F1,0x6A953256,0x0A6040A3);
#endif

// 2017-12-06aRagexe_zero, 2017-12-06bRagexe_zero, 2017-12-06cRagexe_zero, 2017-12-06dRagexe_zero, 2017-12-08aRagexe_zero, 2017-12-08cRagexe_zero, 2017-12-08dRagexe_zero, 2017-12-09bRagexe_zero, 2017-12-09cRagexe_zero, 2017-12-10aRagexe_zero, 2017-12-11bRagexe_zero, 2017-12-12aRagexe_zero, 2017-12-13aRagexe_zero, 2017-12-13bRagexe_zero, 2017-12-13cRagexe_zero
#if PACKETVER == 20171206 || \
    PACKETVER == 20171208 || \
    PACKETVER == 20171209 || \
    PACKETVER == 20171210 || \
    PACKETVER == 20171211 || \
    PACKETVER == 20171212 || \
    PACKETVER == 20171213
	packetKeys(0x718D0388,0x56A11525,0x20042F67);
#endif

// 2017-12-14cRagexe_zero
#if PACKETVER == 20171214
	packetKeys(0x6CE1021D,0x77703B04,0x4E722232);
#endif

// 2017-12-20aRagexe_zero, 2017-12-21aRagexe_zero, 2017-12-21bRagexe_zero
#if PACKETVER == 20171220 || \
    PACKETVER == 20171221
	packetKeys(0x1E2047D2,0x7EE31AC2,0x31434F61);
#endif

// 2017-12-27bRagexe_zero, 2017-12-29aRagexe_zero
#if PACKETVER == 20171227 || \
    PACKETVER == 20171229
	packetKeys(0x7CBF0846,0x02F92654,0x22AA5E2D);
#endif

// 2018-01-03aRagexe_zero
#if PACKETVER == 20180103
	packetKeys(0x2A3D4E64,0x7008690C,0x69FF066F);
#endif

// 2018-01-17aRagexe_zero
#if PACKETVER == 20180117
	packetKeys(0x230959EB,0x1CCB0182,0x1FFA2B30);
#endif

// 2018-01-31dRagexe_zero
#if PACKETVER == 20180131
	packetKeys(0x1F422E02,0x12025202,0x52025202);
#endif

// 2018-02-07bRagexe_zero
#if PACKETVER == 20180207
	packetKeys(0x07CB29CB,0x69CB69CB,0x69CB69CB);
#endif

// 2018-02-13aRagexe_zero
#if PACKETVER == 20180213
	packetKeys(0x0513075E,0x347075AF,0x67C56C6F);
#endif

// 2018-02-21aRagexe_zero
#if PACKETVER == 20180221
	packetKeys(0x28ED7635,0x76591F21,0x59383498);
#endif

// 2018-02-28bRagexe_zero, 2018-03-07aRagexe_zero, 2018-03-09aRagexe_zero
#if PACKETVER == 20180228 || \
    PACKETVER == 20180307 || \
    PACKETVER == 20180309
	packetKeys(0x56C82ABE,0x61AE2B2E,0x472E272E);
#endif

// 2018-03-14nRagexe_zero
#if PACKETVER == 20180314
	packetKeys(0x2FC330DD,0x01C04E1F,0x4D914DE2);
#endif

// 2018-05-11aRagexe_zero, 2018-05-11bRagexe_zero
#if PACKETVER == 20180511
	packetKeys(0x1C055B65,0x68CE748D,0x32AF761D);
#endif


#endif /* MAP_PACKETS_ZERO_KEYS_H */
