/**
 * This file is part of Hercules.
 * http://herc.ws - http://github.com/HerculesWS/Hercules
 *
 * Copyright (C) 2012-2020 Hercules Dev Team
 * Copyright (C) Athena Dev Teams
 *
 * Hercules is free software: you can redistribute it and/or modify
 * it under the terms of the GNU General Public License as published by
 * the Free Software Foundation, either version 3 of the License, or
 * (at your option) any later version.
 *
 * This program is distributed in the hope that it will be useful,
 * but WITHOUT ANY WARRANTY; without even the implied warranty of
 * MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
 * GNU General Public License for more details.
 *
 * You should have received a copy of the GNU General Public License
 * along with this program.  If not, see <http://www.gnu.org/licenses/>.
 */
#define HERCULES_CORE

#include "config/core.h" // AUTOTRADE_PERSISTENCY
#include "aloginif.h"

#include "api/aclif.h"
#include "api/api.h"
#include "common/HPM.h"
#include "common/cbasetypes.h"
#include "common/ers.h"
#include "common/memmgr.h"
#include "common/nullpo.h"
#include "common/showmsg.h"
#include "common/socket.h"
#include "common/strlib.h"
#include "common/timer.h"

#include <stdio.h>
#include <stdlib.h>
#include <sys/types.h>

static struct aloginif_interface aloginif_s;
struct aloginif_interface *aloginif;


// sets login-server's user id
static void aloginif_setuserid(char *id)
{
	nullpo_retv(id);
	memcpy(aloginif->userid, id, NAME_LENGTH);
}

// sets login-server's password
static void aloginif_setpasswd(char *pwd)
{
	nullpo_retv(pwd);
	memcpy(aloginif->passwd, pwd, NAME_LENGTH);
}

// security check, prints warning if using default password
static void aloginif_checkdefaultlogin(void)
{
#ifndef BUILDBOT
	if (strcmp(aloginif->userid, "s1")==0 && strcmp(aloginif->passwd, "p1")==0) {
		ShowWarning("Using the default user/password s1/p1 is NOT RECOMMENDED.\n");
		ShowNotice("Please edit your 'login' table to create a proper inter-server user/password (gender 'S')\n");
		ShowNotice("and then edit your user/password in conf/api-server.conf (or conf/import/api_conf.txt)\n");
	}
#endif
}

// sets login-server's ip address
static bool aloginif_setip(const char *ip)
{
	char ip_str[16];

	nullpo_retr(false, ip);
	if (!(aloginif->ip = sockt->host2ip(ip))) {
		ShowWarning("Failed to Resolve Login Server Address! (%s)\n", ip);
		return false;
	}

	safestrncpy(aloginif->ip_str, ip, sizeof(aloginif->ip_str));

	ShowInfo("Login Server IP Address : '"CL_WHITE"%s"CL_RESET"' -> '"CL_WHITE"%s"CL_RESET"'.\n", ip, sockt->ip2str(aloginif->ip, ip_str));

	return true;
}

// sets login-server's port number
static void aloginif_setport(uint16 port)
{
	aloginif->port = port;
}

/*==========================================
 *
 *------------------------------------------*/
static int aloginif_parse(int fd)
{
	return 0;
}

/*==========================================
 * Destructor
 *------------------------------------------*/
static void do_final_aloginif(void)
{
	if (aloginif->fd != -1) {
		sockt->close(aloginif->fd);
		aloginif->fd = -1;
	}
}

/*==========================================
 *
 *------------------------------------------*/
static void do_init_aloginif(bool minimal)
{
	if (minimal)
		return;

}

/*=====================================
* Default Functions : aloginif.h
* Generated by HerculesInterfaceMaker
* created by Susu
*-------------------------------------*/
void aloginif_defaults(void)
{
	const int packet_len_table[ALOGINIF_PACKET_LEN_TABLE_SIZE] = { // U - used, F - free
		60,  3, -1, 27, 10, -1,  6, -1, // 2af8-2aff: U->2af8, U->2af9, U->2afa, U->2afb, U->2afc, U->2afd, U->2afe, U->2aff
		 6, -1, 18,  7, -1, 39, 30, 10, // 2b00-2b07: U->2b00, U->2b01, U->2b02, U->2b03, U->2b04, U->2b05, U->2b06, U->2b07
		 6, 30, -1,  0, 86,  7, 44, 34, // 2b08-2b0f: U->2b08, U->2b09, U->2b0a, F->2b0b, U->2b0c, U->2b0d, U->2b0e, U->2b0f
		11, 10, 10,  0, 11,  0,266, 10, // 2b10-2b17: U->2b10, U->2b11, U->2b12, F->2b13, U->2b14, F->2b15, U->2b16, U->2b17
		 2, 10,  2, -1, -1, -1,  2,  7, // 2b18-2b1f: U->2b18, U->2b19, U->2b1a, U->2b1b, U->2b1c, U->2b1d, U->2b1e, U->2b1f
		-1, 10,  8,  2,  2, 14, 19, 19, // 2b20-2b27: U->2b20, U->2b21, U->2b22, U->2b23, U->2b24, U->2b25, U->2b26, U->2b27
	};

	aloginif = &aloginif_s;

	/* vars */
	aloginif->connected = 0;

	memcpy(aloginif->packet_len_table, &packet_len_table, sizeof(aloginif->packet_len_table));
	aloginif->fd = -1;
	aloginif->srvinfo = 0;
	memset(aloginif->ip_str, 0, sizeof(aloginif->ip_str));
	aloginif->ip = 0;
	aloginif->port = 6900;
	memset(aloginif->userid, 0, sizeof(aloginif->userid));
	memset(aloginif->passwd, 0, sizeof(aloginif->passwd));
	aloginif->state = 0;

	/* */
	aloginif->init = do_init_aloginif;
	aloginif->final = do_final_aloginif;

	/* funcs */
	aloginif->setuserid = aloginif_setuserid;
	aloginif->setpasswd = aloginif_setpasswd;
	aloginif->checkdefaultlogin = aloginif_checkdefaultlogin;
	aloginif->setip = aloginif_setip;
	aloginif->setport = aloginif_setport;

	aloginif->parse = aloginif_parse;
}
