#1458421443
ALTER TABLE `guild_position` CHANGE `mode` `mode` SMALLINT(5) UNSIGNED NOT NULL DEFAULT  '0';
ALTER TABLE `guild` ADD `max_storage` SMALLINT(6) UNSIGNED NOT NULL DEFAULT '0' AFTER `max_member`;
INSERT INTO `sql_updates` (`timestamp`) VALUES (1458421443);
