#1488744559

ALTER TABLE `picklog`
	ADD COLUMN `opt_idx0` SMALLINT UNSIGNED NOT NULL DEFAULT '0' AFTER `card3`,
	ADD COLUMN `opt_val0` SMALLINT NOT NULL DEFAULT '0' AFTER `opt_idx0`,
	ADD COLUMN `opt_idx1` SMALLINT UNSIGNED NOT NULL DEFAULT '0' AFTER `opt_val0`,
	ADD COLUMN `opt_val1` SMALLINT NOT NULL DEFAULT '0' AFTER `opt_idx1`,
	ADD COLUMN `opt_idx2` SMALLINT UNSIGNED NOT NULL DEFAULT '0' AFTER `opt_val1`,
	ADD COLUMN `opt_val2` SMALLINT NOT NULL DEFAULT '0' AFTER `opt_idx2`,
	ADD COLUMN `opt_idx3` SMALLINT UNSIGNED NOT NULL DEFAULT '0' AFTER `opt_val2`,
	ADD COLUMN `opt_val3` SMALLINT NOT NULL DEFAULT '0' AFTER `opt_idx3`,
	ADD COLUMN `opt_idx4` SMALLINT UNSIGNED NOT NULL DEFAULT '0' AFTER `opt_val3`,
	ADD COLUMN `opt_val4` SMALLINT NOT NULL DEFAULT '0' AFTER `opt_idx4`;

INSERT INTO `sql_updates` (`timestamp`, `ignored`) VALUES (1488744559 , 'No');
