name: mariadb

on: workflow_call

env:
  MYSQL_DATABASE: 'ragnarok'
  MYSQL_USER: 'ragnarok'
  MYSQL_PASSWORD: 'ragnarok'
  MYSQL_ALLOW_EMPTY_PASSWORD: 'yes'
  DEBIAN_COMMON_PACKAGES: cmake make git python3 python3-venv libzstd-dev g++

defaults:
  run:
    shell: bash

jobs:
  build:
    runs-on: ubuntu-latest
    timeout-minutes: 30
    strategy:
      matrix:
        CC: [gcc-15]
        RENEWAL: [""]
        CLIENT_TYPE: [""]
        HTTPLIB: ["", "-DWITH_HTTP_PARSER=llhttp"]
        SANITIZER: ["-DMEMORY_MANAGER=none", "-DMEMORY_MANAGER=none -DENABLE_SANITIZE=ON"]
        PACKET_VERSION: ["-DPACKETVER=20221024"]
        MYSQL: ["10.11", "11.8", "latest"]
        include:
          - CXX: 'g++-15'
            CC: 'gcc-15'

    # github.head_ref will stop previous runs in the same PR (if in a PR)
    # github.run_id is a fallback when outside a PR (e.g. every merge in master will run, and previous won't stop)
    concurrency:
      group: mariadb-${{ github.head_ref || github.run_id }}_${{ matrix.CC }}_${{ matrix.RENEWAL }}_${{ matrix.CLIENT_TYPE }}_${{ matrix.HTTPLIB }}_${{ matrix.SANITIZER }}_${{ matrix.PACKET_VERSION}}_${{ matrix.MYSQL }}
      cancel-in-progress: true

    container:
      image: ubuntu:26.04
    services:
      mysql:
        image: mariadb:${{ matrix.MYSQL }}
        ports:
          - 33306:3306
        env:
          MYSQL_DATABASE: 'ragnarok'
          MYSQL_USER: 'ragnarok'
          MYSQL_PASSWORD: 'ragnarok'
          MYSQL_ALLOW_EMPTY_PASSWORD: 'yes'
        options: >-
          --health-cmd="healthcheck.sh --connect --innodb_initialized"
          --health-interval=5s
          --health-timeout=2s
          --health-retries=3
    env:
      INSTALL_PACKAGES: ${{ matrix.CC }} ${{ matrix.CXX }} mariadb-client
      SQLHOST: mysql
      CC: ${{ matrix.CC }}
      CXX: ${{ matrix.CXX }}
      CONFIGURE_FLAGS: -DCMAKE_C_COMPILER=${{ matrix.CC }} -DCMAKE_CXX_COMPILER=${{ matrix.CXX }} -DCMAKE_BUILD_TYPE=Debug -DENABLE_WERROR=ON -DENABLE_BUILDBOT=ON ${{ matrix.RENEWAL }} ${{ matrix.HTTPLIB }} ${{ matrix.CLIENT_TYPE }} ${{ matrix.SANITIZER }} ${{ matrix.PACKET_VERSION }} -DBUILD_HPMHOOKING=ON
      PACKET_VERSION: ${{ matrix.PACKET_VERSION }}
    steps:
      - uses: actions/checkout@v6
        with:
          fetch-depth: 1

      - name: info
        run: |
          uname -a

      - uses: actions/cache/restore@v6
        name: restore conan cache
        id: cache
        with:
          path: ~/.conan2
          key: ${{ runner.os }}-${{ matrix.CC }}-${{ hashFiles('conanfile.py') }}

      - name: install packages
        run: |
          ./tools/ci/retry.sh apt-get update
          ./tools/ci/retry.sh apt-get install -y -qq $INSTALL_PACKAGES $DEBIAN_COMMON_PACKAGES

      - name: init database
        run: |
          ./tools/ci/travis.sh importdb ragnarok ragnarok ragnarok $SQLHOST

      - name: get plugins
        run: |
          ./tools/ci/travis.sh getplugins || true

      - name: build
        run: |
          ./tools/ci/travis.sh prepareenv
          source .venv/bin/activate
          ./tools/ci/travis.sh build $CONFIGURE_FLAGS

      - name: test
        run: |
          ./tools/ci/travis.sh test ragnarok ragnarok ragnarok $SQLHOST

      - name: extra test
        if: env.PACKET_VERSION != '-DPACKETVER=20130724'
        run: |
          ./tools/ci/travis.sh extratest
